### PR TITLE
First ECC support for the minidriver

### PR DESCRIPTION
**Pull request by vletoux**
ECC signature and DH agreements. ECC keys can now be shown with certutil -scinfo.

### CODE REVIEW

**Comment by frankmorgner** [comment]
Hmm, a review is kind of hard, you are adding more than loc in a single commit so that even github does not show the changes by default. I hope that someone with an ECC card finds the time to look into the code (@philipWendland? @viktorTarasov?), but I'm pretty sure this will take some time...

**Comment by vletoux** [comment]
Well the main modifications are in :
CardGetContainerInfo
CardSignData
Card*DH*
CardDeriveKey

I couldn't commit the function returning the public key without having verified that the signature produced does produce a match.
=> do a diff between the two versions of the file and you will find 3 major blocks of code change, very easy to check

I'm busy doing some minor modifications after a pass of the minidriver quality tool (cmck.exe).
In progress: a better read/write support (for example a real implementation of CardDeleteContainer)
=> I'll produce some other commits

**Comment by philipWendland** [comment]
Sorry, currently I do not have a way to test this.

**Comment by vletoux** [comment]
ECC (and now RSA) certificate request is working when using ADCS (Active Directory Certificate Service)
Need to enable in the configuration : "md_read_only" to false; "md_supports_X509_enrollment" to true and "md_guid_as_label" to true
ECC smart card logon doesn't seem to work yet.

**Comment by dengert** [comment]
Login to AD uses Kerberos's PKINIT.

https://technet.microsoft.com/en-us/library/dd560670(v=ws.10).aspx

Says: Windows 7 and Windows Server 2008 R2 are required for ECC and smart cards.


http://download.microsoft.com/download/9/5/E/95EF66AF-9026-4BB0-A41D-A4F81802D92C/[MS-PKCA].pdf

Foot note <6> says:
ECC is not supported by Windows 2000, Windows XP, Windows Server 2003, Windows Vista, or Windows Server 2008.




On 10/3/2015 12:43 PM, vletoux wrote:
> ECC (and now RSA) certificate request is working when using ADCS (Active Directory Certificate Service)
> Need to enable in the configuration : "md_read_only" to false; "md_supports_X509_enrollment" to true and "md_guid_as_label" to true
> ECC smart card logon doesn't seem to work yet.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-145271792>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
Yes, I know all that (smart card logon is the core business of my company)

Just stuck at this error message
an-error-occured-trying-to-use-this-smart-card

I've written everything to setup ECC here:
http://www.mysmartlogon.com/knowledge-base/ecc-smart-card-logon/

**Comment by vletoux** [comment]
ok: the problem is with the "OpenSC CSP" trick I used to avoid the need for smart card drivers.
(Even if the drivers are provided, you'll have to sign them and manually validate each of them at the installation)
**When the CSP name is replaced with the Base smart card CSP name, the ECC smart card logon works.**

The root cause is that the Smart card credential provider send to the kerberos security package the name of the CSP (instead of the KSP).
The smart card KSP is using a trick to make it works. In HKLM\CurrentControlSet\Control\Cryptograpy\Providers each provider can have an alias for the old CSP. If I add the "OpenSC CSP" as an alias, the provider get loaded. The problem is that the provider checks at the begining the alias. And the Base CSP is hardcoded here.
base ksp check


=> there is choice to make between "minidriver autoinstallation without a driver and keeping the driver autodetection active" and "ECC smart card logon".

**Comment by frankmorgner** [comment]
@vletoux I know that you explained the trick in depth somewhere. Do you have a link to the site or mail to understand the consequences of "verifying/signing/*not* autodetecting the driver?

**Comment by vletoux** [comment]
There is no consequence using a CSP <> the Base CSP because there is 2 models:
* The first one with the old CSP (<> Base CSP) with no autodetection
* The new one with the minidriver / smart card recognized as a driver with autodetection

I used a trick to make the 2nd model recognized as the 1st one.
But Microsoft used itself a trick for smart card logon. They are submitting the CSP instead of the KSP for ECC logon and then using an alias of the KSP to make the match.
The problem is that Microsoft hardcoded the CSP authorized to make the trick (my screenshot) and because I make an alias of the CSP to make it work, my CSP name is not recognized as an KSP alias.

I'll have to launch a new discussion about the minidriver when the discussion about the container name will be closed.
But on my opinion:
* it is ok to keep the OpenSC CSP alias for pure RSA cards (no autodetection)
* for ECC card, disable the autodetection or prepare inf files
(I describe it here http://www.mysmartlogon.com/knowledge-base/a-smart-card-was-detect-but-is-not-the-one-required-for-the-current-operation/)

There is a Microsoft KB about that:
https://support.microsoft.com/en-us/kb/976832

**Comment by frankmorgner** [comment]
If I understood correctly, we only need the OpenSC CSP alias because we don't want to sign our minidriver. My question was about the overhad if we were signing/verifying the minidriver so that the alias would not be needed anymore. Without the alias (and with a "real" minidriver) I assumed that we could achieve auto-detection for both, RSA and EC based cards.

**Comment by vletoux** [comment]
If you want to sign the minidriver, you'll need a code signing certificate (no need for a kernel code certificate). Last time I checked, you need to enroll it as an individual with physical check and check with a private owned domain or as a company (registered phone, ...).

Then, you can sign and timestamp 1) only an empty inf file using a .cat file (this will allow update of the code) or 2) make an inf file referencing the minidriver .dll file. In this case, all the future update will need to be signed too.
A signed minidriver can be deployed with Windows Update with a fee (last time I checked: 400$ per OS)

You will need a signed inf file for EACH card (each ATR). This will be a problem for javacards having different ATR.
A minidriver with an invalid shows a big red warning each time it is inserted in a new smart card reader.

**Comment by frankmorgner** [comment]
OK, understood. Issuing a "real" minidriver is not really an option.

Your suggestion about auto-detection for RSA cards and inf-files for ECC files sounds reasonable.

**Comment by dengert** [comment]
What about mix mode cards, some certificates are RSA some are ECC?

What about Windows 8 and Windows 10?
Microsoft (and other vendors) are moving a "store" approach for downloading software
where the software is signed. This would imply that the minidriver will have to be signed in all future systems.




On 10/7/2015 5:48 AM, Frank Morgner wrote:
> OK, understood. Issuing a "real" minidriver is not really an option.
>
> Your suggestion about auto-detection for RSA cards and inf-files for ECC files sounds reasonable.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-146153843>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
Sorry the previous link I gave was wrong. Here is the correct one:
http://www.mysmartlogon.com/service/searching-driver-time-smart-card-connected/

If there are ECC capabilities (RSA + ECC) you'll have to disable the plug & play for smart card or install a "driver" with an inf file.

On my opinion OpenSC cannot be deployed by the windows store because it is an infrastructure solution requering admin rights & a driver installation. Adding a digital signature will solve only the trust part of the installation.
That's why I think that this is not "mandatory"

If you request it, I can built an inf file for every card and ask their installation when the setup is run.
(one popup for each inf file to install)

Maybe SCFILTER entries can be combined to have one driver instead of many.

**Comment by frankmorgner** [comment]
I only reviewd on 6cbeea3.

It is OK to do some refactoring changes like removing the use of cardcf, but please remove them entirely instead of just commenting. I hope to find time to look at the rest of the commits soon.

**Comment by frankmorgner** [comment]
Is "one popup for each inf file to install" a technical limitation or could we offer the choice of selecting checkboxes during the wix installer?

**Comment by vletoux** [comment]
@frankmorgner I've fixed some things according to your comment.
I won't change secp256r1 because i think this change is out of the minidriver side.
I changed everything else I could.

For the popup, I think we can install one driver for everycard. The problem is to have all the ATR to build the inf file. We could also offer the choice to:
- activate or not the minidriver read write mode
- use a inf file, use the OpenSC trick, disable the PnP mode, or do nothing
I can add a custom dialog to the installer if the minidriver has been selected before

**Comment by frankmorgner** [comment]
the other commits look good, too. Here are the updated comments:

- in `CardGetContainerInfo` you removed the check for `vs->p15card == NULL`. Does this introduce a potential problem?
- variable naming could be better, though things like `oh` have been present before.
- sometimes you have tabs and spaces mixed up, please use tabs only for indenting
- there is dead code commented out in `src/pkcs15init/pkcs15-lib.c` and `src/tools/pkcs15-tool.c` and `src/libopensc/pkcs15.h`

**Comment by vletoux** [comment]
@frankmorgner  I've fixed everything except about the tabs and spaces mixed up. Honestly, I've checked and I didn't find any lines I committed which is starting by spaces instead of tab.
Can you show me an example please ?

**Comment by frankmorgner** [comment]
Here some output of `git blame`:
```
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2395) 		 GetWindowRect(hwndParent, &rectParent);
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2396)          nX = ((rectParent.right - rectParent.left) - nWidth) / 2 + rectParent.left;
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2397)          nY = ((rectParent.bottom - rectParent.top) - nHeight) / 2 + rectParent.top;
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2398) 	 }
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2399) 	 else {
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2400) 		 nX = (nScreenWidth - nWidth) /2;
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2401) 		 nY = (nScreenHeight - nHeight) /2;
6127fe6b src/minidriver/minidriver.c (vletoux         2015-04-19 19:51:22 +0200 2402) 	 }
```
There are some other places (even from me :sweat:). I fixed it here https://github.com/frankmorgner/OpenSC/commit/0ca46910f7549f11a0dcb8c7e289d11f6e47047c

**Comment by vletoux** [comment]
@frankmorgner I've added your commit into my PR

I think that everything is ok for the PR for the write mode & ECC support.
Once this PR will be integrated, I'll work on the setup side in a new PR

**Comment by frankmorgner** [comment]
Thanks!

I won't have a Windows system available for some time.

I think @dengert and @CardContact have ECC cards available. Could one of you test this PR on your machines?

**Comment by dengert** [comment]
I have PIV, NEO and SmartCard-HSM.

But I do not have OpenSC installed or the development environment on my Windows 7.
I don't have access to AD or web services these days

Since Microsoft provided PIV driver there was no intention of installing OpenSC on Windows
while I was working, at lease not for applications that used the minidriver.

I could test the minidriver but only if the nightly builds or PR builds are available.

https://github.com/viktorTarasov where are the nightly builds?

Jenkins used to provide PR builds, but it looks like that is not working anymore.

There are a lot of people who could test on windows, if the PR builds where
available. Setting up the windows development environment is way to complicated for most.



On 10/16/2015 4:37 AM, Frank Morgner wrote:
> Thanks!
>
> I won't have a Windows system available for some time.
>
> I think @dengert <https://github.com/dengert> and @CardContact <https://github.com/CardContact> have ECC cards available. Could one of you test this PR on your machines?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-148667734>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
@dengert You can get the build associated to the PR (https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.15.0.257). Select a specific build, then at the right you have a tab named "artifacts" with the msi file

If you like, I can send to you my test program (source code and/or binary).
Not pretty but it does the good calls
test

Note: certutil does test the signature, not the DH

**Comment by dengert** [comment]
Yes, please send me the test program, both source and binary.

Thanks.

On 10/16/2015 12:28 PM, vletoux wrote:
> @dengert <https://github.com/dengert> You can get the build associated to the PR (https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.15.0.257). Select a specific build, then at the right
> you have a tab named "artifacts" with the msi file
>
> If you like, I can send to you my test program (source code and/or binary).
> Not pretty but it does the good calls
> test <https://cloud.githubusercontent.com/assets/10632326/10548545/de463a78-743b-11e5-871c-0f5b3c8554ab.png>
>
> Note: certutil does test the signature, not the DH
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-148778940>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
@dengert Have you got the test program ?
I saw that you didn't find the build artifact.
Do not hesitate to come back to me.

I waiting for the validation of my commits to work on the setup side

**Comment by dengert** [comment]
I got the program, and ran it with NIST demo card 4 that has 4 EC certificates and 1 RSA as a retired certificate.
The program cound see the 4 certiticates.

The issue with the VS 12 was the redistribution files, for VS 12.
It looks like I can get them at:

http://www.microsoft.com/en-us/download/details.aspx?id=40784

But I also read that the application should include the redistribution files.

The PIV may store certificate as zip files, so I don't think I can use the lite
version.  (The NEO has restrictions on the length of the certificate object, so zipped
certificates may be common.)


Been busy playing golf,this may be the last week with good weather :-)


On 10/20/2015 4:03 PM, vletoux wrote:
> @dengert <https://github.com/dengert> Have you got the test program ?
> I saw that you didn't find the build artifact.
> Do not hesitate to come back to me.
>
> I waiting for the validation of my commits to work on the setup side
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-149702403>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
@dengert  When you said "The program cound see the 4 certiticates." did you mean "could" or "couldn't"

If it couldn't, can you post the minidriver log file to my personal email please ?
Good golf ;-)

**Comment by dengert** [comment]
Sorry. It could. Here are  2 snipits from OpenSCMinidriversystemTest32.exe


General->System Driver Connect  (to use the Microsoft PIV driver. OpenSC is not installed.)


CryptoApiNG ->List container shows 7 certificates. Highlighting "Certificate for Digital Signature"

"Sign ECC" requests PIN, and popup says "The operation completed successfully"


"DH" using the "Certificate for Key Management"

"One or more of the supplied parameters could not be properly interpreted."

So the test program can not do DH using the Microsoft PIV driver.
Does the test program produce a log?

I had installed OpenSC but there were some dll issues, with using command line tools.
I went back to a restore point to make sure it OpenSC was uninstalled.
I will try again, which also requires registry changes as the Microsoft PIV driver has the ATR cached
and the ATR needs to be listed for OpenSC.




On 10/21/2015 4:27 AM, vletoux wrote:
> @dengert <https://github.com/dengert> When you said "The program cound see the 4 certiticates." did you mean "could" or "couldn't"
>
> If it couldn't, can you post the minidriver log file to my personal email please ?
> Good golf ;-)
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-149833965>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
The DH check fails at the end by design because I tested a DH with wrong parameters.
But before it is doing many DH which are verified. You ll get then a wrong data error message if the DH is incorrect.

The general tab does change the minidriver only on the 3 first tabs, not the capi or cng ones which use the Windows one.

No log since the program is designed to run under the visual studio debugger ;-(

**Comment by frankmorgner** [comment]
You could try debugview.exe if you dont have visual studio

Am 21. Oktober 2015 15:00:22 MESZ, schrieb vletoux <notifications@github.com>:
>The DH check fails at the end by design because I tested a DH with
>wrong parameters.
>But before it is doing many DH which are verified. You ll get then a
>wrong data error message if the DH is incorrect.
>
>The general tab does change the minidriver only on the 3 first tabs,
>not the capi or cng ones which use the Windows one.
>
>No log since the program is designed to run under the visual studio
>debugger ;-(
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenSC/OpenSC/pull/566#issuecomment-149887016

-- 
Frank Morgner

**Comment by vletoux** [comment]
@dengert Try "api monitor" from rohitab.com
By checking "cryptography", you'll be able to see all CAPI / CNG calls run from certutil / my_test_program with their parameters and results.

=> are there any other validation required before accepting the PR ?

it's new code, especially located in the minidriver, so the risk of adding it should be quite limited

**Comment by dengert** [comment]
I now have opensc from 556-2015-10-15 on W7 64 bit. (both 64 and 32 bit versions.)

It took a bit to turn off the Microsoft PIV driver in the registry so the OpenSC driver would be used.
With the OpenSC driver, the list container shows the "GUID" for the certificates. With the Microsoft PIV driver
a character string is shown instead.  (See the snipit I sent a few days ago.)

Running the test program 64bit the signECC works As expected the DH appears to work, as it did with the Microsoft driver.

Running the test program 32bit, appears to run the Microsoft PIV driver. Any idea why?

I still need to make sure there is no additional information in the cert store that could cause confusion.

I hope tomorrow to uses one of the debug tools to see what is going on.


On 10/21/2015 8:00 AM, vletoux wrote:
> The DH check fails at the end by design because I tested a DH with wrong parameters.
> But before it is doing many DH which are verified. You ll get then a wrong data error message if the DH is incorrect.
>
> The general tab does change the minidriver only on the 3 first tabs, not the capi or cng ones which use the Windows one.
>
> No log since the program is designed to run under the visual studio debugger ;-(
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-149887016>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
FYI You have a second Calais database on the wow registry node for 32 bits on 64 bits system

**Comment by dengert** [comment]
Running OpenSCMinidriverTest64.exe on W7 Pro 64bit with OpenSC from #566. Added
c:\tmp\md.log and opensc.conf with debug = 9; debug_file=c:\tmp\opensc-debug.log

The NIST test card #4 has a Key Management Key using P-256 curve.

The opensc-debug.log shows sc_pkcs15_derive with different data.

The format of the command and response are found in PIV 800-73-3 Part 2
A.4.2 Elliptic Curve Cryptography Diffie-Hellman

Looks like it worked!

3 different derive operations were done, with different data. This was the first.

2015-10-23 13:24:02.898 CardConstructDHAgreement
2015-10-23 13:24:02.913 check_reader_status
2015-10-23 13:24:02.944 pCardData->hSCardCtx:0x00000003 hScard:0x00000001
2015-10-23 13:24:02.944 [cardmod] sc.c:251:sc_detect_card_presence: called
2015-10-23 13:24:02.944 [cardmod] reader-pcsc.c:384:pcsc_detect_card_presence: called
2015-10-23 13:24:02.944 SCM Microsystems Inc. SCR35xx USB Smart Card Reader 0 check
2015-10-23 13:24:02.944 [cardmod] reader-pcsc.c:313:refresh_attributes: returning with: 0 (Success)
2015-10-23 13:24:02.944 [cardmod] reader-pcsc.c:389:pcsc_detect_card_presence: returning with: 5
2015-10-23 13:24:02.944 [cardmod] sc.c:256:sc_detect_card_presence: returning with: 5
2015-10-23 13:24:02.960 check_reader_status r=5 flags 0x00000005
2015-10-23 13:24:02.991 CardConstructDHAgreement dwVersion=2, dwKeySpec=2 pbData=000000000378DCB0, cbData=72
2015-10-23 13:24:02.991 [cardmod] pkcs15-sec.c:200:sc_pkcs15_derive: called
2015-10-23 13:24:02.991 [cardmod] pkcs15-sec.c:289:sc_pkcs15_derive: returning with: 0 (Success)
2015-10-23 13:24:03.007 sc_pkcs15_derive returned 0
2015-10-23 13:24:03.007 [cardmod] pkcs15-sec.c:200:sc_pkcs15_derive: called
2015-10-23 13:24:03.007 [cardmod] padding.c:283:sc_get_encoding_flags: called
2015-10-23 13:24:03.007 iFlags 0x0, card capabilities 0x30010
2015-10-23 13:24:03.007 pad flags 0x0, secure algorithm flags 0x10000
2015-10-23 13:24:03.007 [cardmod] padding.c:317:sc_get_encoding_flags: returning with: 0 (Success)
2015-10-23 13:24:03.022 [cardmod] card.c:394:sc_lock: called
2015-10-23 13:24:03.022 [cardmod] sec.c:68:sc_set_security_env: called
2015-10-23 13:24:03.022 [cardmod] card-piv.c:2214:piv_set_security_env: called
2015-10-23 13:24:03.022 flags=00000015 op=4 alg=2 algf=00010000 algr=00000100 kr0=9d, krfl=1
2015-10-23 13:24:03.022 [cardmod] card-piv.c:2245:piv_set_security_env: returning with: 0 (Success)
2015-10-23 13:24:03.022 [cardmod] sec.c:72:sc_set_security_env: returning with: 0 (Success)
2015-10-23 13:24:03.022 [cardmod] sec.c:40:sc_decipher: called
2015-10-23 13:24:03.022 [cardmod] card-piv.c:2410:piv_decipher: called
2015-10-23 13:24:03.022 [cardmod] card-piv.c:2274:piv_validate_general_authentication: called
2015-10-23 13:24:03.022 [cardmod] card-piv.c:447:piv_general_io: called
2015-10-23 13:24:03.038 87 11 9d 71 : 255 256
2015-10-23 13:24:03.038 [cardmod] card.c:394:sc_lock: called
2015-10-23 13:24:03.038 calling sc_transmit_apdu flags=1 le=256, resplen=4096, resp=000000000017C220
2015-10-23 13:24:03.038 [cardmod] apdu.c:563:sc_transmit_apdu: called
2015-10-23 13:24:03.038 [cardmod] card.c:394:sc_lock: called
2015-10-23 13:24:03.038 [cardmod] apdu.c:530:sc_transmit: called
2015-10-23 13:24:03.038 [cardmod] apdu.c:384:sc_single_transmit: called
2015-10-23 13:24:03.038 CLA:0, INS:87, P1:11, P2:9D, data(71) 000000000017D2E0
2015-10-23 13:24:03.038 reader 'SCM Microsystems Inc. SCR35xx USB Smart Card Reader 0'
2015-10-23 13:24:03.038
Outgoing APDU data [   77 bytes] =====================================
00 87 11 9D 47 7C 45 82 00 85 41 04 5E A2 7C B1 ....G|E...A.^.|.
48 DD EA 31 23 54 E2 84 F3 51 0F 7C 62 51 37 76 H..1#T...Q.|bQ7v
CB EE EF 4E 6D 0C 46 26 C4 A2 90 33 8A AE F6 26 ...Nm.F&...3...&
C3 AD 8D 37 70 8C 81 B4 FD E4 62 66 93 80 E8 8D ...7p.....bf....
81 3C 3A 84 63 8E 38 74 50 20 95 20 00          .<:.c.8tP . .
======================================================================
2015-10-23 13:24:03.038 [cardmod] reader-pcsc.c:190:pcsc_internal_transmit: called
2015-10-23 13:24:03.522
Incoming APDU data [   38 bytes] =====================================
7C 22 82 20 A1 66 7E 3D 4B DD 72 9A F8 3B 2B A0 |". .f~=K.r..;+.
47 B2 9F 76 55 0D 4B 58 32 1E 14 DA DE 0D 2D D1 G..vU.KX2.....-.
97 0B 18 47 90 00                               ...G..
======================================================================
2015-10-23 13:24:03.522 [cardmod] apdu.c:399:sc_single_transmit: returning with: 0 (Success)
2015-10-23 13:24:03.522 [cardmod] apdu.c:552:sc_transmit: returning with: 0 (Success)
2015-10-23 13:24:03.537 [cardmod] card.c:434:sc_unlock: called
2015-10-23 13:24:03.537 DEE r=0 apdu.resplen=36 sw1=90 sw2=00
2015-10-23 13:24:03.537 DEE got buffer 00000000037B9640 len 36
2015-10-23 13:24:03.537 [cardmod] card.c:434:sc_unlock: called
2015-10-23 13:24:03.553 [cardmod] card-piv.c:558:piv_general_io: returning with: 36
2015-10-23 13:24:03.553 [cardmod] card-piv.c:2327:piv_validate_general_authentication: returning with: 32
2015-10-23 13:24:03.553 [cardmod] card-piv.c:2412:piv_decipher: returning with: 32
2015-10-23 13:24:03.553 [cardmod] sec.c:44:sc_decipher: returning with: 32
2015-10-23 13:24:03.568 [cardmod] card.c:434:sc_unlock: called
2015-10-23 13:24:03.568 [cardmod] pkcs15-sec.c:289:sc_pkcs15_derive: returning with: 32
2015-10-23 13:24:03.584 sc_pkcs15_derive returned 32
2015-10-23 13:24:03.615
P:4940 T:2764 pCardData:00000000003EE0C0
2015-10-23 13:24:03.631 CardDeriveKey
2015-10-23 13:24:03.646
P:4940 T:2764 pCardData:00000000003EE0C0
2015-10-23 13:24:03.662 CardDeriveKey
2015-10-23 13:24:03.693
P:4940 T:2764 pCardData:00000000003EE0C0
2015-10-23 13:24:03.709 CardDestroyDHAgreement

On 10/23/2015 1:29 AM, vletoux wrote:
> FYI You have a second Calais database on the wow registry node for 32 bits on 64 bits system
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-150488302>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
A suggestion for the test program:

Implement the equivalent of:

openssl x509 -noout -in <certificate.of.other> -pubkey \
   | openssl ec -pubin -outform DER > $TMP.other.pubkey.der

pkcs11-tool -derive -m ECDH1-COFACTOR-DERIVE -d <id> -i  ECDH1-COFACTOR-DERIVE \
    -i $TMP.other.pubkey.der -O

This would allow two people with cards that have ECDH key to test DH between them.
Each needs access to the others certificate, which contains the public key.
The output of both people running the above should be the same shared secret.




-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
I can do every CAPI / CNG test program but CNG doesn't allow the export of the shared secret but only a derivate (not NCryptSecretAgreement but NCryptDeriveKey).

Personally the test program generated one public / private ECC key, compute the DH and derivate the key then compare the key computed the same way with the other public key.
I then used cmck.exe to test all variations.
Then I played with the AD smart card logon.

**Comment by vletoux** [comment]
Tried with an isoApplet card. The fix about the minidriver deauthentication bug break the compatibility with the card (the second pin authentication attempt failed because the card has been reseted).
=> cannot test anymore

**Comment by dengert** [comment]
Looks like Microsoft's supports :BCRYPT_KDF_SP80056A_CONCAT (L"SP800_56A_CONCAT")

Use the SP800-56A key derivation function.


This is well defined here: NIST 800-56A
5.8.1 Concatenation Key Derivation Function (Approved Alternative 1)

Looks like this could be added to pkcs11-tool


On 10/23/2015 3:12 PM, vletoux wrote:
> I can do every CAPI / CNG test program but CNG doesn't allow the export of the shared secret but only a derivate (not NCryptSecretAgreement but NCryptDeriveKey).

>
> Personally the test program generated one public / private ECC key, compute the DH and derivate the key then compare the key computed the same way with the other public key.
> I then used cmck.exe to test all variations.
> Then I played with the AD smart card logon.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-150678286>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
I didn't implement it in the minidriver because I couldn't find the algorithm specification, parameters and a way to test it.

**Comment by philipWendland** [comment]
Can I fix this somehow?
If the card is reset, the PIN will be de-authenticated. That sounds like 
normal behavior to me. Why does the second pin authentication attempt fail?

Thanks,
Philip

Am 10/23/2015 um 10:41 PM schrieb vletoux:

**Comment by dengert** [comment]
Its not important to add, as it is only a test.

What pkcs11-tool has is basicaly:
sp800-56A "5.7.1.2 Elliptic Curve Cryptography Cofactor Diffie-Hellman (ECC CDH) Primitive"
and the other party's public key is passed passed as the only data.
Both parties must be using the same curve.

The way to test it is two smartcards each with a ECC key. Using any of the methods should produce the same
results. One could be on Windows, they other on Linux.

On 10/23/2015 3:47 PM, vletoux wrote:
> I didn't implement it in the minidriver because I couldn't find the algorithm specification, parameters and a way to test it.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-150686252>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by vletoux** [comment]
It fails because the applet maybe be not loaded again ...

Le vendredi 23 octobre 2015, Philip Wendland <notifications@github.com> a
écrit :

> Can I fix this somehow?
> If the card is reset, the PIN will be de-authenticated. That sounds like
> normal behavior to me. Why does the second pin authentication attempt fail?
>
> Thanks,
> Philip
>
> Am 10/23/2015 um 10:41 PM schrieb vletoux:
> >
> > Tried with an isoApplet card. The fix about the minidriver
> > deauthentication bug break the compatibility with the card (the second
> > pin authentication attempt failed because the card has been reseted).
> > => cannot test anymore
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-150684153>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSC/OpenSC/pull/566#issuecomment-150695321>.
>


-- 
---
Vincent

**Comment by vletoux** [comment]
To summarize:
- tested on PIV card by @dengert  => OK
- tested on sc-hsm in relation with @CardContact => OK
- tested on isoApplet in relation with @philipWendland => Not OK
{the applet is not yet compatible with the minidriver because the applet reselection is missing after a deauthentication (reset)}
- tested on an OpenPGP card by me => OK (no regression for RSA card)
- tested on an Masktech card by me => OK (no regression for RSA card)
- Code review done by @frankmorgner 

=> can this pull request be accepted, please ?
(last commit was 8 days ago)

**Comment by frankmorgner** [comment]
thanks

**Pull request merged**
