### PR TITLE
Fix 1734

### PR DESCRIPTION
**Pull request by frankmorgner**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by popovec** [comment]
Ok, this fix the #1731 but  we still need #1734 to fix  errors in `sc_format_apdu_cse_lc_le()`.

**Comment by frankmorgner** [comment]
Thanks for the testing. I've added the limitations into the documentation of `sc_format_apdu_ex()`, which is the only place where `sc_format_apdu_cse_lc_le()` is called.

**Comment by dengert** [comment]
This PR may fix the specific  problem in #1731 , but IMHO `sc_format_apdu_ex` is only partially implemented. It looks like it will only work correctly with extended APDUs and it does not factor in data chaining and may have problems with T=0.  

This problem started when a developer assumed `sc_format_apdu_ex` could replace a lot of extra code and tried to use it with short APDUs.  I would like to use it too. 

If the intent of https://github.com/OpenSC/OpenSC/commit/27526de0219f42a666eaadf1e484ea96a9ba8db9 is to use `sc_format_apdu_ex` as a replacement for `sc_format_apdu`  everywhere then it needs to support T=0, T=1, data chaining, short APDUs and other things. Adding comments does not address the underlying problems introduced with `sc_format_apdu_ex` or help developers avoid the same problems. 

#1734 was only a partial fix. As I said in #1731 "Fix it however you want." But the problems still exist.

**Comment by metsma** [comment]
I confirm, this PR fixes EstEID 2018 card communication with T=0

**Pull request merged**
