### PR TITLE
gemsafeV1 ISO7816 PIN support and PTEID improvements (Supersedes #794)

### PR DESCRIPTION
**Pull request by nunojpg**

### CODE REVIEW

**Comment by frankmorgner** [comment]
Overall it looks better now.

Could you check the build error: https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.16.0.719/job/cjatbjbcij5ngw1c?

**Comment by nunojpg** [comment]
Hi, I've received some comments and I'll try to update the commits this weekend.

Not sure about the build failure, for now I'm blaming the build rig, if it fails again I'll take a look.

**Comment by l1k** [comment]
Is nunojpg/OpenSC@2ef3e2f3553ec6a84e07d12f0fafa20ca9a4e67f  the same as it was in #794? If so, feel free to add my
```
Tested-by: Lukas Wunner <lukas@wunner.de>
```

**Comment by frankmorgner** [comment]
@nunojpg did you find time to integrate the comments you got?

**Comment by nunojpg** [comment]
@frankmorgner It is still WIP, please give me more 1 week.

**Comment by frankmorgner** [comment]
ok, no problem

**Comment by nunojpg** [comment]
@l1k I've added your tested-by. Thanks.

The pkcs15-pteid changes are still pending testing and validation from 2 people. Please hold the merge.

**Comment by frankmorgner** [comment]
@nunojpg did you get all the feedback?

Could you resolve the conflict?

**Comment by nunojpg** [comment]
@frankmorgner hi, thanks. Conflict solved. Green light to merge.

**Pull request closed without merging**
