### PR TITLE
TrueCrypt/VeraCrypt support in OpenPGP

### PR DESCRIPTION
**Pull request by hongquan**
Hello

This is a redo work of #150. However, most of its commits, by my mistake, is already included in #303 and gets merged (It is tested and works well, though).

Here are some minor changes for the feature.

### CODE REVIEW

**Comment by frankmorgner** [comment]
your changes are not related to Truecrypt, as far as I can see... But they don't do any harm either. What's the current state of OpenPGP/OpenSC support in Truecrypt/Veracrypt?

**Comment by hongquan** [comment]
> your changes are not related to Truecrypt

The changes are related to OpenPGP's private DO, which is used for storing TrueCrypt's keyfile. Actually, this PR should say about OpenPGP "data" DO, but TrueCrypt is mentioned because I want to notify the OpenSC team that the TrueCrypt support has already gone to OpenSC and already work. This PR adds some minor improvements.

> What's the current state of OpenPGP/OpenSC support in Truecrypt/Veracrypt?

I can answer only for OpenPGP case in OpenSC (don't know about other cards). It basically works, but with some limitations due to OpenPGP's limit, as mentioned in https://github.com/OpenSC/OpenSC/pull/150#issue-12506015

**Comment by mouse07410** [comment]
I say again: making TrueCrypt/VeraCrypt use smart cards to unlock the volume is a very good idea. But the current design is broken: many smart cards (particularly those issued by organizations) do **not** allow write access by users.

On the other hand, **all** of those smart cards allow RSA or ECC key wrapping (a bit more difficult with ECC as in this case you cannot pre-generate the key, but still quite usable).

To fix this design flaw, you need to move away from trying to **write** your DO **to** the card, and instead **use** the card as it's supposed to be used, i.e., to encrypt the volume master key with the KEY MANagement key (for PIV) or Encryption subway (OpenPGP).

**Comment by hongquan** [comment]
> you need to move away from trying to write your DO to the card, and instead use the card as it's supposed to be used

I'm aware of this, but it is not the way TrueCrypt does. TrueCrypt uses PKCS#11 card to store keyfile (!), not to encrypt its key/data.

**Comment by mouse07410** [comment]
>> you need to move away from trying to write your DO to the card, and instead use the card as it's supposed to be used

> I'm aware of this, but it is not the way TrueCrypt does. TrueCrypt uses PKCS#11 card to store keyfile (!), not to encrypt its key/data.

In turn, I'm aware of what TrueCrypt does. But I'm trying to tell you that it's a silly way to use a smart card because (a) many smart cards will *not* allow write access, and (b) *all* the smart cards support key encryption in one way or the other.

"...it's not the way TrueCrypt does..." is not an acceptable excuse.

**Comment by hongquan** [comment]
> I'm trying to tell you that...
I'm totally agree with you about how smartcard should be used.
But I make this feature, not because I encourage to use smartcard for storing TrueCrypt keyfile. It is because some TrueCrypt user, who owns a OpenPGP card, wants to use his smartcard with TrueCrypt, and TrueCrypt also offers smartcard support. The problem is that he doesn't know that TrueCrypt doesn't support in correct way, and actually user doesn't need to care it.

**Comment by mouse07410** [comment]
Sorry for not making myself clear enough. The way "some TrueCrypt user" wants it to work is broken, and (more importantly) will *not* work for many users and many OpenPGP (and other) cards. If you decided to enable OpenPGP card support, the least you could do was to make it right - rather than following *literally* that one ignorant user's request and keeping this thing broken.

After all, TrueCrypt is open source, isn't it?

**Comment by frankmorgner** [comment]
@hongquan please look at https://github.com/OpenSC/OpenSC/pull/817/files, your PR does not contain any functional or logical change. Since you keep saying that those changes are related to Truecrypt, this makes me believe that you forgot to add some change...

**Comment by hongquan** [comment]
@frankmorgner I think you miss one my [comment](#issuecomment-230668019), or I couldn't make clear my idea (with my poor English).
> you forgot to add some change
Those changes, by my mistake, was included in #303 and got merged. But I still mention TrueCrypt in this PR, because at least I want to inform OpenSC team that the OpenSC-OpenPGP code already includes support for TrueCrypt. I don't want the code to have something hidden, unknown to the team.

**Comment by hongquan** [comment]
> After all, TrueCrypt is open source
Yes. Actually, TrueCrypt is discontinued. Its living fork is Veracrypt.

**Comment by frankmorgner** [comment]
@hongquan got it, thanks for the clearification.

**Pull request merged**
