### PR TITLE
Prep openssl 1.1.0 pre5

### PR DESCRIPTION
**Pull request by dengert**
Resubmit of #740 with rebase on to toward-opensc-0.16.0 which was renamed.  Minor change to card-oberthur.c  to resolve merge conflict. 

OpenSSL-1.1.0-pre5 now hides the RSA and DSA structures which require additional changes to OpenSC. Since the release of pre5 the RSA_set0_key has changed. This is not reflected in these changes:
 http://rt.openssl.org/Ticket/Display.html?id=4518

These changes are experimental and need testing, testing that I do not have the hardware to test.
They should not be included in 0.16.0. 

OpenSSL-1.1.0 may have another RC before a final release which will require additional changes.

As with #717 and #740 the changes are designed to allow OpenSC code to compile with OpenSSL versions 0.9.7, 0.9.7, 0.9.8, 1.0.1, 1.0.2 and 1.1.0-pre5

### CODE REVIEW

**Comment by dengert** [comment]
@viktorTarasov Why did you close this?

**Comment by viktorTarasov** [comment]
By mistake. I removed 'towards-0.16.0' branch. 
If it's not too difficult, renew this PR to actual 'master',
if not -- I will restore removed branch.

**Comment by dengert** [comment]
I will rebase on master and make changes as needed. Thanks.
      
    
    On 7/22/2016 10:41 AM, viktorTarasov
      wrote:
    
    
      By mistake. I removed 'towards-0.16.0' branch. 
        If it's not too difficult, renew this PR to actual 'master',
        if not -- I will restore removed branch.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
OpenSSL announced the 1.1.0 pre release 6 today. I will be updating and rebaseing this PR late next week to use the the new OpenSSL release.  (I can not do it this week.)

**Pull request closed without merging**
