### PR TITLE
sc-hsm: add support for `opensc-tool --serial`

### PR DESCRIPTION
**Pull request by frankmorgner**
fixes https://github.com/OpenSC/OpenSC/issues/2648

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by Jakuje** [comment]
What is the significance of the change to `MacOSX/OpenSC_binaries.entitlements`? The rest looks good, but please, squash it into single commit to avoid fixup commits.

**Comment by frankmorgner** [comment]
that were accidental changes related to some other issue (removed now)

**Comment by Jakuje** [comment]
> that were accidental changes related to some other issue (removed now)

thanks. Please, squash the commits and then we are good to go.

**Comment by frankmorgner** [comment]
done using the github merge UI

**Pull request merged**
