### PR TITLE
pkcs11-tool: Simplify PIN warnings messages logic

### PR DESCRIPTION
**Pull request by nunojpg**
Signed-off-by: Nuno Goncalves <nunojpg@gmail.com>

### CODE REVIEW

**Comment by nunojpg** [comment]
@viktorTarasov In response to #819, please check if this is what you prefer.

Thanks!

**Comment by viktorTarasov** [comment]
Look if will agree with this 1198197586cbfdd800d46301ff74799460944dde .

**Comment by nunojpg** [comment]
@viktorTarasov I don't understood what you mean...

**Comment by viktorTarasov** [comment]
> I don't understood what you mean...

never mind, sorry for the noise.

applied in 6ad229e9f6ebff1756bb6d0592c9a6f539e0fd7f,
thanks.

**Pull request closed without merging**
