### PR TITLE
Use struct sm_cwa_session from sm.h in dnie

### PR DESCRIPTION
**Pull request by rickyepoderi**
Finally I think this is complete and I tested it with both types of DNIe. This is the fix for issue #930. Remember that besides of replacement the structures it also removes the _sc_reset_ from the DNIe.

Please @germanblanco take a look of the changes before committing if you have the time.

### CODE REVIEW

**Comment by frankmorgner** [comment]
Please check with `valgrind` if there are any problems with the memory handling.

**Comment by rickyepoderi** [comment]
This is the result for a login. All the changes are inside the secure channel creation, so I think that with a simple login is more than enough:

```
$ valgrind --leak-check=yes ./pkcs11-tool -l -I
==3572== Memcheck, a memory error detector
==3572== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==3572== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==3572== Command: ./pkcs11-tool -l -I
==3572== 
Cryptoki version 2.20
Manufacturer     OpenSC Project
Library          OpenSC smartcard framework (ver 0.16)
Using slot 0 with a present token (0x0)
Logging in to "PIN1 (DNI electrónico)".
Please enter User PIN: 
==3572== Source and destination overlap in mempcpy(0x564fbe0, 0x564fbe0, 21)
==3572==    at 0x4C32113: __GI_mempcpy (vg_replace_strmem.c:1518)
==3572==    by 0x5AEAC0D: _IO_default_xsputn (genops.c:438)
==3572==    by 0x5ABEBDA: vfprintf (vfprintf.c:1637)
==3572==    by 0x5ADFACA: vsprintf (iovsprintf.c:42)
==3572==    by 0x5AC5326: sprintf (sprintf.c:32)
==3572==    by 0x5361C53: cwa_hexdump (cwa14890.c:87)
==3572==    by 0x5363DD9: cwa_trace_apdu (cwa14890.c:121)
==3572==    by 0x5363DD9: cwa_encode_apdu (cwa14890.c:1465)
==3572==    by 0x53608B6: dnie_sm_get_wrapped_apdu (card-dnie.c:801)
==3572==    by 0x5389C5B: sc_sm_single_transmit (sm.c:139)
==3572==    by 0x52CA70E: sc_transmit (apdu.c:519)
==3572==    by 0x52CB382: sc_transmit_apdu (apdu.c:628)
==3572==    by 0x5366028: dnie_transmit_apdu (cwa-dnie.c:905)
==3572== 
==3572== 
==3572== HEAP SUMMARY:
==3572==     in use at exit: 34,233 bytes in 952 blocks
==3572==   total heap usage: 6,838 allocs, 5,886 frees, 978,032 bytes allocated
==3572== 
==3572== 112 (40 direct, 72 indirect) bytes in 1 blocks are definitely lost in loss record 621 of 656
==3572==    at 0x4C2ABAF: malloc (vg_replace_malloc.c:299)
==3572==    by 0x6664DE5: ???
==3572==    by 0x6664537: ???
==3572==    by 0x52E81CC: pcsc_detect_readers (reader-pcsc.c:1198)
==3572==    by 0x52B910F: sc_ctx_detect_readers (ctx.c:695)
==3572==    by 0x52B9BD2: sc_context_create (ctx.c:826)
==3572==    by 0x643902B: ???
==3572==    by 0x10DDD6: main (pkcs11-tool.c:764)
==3572== 
==3572== LEAK SUMMARY:
==3572==    definitely lost: 40 bytes in 1 blocks
==3572==    indirectly lost: 72 bytes in 3 blocks
==3572==      possibly lost: 0 bytes in 0 blocks
==3572==    still reachable: 34,121 bytes in 948 blocks
==3572==         suppressed: 0 bytes in 0 blocks
==3572== Reachable blocks (those to which a pointer was found) are not shown.
==3572== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==3572== 
==3572== For counts of detected and suppressed errors, rerun with: -v
==3572== ERROR SUMMARY: 5719 errors from 2 contexts (suppressed: 0 from 0)
```

There aren't new warnings related to the changes (it's logical cos I'm just re-using sm structs which are already there, I'm substituting allocated arrays with already created structures).

The only issue related to dnie is in _cwa_hexdump_ which is there since the beginning. I think that @germanblanco already told me about this issue long ago. If you want I can look to this issue later on, but it seems a warning more than a real problem.

**Comment by germanblanco** [comment]
Hola Ricardo,

si, el error del valgrind es el que hablamos hace tiempo.
Lo he estado probando y me falla la firma :-(
Ahora que no te se decir si sera cosa de mi DNI o de la aplicacion o de
que. me ha fallado con dos aplicaciones distintas, una el programa para
presentar el modelo 390 de la AEAT y otra con el "Afirma". Lo has probado
tu?

Un saludo,

/German

**Comment by rickyepoderi** [comment]
@germanblanco I have just realized that you answered to the pull request comment instead of sending a mail directly to me. It is always nice seeing some Spanish in github, but dude, you need to relax and work less. :smile: 

As I told you directly in the mail this change is only related to the secure channel creation (deletion on the _sc_reset_ and use of _sm.h_ structs).  I have not modified nothing about the signature. Right now I only test the changes with my tester (that's why I did it, it is super-fast and I think it covers all the cases).

In spite of all that, this week I tried to test it with _autofirma_ (the new application provided by the government) but I realized that they have re-invented the wheel again and it seems to not use any pkcs#11 library. So any failure of that application is (I am not completely sure but quite confident) not related to opensc. Then I tried with the previous java signature applet (the internet test page has disappeared but I downloaded a copy and I can test it locally) and it works ok. (First it did not work but the reason was that the applet found the system pkcs#11 library. In my debian the version is 0.16 which still does not support DNIe 3.0. As soon I removed the system package the applet found the compiled library and it worked like a charm.)

**Comment by frankmorgner** [comment]
Thanks!

Please continue the cleanup by consequently using `get_sm_apdu` and `free_sm_apdu` including memory management (see discussion in https://github.com/OpenSC/OpenSC/pull/655).

**Comment by frankmorgner** [comment]
See also https://github.com/OpenSC/OpenSC/issues/930#issuecomment-272559484 for using the SM framework

**Pull request merged**
