### PR TITLE
Migrate some tests to Github Actions

### LINKED ISSUE #2361: Migrate travis-ci to generic scripts and run in Github Actions
### Problem Description

The free travis-ci is gone and the new one requires OSS projects to request OSS credits every time they run out (or pay your own):

https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

### Proposed Resolution

I am not very happy with this business model so I would suggest to rewrite the CI to github-ci, which is now free and we hope it will stay for some time.

At this moment, the CI is long spaghetti yaml file with a lot of conditions to satisfy several runs. We should break it to several runs, probably collect the commands to separate scripts and share what is common (probably with functions or running other scripts) executing the same tasks we used to have on travis-ci

Status after merging #2362:
 * [x] OSX
   * [X] Setup
   * [X] Build
   * [x] Package signing
 * [X] Linux (Ubuntu 20)
   * [X] Setup
   * [X] Build
   * [X] clang-tidy
 * [ ] Other Linux (or Ubuntu version)
   * [X] Ubuntu 18
   * [ ] Other (would require containers with some limitations)?
 * [ ] Windows
   * [X] wine/mingw
   * [ ] Real windows?
 * [X] Tests
   * [X] virt_cacard (CAC)
   * [X] OSEiD (myeid)
   * [X] Java Card simulation
     * [X]  PIV
     * [X] IsoApplet
     * [X] GidsApplet
     * [X] OpenPGP
 * [ ] Refactor github-only stuff from the shell scripts
 * [x] Remove the .travis.yml
 * [x] Integrate Coverity Scan

### PR DESCRIPTION
**Pull request by Jakuje**
Partially resolves #2361.

What is and is not in:
 * [ ] OSX
   * [X] Setup
   * [X] Build
   * [ ] Package signing
 * [X] Linux (Ubuntu 20)
   * [X] Setup
   * [X] Build
   * [X] clang-tidy
 * [ ] Other Linux (or Ubuntu version)
   * [X] Ubuntu 18
   * [ ] Other?
 * [ ] Windows
   * [X] wine/mingw
   * [ ] Real windows?
 * [X] Tests
   * [X] virt_cacard (CAC)
   * [X] OSEiD (myeid)
   * [X] Java Card simulation
     * [X]  PIV
     * [X] IsoApplet
     * [X] GidsApplet
     * [X] OpenPGP

It is going to require some more work. I tried to refactor the spaghetti yaml to some sensible scripts so we are less dependent on the actual CI engine

### CODE REVIEW

**Comment by Jakuje** [comment]
The CI is not triggered by this PR, because it does not change any .c or .h files in the repository. But it is invoked on push here:

* https://github.com/Jakuje/OpenSC/actions/runs/989347541
* https://github.com/Jakuje/OpenSC/actions/runs/989347539

**Comment by Jakuje** [comment]
I added the Javacard tests today. Again they are not executed as no source code was changed in this PR, but they run in my fork:
 * https://github.com/Jakuje/OpenSC/actions/runs/1012911646 [linux]
 * https://github.com/Jakuje/OpenSC/actions/runs/1012911648 [osx]

**Comment by Jakuje** [comment]
@OpenSC/maintainers can you check if something like is good enough replacement for travis so we can merge it and use it for testing new PRs against?

**Comment by LudovicRousseau** [comment]
No objection to use github actions. Thanks for your work on it.

**Pull request merged**
