### PR TITLE
fixed location of vcvarsall.bat

### PR DESCRIPTION
**Pull request by frankmorgner**
*DO NOT MERGE*

work in progress

### CODE REVIEW

**Comment by frankmorgner** [comment]
@LudovicRousseau I'm still trying to set up a working configuration for appveyor. I called for your help becaus I thought you had a little more experience in this than me...

However, as I can see, now that appveyor.yml is present at least ci works and is tested for all PRs. This will help for further refinements...

**Comment by LudovicRousseau** [comment]
@frankmorgner I have no experience with Windows or Windows tools :-)

**Comment by frankmorgner** [comment]
I have set up the CI environment as described in http://permalink.gmane.org/gmane.comp.encryption.opensc.devel/14802 and https://github.com/OpenSC/OpenSC/wiki/Automated-OpenSC-builds#windows. However, during compilation I get an error:
`NMAKE : fatal error U1073: don't know how to make '..\libopensc\opensc.lib'`
See https://ci.appveyor.com/project/LudovicRousseau/opensc/build/1.0.32/job/cp69mh7vxc683so8.

@martinpaljak @viktorTarasov do you know how to solve this dependency?

**Comment by martinpaljak** [comment]
Oh great. Isn't there a "rebuild" button in appveyor ?

**Comment by frankmorgner** [comment]
Yes, there is but it can only be seen by @LudovicRousseau since he is the owner of the AppVeyor account. We should try to figure out if we can move this to an OpenSC-group account in AppVeyor

**Comment by frankmorgner** [comment]
@martinpaljak it turns out that we could apply for an OpenSC account http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations. I don't think that's a clever idea because this account only has one password that must then be propagated to all maintainers...

**Comment by frankmorgner** [comment]
you can, however, set up AppVoyer with your personal remote of OpenSC. This allows *you* to verify your build before making a PR.

**Comment by LudovicRousseau** [comment]
I think any body can create an account and build OpenSC using AppVeyor.
The only remaining problem is that https://github.com/OpenSC/OpenSC/blob/master/README.md can/should contain only one AppVeyor link. I used my AppVeyor account but feel free to change it.

**Pull request merged**
