### PR TITLE
Fix OS X installation

### PR DESCRIPTION
**Pull request by frankmorgner**
Fixes the OS X problems mentioned in #688 

I still need to verify the patches on a mac...

### CODE REVIEW

**Comment by frankmorgner** [comment]
[OpenSC-0.16.0rc2.dmg.zip](https://github.com/OpenSC/OpenSC/files/270710/OpenSC-0.16.0rc2.dmg.zip)
Verified that everything works as expected

**Comment by frankmorgner** [comment]
Verified that everything works as expected including finding the opensc pkcs11 module.
[OpenSC-0.16.0rc2.dmg.zip](https://github.com/OpenSC/OpenSC/files/272233/OpenSC-0.16.0rc2.dmg.zip)

**Comment by pyther** [comment]
Installed the binary, everything appears to work. Thanks!

**Comment by frankmorgner** [comment]
rewrote with my new email address and integrated #763

**Pull request merged**
