### PR TITLE
PIV: split up card matching from initializing

### PR DESCRIPTION
**Pull request by frankmorgner**
- Separate detection of card type from card initialization; extract
initialization of the private data from `piv_match_card_continued()`
into `piv_init_priv()`
- Clearify lock handling; the card is unlocked in the function where it
is locked to avoid responsibility passing
- `piv_activate()` makes sure that the PIV applet is selected during
card matching and initialization.

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [x] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Review by Jakuje — APPROVED** [review]

**Comment by dengert** [comment]
@frankmorgner @Jakuje  You do realize that #2053 has major changes in this same area, and I have started to address the your comments starting at  https://github.com/OpenSC/OpenSC/pull/2053#issuecomment-964943760 unless this is a bug that you are trying to fix having both of us trying to change the same code is making it harder not easier for both of us. 

I would like to ask that you look at the #2053 changes  in this area before committing this change to master.

**Comment by frankmorgner** [comment]
we can wait until we've finalized #2053

**Comment by frankmorgner** [comment]
I'll open a unified draft PR with all simplifications.

**Comment by Jakuje** [comment]
Right. But its always easier to review smaller and self-contained changes than this large diff. I wanted to clean up the backlog of approved changes before getting to this. I will try to have a look to the #2053 now.

**Pull request closed without merging**
