### PR TITLE
Fix CAC-introduced bug that broke access to certificates

### PR DESCRIPTION
**Pull request by mouse07410**
Thanks to @dengert for finding this problem.

Please review and (hopefully) merge soon.

### CODE REVIEW

**Comment by mouse07410** [comment]
(Hopefully) fixes #1030 .

**Comment by frankmorgner** [comment]
In https://github.com/OpenSC/OpenSC/issues/1030#issuecomment-295517198 you stated that the change in question fixes your missing key usage flag, is that correct?

Since I missed it the first time, I need to look closer at the ASN.1 structure definition... @Jakuje, what do you think?

**Comment by frankmorgner** [comment]
Quoted from [RFC 5912](https://tools.ietf.org/html/rfc5912):
```
CertExtensions EXTENSION ::= {
           ext-AuthorityKeyIdentifier | ext-SubjectKeyIdentifier |
           ext-KeyUsage | ext-PrivateKeyUsagePeriod |
           ext-CertificatePolicies | ext-PolicyMappings |
           ext-SubjectAltName | ext-IssuerAltName |
           ext-SubjectDirectoryAttributes |
           ext-BasicConstraints | ext-NameConstraints |
           ext-PolicyConstraints | ext-ExtKeyUsage |
           ext-CRLDistributionPoints | ext-InhibitAnyPolicy |
           ext-FreshestCRL | ext-AuthorityInfoAccess |
           ext-SubjectInfoAccessSyntax, ... }

ext-KeyUsage EXTENSION ::= { SYNTAX
       KeyUsage IDENTIFIED BY id-ce-keyUsage }
id-ce-keyUsage OBJECT IDENTIFIER ::=  { id-ce 15 }

KeyUsage ::= BIT STRING {
        digitalSignature        (0),
        nonRepudiation          (1), --  recent editions of X.509 have
                                     --  renamed this bit to
                                     --  contentCommitment
        keyEncipherment         (2),
        dataEncipherment        (3),
        keyAgreement            (4),
        keyCertSign             (5),
        cRLSign                 (6),
        encipherOnly            (7),
        decipherOnly            (8)
    }
```
A `BIT STRING` has tag `3`, which is what @mouse07410 suggests. Instead, tag `128` means *context-specific* encoding, which also makes some sense, but - strictly speaking - violates the RFC's definition. Is there some other definition that requires us to accept both tag `3` *and* tag `128` in the generic code?

If not, I suggest a local workaround within the CAC PKCS#15 emulator.

**Comment by Jakuje** [comment]
Hello. Looking through the commit message in f9a70cc8 I see:

 * Update bit order of returned bitstring extension (do not invert)

so it was changed intentionally (though I don't remember why the inversion was problem - bad card?). Comparing the results before (with commit 777e2a3) and after this PR applied I do not see any difference in output of `pkcs11-tool -O` for none of the standard PIV Test cards, CAC cards or `libcacard`.

As @dengert wrote, it is most probably wrong so I am ok with this change.

**Comment by dengert** [comment]
Sounds like @Jakuje, @frankmorgner, @mouse07410  and @dengert are all OK with the one line change.

**Comment by mouse07410** [comment]
> In #1030 (comment) you stated that the change in question fixes your missing key usage flag, is that correct?

Correct. 

EC *public* key still shows "Usage: none", which strictly speaking is incorrect (it should be "Usage: derive") - but it does not seem to prevent OpenSSL/libp11/pkcs11-tool from correctly using that public key. I tested it. And EC *private* key now shows the correct "Usage: derive". Usage for RSA keys is all correct/perfect.

**Comment by mouse07410** [comment]
@frankmorgner it seems that in `MacOSX/build-package.in` line 10
```
test -x ./configure || ./bootstrap
```
tramps over lines 43-51
```
if ! test -e ${BUILDPATH}/target/$PREFIX/lib/pkgconfig; then
        ./configure --prefix=$PREFIX \
                --sysconfdir=$PREFIX/etc \
                --disable-dependency-tracking \
                --enable-shared \
                --disable-static \
                --enable-strict \
                --disable-assert \
                --enable-sm # TODO: remove this (must be sensible default in master)
```
because directory `${PWD}/target/Library/OpenSC/lib/pkgconfig` exists (so that second `./configure --prefix=...` does not get executed.

I've observed that `make install` puts things to `/usr/local` regardless of `./configure --prefix=/Library/OpenSC`.

That would explain why some stuff is not updated in `/Library/OpenSC`.

Comments are welcome.

**Comment by dengert** [comment]
With regard to EC key pubkey keyUsage having none, I don't see why. Copuld the problem be in how pkcs11-tool displays it? @mouse07410 Can you get a spy trace and see if a C_GetAttribute of the public key asks for CKA_DERIVE, and what is returned?

Since in ECDH, the public key of the peer is passed as a parameter (and only as a "Big Integer") to  the derive  operation using the private key, C_Derive never sees any attributes of the public key, and that maybe why is works. Only programs like pkcs11-tool are looking at the public key and the key usage bits from the matching certificate.

**Comment by mouse07410** [comment]
> Could the problem be in how pkcs11-tool displays it?

Probably not.

> Can you get a spy trace and see if a `C_GetAttribute` of the public key asks for `CKA_DERIVE`, and what is returned?

Certainly. Here's the SPY: [yubi4-spy-dump.txt](https://github.com/OpenSC/OpenSC/files/945234/yubi4-spy-dump.txt)
Here's the screen output:
```
. . . . .
Private Key Object; EC
  label:      KEY MAN key
  ID:         03
  Usage:      derive
Public Key Object; EC  EC_POINT 384 bits
  EC_POINT:   0461xxxxxx
  EC_PARAMS:  0605xxxxxx
  label:      KEY MAN pubkey
  ID:         03
  Usage:      none
. . . . .
```

From what I see, it does *not* ask for `CKA_DERIVE`, which is why it is never returned. In fact, I do not see the code asking for `CKA_DERIVE` for *any* *public* keys. Could that be the problem?
```
. . . . .
97: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_CLASS             00007fff5f6072d0 / 8
[out] pTemplate[1]: 
    CKA_CLASS             CKO_PUBLIC_KEY       
Returned:  0 CKR_OK

98: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_KEY_TYPE          00007fff5f6072d0 / 8
[out] pTemplate[1]: 
    CKA_KEY_TYPE          CKK_EC             
Returned:  0 CKR_OK

99: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_CLASS             00007fff5f6072d0 / 8
[out] pTemplate[1]: 
    CKA_CLASS             CKO_PUBLIC_KEY       
Returned:  0 CKR_OK

100: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_EC_POINT          0000000000000000 / 0
[out] pTemplate[1]: 
    CKA_EC_POINT          0000000000000000 / 99
Returned:  0 CKR_OK

101: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_EC_POINT          00007fe651709120 / 99
[out] pTemplate[1]: 
    CKA_EC_POINT          00007fe651709120 / 99
    00000000  04 61 . . . . .
    . . . . .           
Returned:  0 CKR_OK

102: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_ECDSA_PARAMS      0000000000000000 / 0
[out] pTemplate[1]: 
    CKA_ECDSA_PARAMS      0000000000000000 / 7
Returned:  0 CKR_OK

103: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_ECDSA_PARAMS      00007fe651708b20 / 7
[out] pTemplate[1]: 
    CKA_ECDSA_PARAMS      00007fe651708b20 / 7
    00000000  06 05 2B 81 04 00 22                             ..+..."         
Returned:  0 CKR_OK

104: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_LABEL             0000000000000000 / 0
[out] pTemplate[1]: 
    CKA_LABEL             0000000000000000 / 14
Returned:  0 CKR_OK

105: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_LABEL             00007fe651708b20 / 14
[out] pTemplate[1]: 
    CKA_LABEL             00007fe651708b20 / 14
    4B455920 4D414E20 7075626B 6579
     K E Y .  M A N .  p u b k  e y
Returned:  0 CKR_OK

106: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_ID                0000000000000000 / 0
[out] pTemplate[1]: 
    CKA_ID                0000000000000000 / 1
Returned:  0 CKR_OK

107: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_ID                00007fe651708b20 / 1
[out] pTemplate[1]: 
    CKA_ID                00007fe651708b20 / 1
    00000000  03                                               .               
Returned:  0 CKR_OK

108: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_ENCRYPT           00007fff5f6072d0 / 1
[out] pTemplate[1]: 
    CKA_ENCRYPT           False
Returned:  0 CKR_OK

109: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_VERIFY            00007fff5f6072d0 / 1
[out] pTemplate[1]: 
    CKA_VERIFY            False
Returned:  0 CKR_OK

110: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe6517063e0
[in] pTemplate[1]: 
    CKA_WRAP              00007fff5f6072d0 / 1
[out] pTemplate[1]: 
    CKA_WRAP              False
Returned:  0 CKR_OK

111: C_FindObjects
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] ulMaxObjectCount = 0x1
[out] ulObjectCount = 0x1
Object 0x7fe651706d10 matches
Returned:  0 CKR_OK

112: C_GetAttributeValue
2017-04-20 15:05:35.149
[in] hSession = 0x7fe651403060
[in] hObject = 0x7fe651706d10
[in] pTemplate[1]: 
    CKA_CLASS             00007fff5f6072d0 / 8
[out] pTemplate[1]: 
    CKA_CLASS             CKO_CERTIFICATE      
Returned:  0 CKR_OK
. . . . .
```

**Comment by dengert** [comment]
pkcs11-tool.c in show_key() line: 3360
         `if ((!pub || sec) && getDERIVE(sess, obj)) {`

This says if not a public key or secret key check for CKA_DERIVE == TRUE
it should be:
` if (getDERIVE(sess, obj)) {`
because PKCS#11 says all keys have a CKA_DERIVE attribute.

**Comment by dengert** [comment]
@Jakuje you had said the use of the  SC_ASN1_BIT_STRING_NI may have been added to get around some problem, or it was a bad card.  

But also see that in the ./pkcs15-cac.c usage is not initialized, and is never reset when reading multiple certitficates. I don't think sc_pkcs15_get_bitstring_extension clears it out. (I could be wrong.)

**Comment by mouse07410** [comment]
@dengert thanks - see #1033 .

Guys, can I ask to speed up the review on this pair of one-line changes? Especially #1032 (this one), as it is crucial for functionality on Mac.

**Comment by frankmorgner** [comment]
Patience, @mouse07410. Integration can be speeded up by adding reviews.

**Comment by mouse07410** [comment]
Thank you!

**Comment by Jakuje** [comment]
FYI I found the card which made me to change this. It was obviously in CI. In `pcsc_scan` it says:

	Republic Slovenia e-Gov, Ministry of Public Administration
	SIGOV-CA, Slovenian Governmental Certification Authority

and is identified as a CAC II card and with this commit I am getting SIGN+VERIFY usage flags in the Encryption key, instead of ENCRYPT/DECRYPT.

The related part of decoding extensions for signature keys:

```
asn1.c:1267:asn1_decode_entry: decoding 'bitString', raw data:06C0
pkcs15-cac.c:401:sc_pkcs15emu_cac_init: cert 0002: cert_usage=0x3, pub_usage=0xc0 priv_usage=0xc
pkcs15-cac.c:410:sc_pkcs15emu_cac_init: adding rsa public key r=0 usage=c0
pkcs15-cac.c:414:sc_pkcs15emu_cac_init: adding rsa private key r=0 usage=c
```

The related part of decoding extensions for encryption key looks correct:

```
asn1.c:1267:asn1_decode_entry: decoding 'bitString', raw data:0520
pkcs15-cac.c:401:sc_pkcs15emu_cac_init: cert 0003: cert_usage=0x4, pub_usage=0xc0 priv_usage=0xc
pkcs15-cac.c:410:sc_pkcs15emu_cac_init: adding rsa public key r=0 usage=c0
pkcs15-cac.c:414:sc_pkcs15emu_cac_init: adding rsa private key r=0 usage=c
```
Problem is in the CAC driver, that I rewrote the old constants to the `SC_PKCS15INIT_X509_*`  defined in `pkcs15-init.h`, which are "inverted". The PIV driver is hardcoding the magic numbers correctly so it works just fine. We should merge also this mapping to some common code.

I will fill a new pull request resolving this issue in the CAC driver.

**Pull request merged**
