### PR TITLE
Implementation of card_ctl function with SC_CARDCTL_GET_SERIALNR

### PR DESCRIPTION
**Pull request by resoli**
Implementation of card_ctl function with SC_CARDCTL_GET_SERIALNR

### CODE REVIEW

**Comment by sschutte** [comment]
I would be happy to do some more testing for the new releases, however I can only use the Italian CNS since I dont have any other cards to test with. If there would be a way to get a hold of some more smart cards I would be happy to help.

Regarding testing, I came across something odd with Windows 8.1 64 bit. While l can authenticate with the card, I cannot change the PIN using the opensc tools. I have tested with opensc 0.14 and opensc 0.15. Both the 64 bit and 32 bit versions of Opensc are installed. I tried changing the pin using both the 32 bit versions and 64 bit versions of ```pkcs15-tool.exe```

Running ```pkcs15-tool.exe --change-pin``` results in ```Pin code change failed: Transmit failed```

Under Linux I can change the PIN just fine:

```Linux  3.19.3-200.fc21.x86_64 #1 SMP Thu Mar 26 21:39:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

``` opensc-0.14.0-2.fc21.x86_64 ```

Here is the debug log file from Windows 8.1 

https://gist.github.com/sschutte/2e64be1f7bdfe6e2bce6

**Comment by dengert** [comment]
Line 1572:

2015-04-20 15:51:48.395 [pkcs15-tool] reader-pcsc.c:182:pcsc_internal_transmit: called
2015-04-20 15:51:48.395 ACS CCID USB Reader 0:SCardTransmit/Control failed: 0x80100068

https://msdn.microsoft.com/en-us/library/windows/desktop/aa374738(v=vs.85).aspx#smart_card_return_values
says  0x80100068 SCARD_W_RESET_CARD The smart card was reset.

But the previous command to the card at line 1547 worked.
So the problem could be in windows.



On 4/21/2015 6:33 AM, Shaun Schutte wrote:
> I would be happy to do some more testing for the new releases, however I can only use the Italian CNS since I dont have any other cards to test with. If there would be a way to get a hold of some more
> smart cards I would be happy to help.
>
> Regarding testing, I came across something odd with Windows 8.1 64 bit. While l can authenticate with the card, I cannot change the PIN using the opensc tools. I have tested with opensc 0.14 and
> opensc 0.15. Both the 64 bit and 32 bit versions of Opensc are installed. I tried changing the pin using both the 32 bit versions and 64 bit versions of |pkcs15-tool.exe|
>
> Running |pkcs15-tool.exe --change-pin| results in |Pin code change failed: Transmit failed|
>
> Under Linux I can change the PIN just fine:
>
> |Linux 3.19.3-200.fc21.x86_64 #1 SMP Thu Mar 26 21:39:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux|
>
> |opensc-0.14.0-2.fc21.x86_64|
>
> Here is the debug log file from Windows 8.1
>
> https://gist.github.com/sschutte/2e64be1f7bdfe6e2bce6
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/321#issuecomment-94755797>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by sschutte** [comment]
Thanks for the reponse @dengert. Seems as though someone else is also having a similar error code althought using a different command.

http://comments.gmane.org/gmane.comp.encryption.opensc.devel/15352

Would you prefer if I sent this to the developer mailing list or creating a bug report?

**Comment by dengert** [comment]
This sounds like  issues that https://github.com/OpenSC/OpenSC/issues/434 and https://github.com/OpenSC/OpenSC/issues/439
are trying to address. i.e. what is Windows trying to do, and how to keep other processes from
accessing a unlocked verified card and misusing it or resetting it.

On 4/21/2015 8:23 AM, Shaun Schutte wrote:
> Thanks for the reponse @dengert <https://github.com/dengert>. Seems as though someone else is also having a similar error code althought using a different command.
>
> http://comments.gmane.org/gmane.comp.encryption.opensc.devel/15352
>
> Would you prefer if I sent this to the developer mailing list or creating a bug report?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/321#issuecomment-94792704>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by sschutte** [comment]
I see that https://github.com/OpenSC/OpenSC/issues/434 has been closed. Is there any builds from the Jenkins server that I can test to see if the problem has now been resolved under Windows 8.1?

**Comment by dengert** [comment]
On 4/30/2015 3:37 AM, Shaun Schutte wrote:
> I see that #434 <https://github.com/OpenSC/OpenSC/issues/434> has been closed. Is there any builds from the Jenkins server that I can test to see if the problem has now been resolved under Windows 8.1?
>
See:

https://opensc.fr/jenkins/view/OpenSC-master/job/OpenSC-master/
https://opensc.fr/jenkins/view/OpenSC-master/job/OpenSC-master-Win32/
https://opensc.fr/jenkins/view/OpenSC-master/job/OpenSC-master-Win64/

look for the msi files.


> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/321#issuecomment-97707661>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by viktorTarasov** [comment]
as well as
https://sourceforge.net/projects/opensc/files/OpenSC/nightly/

**Comment by sschutte** [comment]
Some feedback from my side while testing nightly builds, changing the PIN of the card is still failing. 
Running ```pkcs15-tool.exe --change-pin``` results in ```Pin code change failed: Transmit failed```

I am testing under Windows 8.1 64 bit. The current build that is being tested is:
```opensc-0.14.0g20150513101938-win64``` and ```opensc-0.14.0g20150513101938-win32```

All registry settings are correct and I can successfully authenticate myself using the card, just PIN management seems to be broken. 

Here is the log file:

https://gist.github.com/sschutte/83b1727274f8a333363f

There seems to be no change since the error is in the same place it was previously:

```
2015-05-13 16:42:07.905 [pkcs15-tool] reader-pcsc.c:184:pcsc_internal_transmit: called
2015-05-13 16:42:07.921 ACS CCID USB Reader 0:SCardTransmit/Control failed: 0x80100068
```

**Comment by dengert** [comment]
If other windows processes are accessing the card, (for example trying to find a driver) the opensc debug log will not show that.
You may need to get a USB trace, or some sort of Windows trace. Look at:

https://technet.microsoft.com/en-us/library/ff404296(v=ws.10).aspx

https://msdn.microsoft.com/en-us/library/cc242851.aspx

  0x80100068 The smart card has been reset, so any shared state information is invalid.

It does no look like a problem with the change pin, as the command is not sent to the card.

This might be usefull too:
http://www.fi.muni.cz/~xsvenda/apduinspect.html


On 5/13/2015 9:48 AM, Shaun Schutte wrote:
> Some feedback from my side while testing nightly builds, changing the PIN of the card is still failing.
> Running |pkcs15-tool.exe --change-pin| results in |Pin code change failed: Transmit failed|
>
> I am testing under Windows 8.1 64 bit. The current build that is being tested is:
> |opensc-0.14.0g20150513101938-win64| and |opensc-0.14.0g20150513101938-win32|
>
> All registry settings are correct and I can successfully authenticate myself using the card, just PIN management seems to be broken.
>
> Here is the log file:
>
> https://gist.github.com/sschutte/83b1727274f8a333363f
>
> There seems to be no change since the error is in the same place it was previously:
>
> |2015-05-13 16:42:07.905 [pkcs15-tool] reader-pcsc.c:184:pcsc_internal_transmit: called
> 2015-05-13 16:42:07.921 ACS CCID USB Reader 0:SCardTransmit/Control failed: 0x80100068
> |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/321#issuecomment-101696792>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Pull request merged**
