### PR TITLE
pkcs11-tool: login if pin_cache disabled or exhausted

### PR DESCRIPTION
**Pull request by nunojpg**
This fixes the remaining case mentioned on #948 according to the suggestion of reacting to a CKR_USER_NOT_LOGGED_IN by trying to login.

| CKA_ALWAYS_AUTHENTICATE | FALSE                             | TRUE |
|----------------------------------------------|-----------------------------------|---------|
| With pinpad                                   | OK (with merged #948)    | OK   |
| Without pinpad                              | OK after this pull request | OK   |

### CODE REVIEW

**Comment by dengert** [comment]
Using this patch with a PIN PAD reader, (CM 3821),   the PIN is requested for every operation, because 
`info.flags & CKF_PROTECTED_AUTHENTICATION_PATH` is always true.

Either:
1. The deleted code to test for `case CKS_RW_USER_FUNCTIONS:` needs to be added back, and the line 
`//logged in, not needed to continue.`
should be replaced by: 
`if (getALWAYS_AUTHENTICATE(session, privKeyObject))`
                 `login(session,CKU_CONTEXT_SPECIFIC);`


2. the test that the session for a RW session  when requesting  CKU_CONTEXT_SPECIFIC should be added to the login() routine.

**Comment by nunojpg** [comment]
Hi,

That code had a bug, in which the test was being made for the whole variable and just not testing the bit.

It should have been: "if(sessionInfo.state & CKS_RW_USER_FUNCTIONS)".

And I removed it because all the paths for authenticate_if_required already include this test in the call path.

Could you please let me know in which case you are seeing a wrong behavior?

**Comment by frankmorgner** [comment]
Please use `goto` only for simplifying error handling. If possible, don't create new spaghetti code (we already have enough of that)...

**Comment by nunojpg** [comment]
@frankmorgner clearly it could be improved.

I also introduced now a small format change for pkcs --test:

* remove "testing signature mechanisms:"
* print "Mechanism not supported" when is the case.
* indent "all 4 signature functions seem to work" at key level.

Master:

```
Using slot 1 with a present token (0x4)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (CITIZEN AUTHENTICATION KEY)
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (CITIZEN AUTHENTICATION KEY)
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (CITIZEN AUTHENTICATION KEY)  -- can't be used to decrypt, skipping
No errors
```

Becomes:

```
Using slot 1 with a present token (0x4)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (CITIZEN AUTHENTICATION KEY)
    all 4 signature functions seem to work
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
Verify (currently only for RSA)
  testing key 0 (CITIZEN AUTHENTICATION KEY)
    RSA-X-509: Mechanism not supported
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (CITIZEN AUTHENTICATION KEY)  -- can't be used to decrypt, skipping
No errors
```

**Comment by frankmorgner** [comment]
please also have a look at the build errors from the CI platforms

**Comment by nunojpg** [comment]
Since there was no comment againts https://github.com/OpenSC/OpenSC/pull/900#issuecomment-261192029, I had the idea OpenSC was now relying on C99.... Fixed.

**Comment by dengert** [comment]
You stated above: "That code had a bug, in which the test was being made for the whole variable and just not testing the bit. It should have been: "if(sessionInfo.state & CKS_RW_USER_FUNCTIONS)".

No, sessionInfo.state is of type CKS_STATE that has 5 possible values, and can be used in a case statement.
You may have been confusing sessionInfo.state with sessionInfo.flags that is of type CKF_FLAGS, 
and  CKS_RW_USER_FUNCTIONS with CKF_RW_SESSION. 

I would like to propose an alternative patch https://github.com/dengert/OpenSC/commits/pkcs11-tool-fix that fixes the issues in authenticate_if_needed of calling login for every crypto operation if a PIN PAD reader is used.

**Comment by nunojpg** [comment]
It looks I am once again confused about the CKS/CKF stuff :(

For me all worked fine when I was using a PINPAD, but it failed when I did a pkcs11-tool --login --test that required 12 logins, and my pin cache allowed for less than that.

With this pull request all the 4 combinations of PINPAD and CKA_ALWAYS_AUTHENTICATE I tested to work.

With your branch, without PINPAD and regardless of pincache enabled or disabled:

```
$ pkcs11-tool -lt
Using slot 0 with a present token (0x0)
Logging in to "Auth PIN (CARTAO DE CIDADAO)".
Please enter User PIN:
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (CITIZEN AUTHENTICATION KEY)
Logging in to "Auth PIN (CARTAO DE CIDADAO)".
Please enter User PIN:
error: PKCS11 function C_Login failed: rv = CKR_USER_ALREADY_LOGGED_IN (0x100)
Aborting.
```

So for me is totally unclear:

* What was the problem you were having with master when using a Pinpad.
* What is the problem you are detecting on my branch.
* How does your branch solve the reason for this pull request: "pkcs11-tool: login if pin_cache disabled or exhausted".

**Comment by dengert** [comment]
Both our changes added a call in the decrypt tests because it had a missing call to authenticate_if_needed.  That being said...

On master I just lived with what pkcs11-tool did and did would not test pinpad with pkcs11-tool. Other programs could test  the pinpad. I do not use the pin cache, and try and setup the environment so a single login will keep the card in the login state, and as needed by CKA_ALWAYS_AUTHENTICATE to enter the pin again. 

I do not put the PIN on the pkcs11-tool command line, I want to be prompted for the PIN when it is needed and never use the pin_cache. 

 PKCS#11 2.40 says:

> The CKA_ALWAYS_AUTHENTICATE attribute can be used to force re-authentication (i.e. force the user to provide a PIN) for each use of a private key. “Use” in this case means a cryptographic operation such as sign or decrypt. This attribute may only be set to CK_TRUE when CKA_PRIVATE is also CK_TRUE.

> Re-authentication occurs by calling C_Login with userType set to CKU_CONTEXT_SPECIFIC immediately after a cryptographic operation using the key has been initiated (e.g. after C_SignInit). In this call, the actual user type is implicitly given by the usage requirements of the active key. If C_Login returns CKR_OK the user was successfully authenticated and this sets the active key in an authenticated state that lasts until the cryptographic operation has successfully or unsuccessfully been completed (e.g. by C_Sign, C_SignFinal,..). A return value CKR_PIN_INCORRECT from C_Login means that the user was denied permission to use the key and continuing the cryptographic operation will result in a behavior as if C_Login had not been called. In both of these cases the session state will remain the same...

(There may be other context specific cases to use it, but it is not a substitute for a normal C_Login.)

The problem with your patch as I stated above when using a PIN PAD: " the PIN is requested for every operation, because info.flags & CKF_PROTECTED_AUTHENTICATION_PATH is always true."
The card has 4 keys. Only one has  CKA_ALWAYS_AUTHENTICATE. 
Thus it was doing 4 times the pin requests that it should have done. 

You change to authenticate_if_needed also removed any test to the state of the session, i.e. 
CKS_*_FUNCTIONS or not. Most failures that return CKR_USER_NOT_LOGGED_IN are for the wrong type
of session. 

I thing the main problem is authenticate_if_needed was designed to handle CKA_ALWAYS_AUTHENTICATE and do C_Login(CKU_CONTEXT_SPECIFIC). 

Note:
authenticate_if_needed is called **before** each crypto operation. It is not called to test if the pin_cache has run out. It could, but its not clear how to tell if the pin_cache_limit has been reached without an operation failing with CKR_USER_NOT_LOGGED_IN.  

What we need is another way to handle CKR_USER_NOT_LOGGED_IN and does another C_LOGIN
that is not  CKU_CONTEXT_SPECIFIC. PKCS#11 2.40 says:

> If the user type is CKU_CONTEXT_SPECIFIC , the behavior of C_Login depends on the context in which it is called. Improper use of this user type will result in a return value CKR_OPERATION_NOT_INITIALIZED..


We could have a authenticate_because_ckr_user_not_logged_in (or some other name) to handle retries if 
ckr_user_not_logged_in is returned. 

What we need is a PKCS11SPY trace when the pin_cache limit is reached, to see what is the state of the session.  **If the state is  CKS_*_FUNCTIONS and function got a  CKR_USER_NOT_LOGGED_IN,
that would imply to try and login again.** 

As far as I know, how a pkcs11 module can do pin caching and tell the application the pin_cache_limit has been reached is not defined in PKCS#11 specs. What is defined is a session can lose it login state, for many reasons, and CKR_USER_NOT_LOGGED_IN can be returned by may functions. 

pkcs11-tool needs to work with more then just opensc-pkcs11.so.

**Comment by nunojpg** [comment]
I'm not understanding what is going in many levels.

When CKF_PROTECTED_AUTHENTICATION_PATH is true, doesn't it mean that the user must insert the pin for every operation? How could the pinpad cache it?

And are you reporting it as a general bug or as a regression created by this patch?

**Comment by dengert** [comment]
Here is another though...

The pin_cache_code sets the pin_cache_counter. But in my option, can get in the way if an application such as pkcs11-tool  can not handle CKR_USER_NOT_LOGGED_IN. 

Using my patch, 
pkcs11-tool does one C_Login to authenticate to the card, then does all its tests.

So the "pin_cache_counter" from the opensc.conf  that maps to 
and is only called from `sc_pkcs15_pincache_revalidate` from `use_key` in `pkcs15-sec.c` 
when a command fails. So  a single C_login should work for all keys that do not have CKA_ALWAYS_AUTHENTICATE or user_consent. 

`sc_pkcs15_pincache_add` will set a `pin_obj->usage_counter = 0;`
and `sc_pkcs15_pincache_revalidate` does `pin_obj->usage_counter++;`
and this is the only place where `pin_obj->usage_counter`. 

So I don't see why a default pin_cache_counter would not work in pkcs11-tool.

Wint modified opensc.conf, running `/opt/ossl-1.0.2/bin/pkcs11-tool --module /opt/ossl-1.0.2/lib/pkcs11-spy.so -l -t`
shows `use_pin_cache=1 pin_cache_counter=3 pin_cache_ignore_user_consent=0`
and so calls no calls to  `sc_pkcs15_pincache_revalidate`
running under gdb confirms it is not called.

Spy shows CKR_USER_NOT_LOGGED_IN is never returned. 
 
Does you card or card require the pin for every crypto operation or for one of the keys?
Does any of its PKCS#15 keys set user_consent?
user_consent can be an integer, not just one. 

pkcs#11 only has CKA_ALWAYS_AUTHENTICATE which in effect is implied if user_consent==1
But it is assumed that CKA_ALWAYS_AUTHENTICATE is fixed for an object, and does not change based on how may operations have been.

Is you card drive doing its own pin_cache  code doing its own usage counter?

**Comment by dengert** [comment]
CKF_PROTECTED_AUTHENTICATION_PATH  PKCS#11 says:
> means that there is some way for a user to be authenticated to the token without having the application send a PIN through the Cryptoki library. One such possibility is that the user enters a PIN on a PINpad

In C_Login it says:
> To log into a token with a protected authentication path, the pPin parameter to C_Login should be NULL_PTR.

Note that PKCS#11 leaves it up to the application to look at the flag and set the NULL_PTR. But if its a good pin pad reader, the reader will not allow a normal verify command to pass, thus forcing the use of the pin pad reader. 

The pkcs11-tool.c:login()   will set the NULL_PTR if CKF_PROTECTED_AUTHENTICATION_PATH is set. 
So authenticate_if_needed does not need to do anything with it as it calls login().

No Pin Pad reader I know of can cache pins in the reader.  OpenSC sends a template of the verify command that the reader then fills in with teh PIN typed on the pin pad reader. So in theory it could
be cached on the reader. 
Normally the user has to enter it each time. The whole  point of a pin pad reader is to enforce a policy to to make the user send in the pin via the pin pad reader each time, thus never exposing the pin to the host where it could be stolen or cached thus avoiding the policy the card provider wants enforced. 
(Not perfect but close.)

OpenSC has a pin_cache capability, that if a crypto operation fails, it will call `sc_pkcs15_pincache_revalidate` and use a cached pin it it is not at its limit.
` if (pin_obj->usage_counter >= p15card->opts.pin_cache_counter) {`

Maybe the problem is  pin_obj->usage_counter is not initialized to zero?

You asked: "How does your branch solve the reason for this pull request: "pkcs11-tool: login if pin_cache disabled or exhausted".
Even when I am using the pin cache, and setting the limit to 3, I never run into the limit.
CKA_ALWAYS_AUTHENTICATE is handled differently then a normal pin. and does not count
toward the usage_count. 



So I am asking you if sc_pkcs15_pincache_revalidate is ever called. 




and  up the usege count for the pin
but only if the usage count is not at its limit.

**Comment by dengert** [comment]
You also asked: "When CKF_PROTECTED_AUTHENTICATION_PATH is true, doesn't it mean that the user must insert the pin for every operation? How could the pinpad cache it?"

Not every operation, only for any login.

CKA_ALWAYS_AUTHENTICATE for a key, means that pin must be entered before every crypto operation 
using that key. If the token also has CKF_PROTECTED_AUTHENTICATION_PATH then the pin needs to be entered. 

(Some PKCS#11 applications can not handle CKA_ALWAYS_AUTHENTICATE/user_consent see opensc.conf  pin_cache_ignore_user_consent which allow an opensc cached pin to be used.)

**Comment by nunojpg** [comment]
I require 12 logins for a pkcs11-tool --test with my card, either with a slot marked with user_consent or not.

So in my case the default pincache_count=10 triggers a failure, because I would need at least 11.

> Using this patch with a PIN PAD reader, (CM 3821), the PIN is requested for every operation, because
> info.flags & CKF_PROTECTED_AUTHENTICATION_PATH is always true.

So was this a regression report or just a confirmation that all works as expected?

**Comment by dengert** [comment]
Can you send a opensc-debug log and a spy log?

(I have to run... will reply more later.)

**Comment by nunojpg** [comment]
I require 12 logins for a pkcs11-tool --test with my card, either with a slot marked with user_consent or not.

So in my case the default pincache_count=10 triggers a failure, because I would need at least 11.

I think I now understand the problem: Login is attempted for operations which shouldn't require it.

I can't experience that for my card, so I will forward you a log using a pinpad for:

* Master - slot user_consent=false
* Master - slot user_consent=true
* This PR - slot user_consent=false
* This PR - slot user_consent=true

Thanks!

**Comment by nunojpg** [comment]
I've discussed with @dengert offline and will continue the discussion here by beginning of April.

**Comment by nunojpg** [comment]
After reviewing #1039 and @dengert comments I don't think I can do any contribution to solve this, so I'm abandoning it.

**Comment by dengert** [comment]
Also see #1064

**Pull request closed without merging**
