### PR TITLE
Removal of old card drivers

### PR DESCRIPTION
**Pull request by xhanulik**
This PR proposes a removal of old card drivers with no recent user or developer activity. All of the following drivers were disabled in #2391.
The process of disabling and removing of old drivers is described on [wiki](https://github.com/OpenSC/OpenSC/wiki/Removal-of-Old-Card-Drivers).

The discussed drivers are:
- `card-akis.c`, last developer modification f947614 (2007),
- `card-flex.c`, 7d935df (2010),
- `card-gpk.c`, a8908b8 (2007),
- `card-incrypto34.c`, a2f622a (2007),
- `card-westcos.c`, c3de15d (2010).

The decision regarding whether all or some of the drivers should be removed, or if they should remain disabled, is open for discussion.

### CODE REVIEW

**Comment by frankmorgner** [comment]
Before removing the driver completely, we should put it into the list of old card drivers first.

Also, for GPK there has recently been user activity (https://github.com/OpenSC/OpenSC/issues/2832), so we should still keep this in the list of old drivers

**Comment by xhanulik** [comment]
> Before removing the driver completely, we should put it into the list of old card drivers first.

All of the mentioned drivers were disabled in #2391, so they are on the list of old card drivers:

https://github.com/OpenSC/OpenSC/blob/33dd3a237225d1adf65a9c503fe81d5f6b3b8649/src/libopensc/ctx.c#L170-L179

> Also, for GPK there has recently been user activity (#2832), so we should still keep this in the list of old drivers

I think this issue was regarding the disabled `asepcos` driver, which is not part of this PR (and the user activity should be already updated on wiki).

**Comment by frankmorgner** [comment]
Thanks for the clearification. However, it looks like `card-flex.c` was still reachable via the "`cyberflex`" driver, because only the predecessor Cryptoflex (`flex`) was moved to the old drivers previously. I think it would be nice to keep both in the list of old drivers for an other release cycle. The removal of the other drivers could be scheduled when the final release of 0.24.0 is out.

**Comment by xhanulik** [comment]
Alright, I will move `cyberflex` into old drivers then.

**Review by frankmorgner — APPROVED** [review]
LGTM

libopensc will be ABI incompatible to previous versions due to the change in defines, we need to make sure to change the library version accordingly before a release.

**Review by Jakuje — APPROVED** [review]

**Comment by frankmorgner** [comment]
> Good point! We should probably note it somewhere or start a draft release issue/pr with the notes so it wont get lost.

I extended the note for the release how to in the wiki, I think that should be enough:
>configure.ac : Update the [LT version number](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html), which is required with changes to, for example, opensc.h and libopensc.exports.

> Just to be clear, are we good to include this with the release in 2 months? I would say yes and lets merge this soon so we can get feedback early if somebody will miss these.

Yes, good for me.

**Pull request merged**
