### PR TITLE
allow failed cross-builds in travis

### PR DESCRIPTION
**Pull request by viktorTarasov**
Results of the cross-build jobs have no impact onto the build status.

Proposal for issue #906

### CODE REVIEW

**Comment by frankmorgner** [comment]
Putting our heads into the sand doesn't bring us any further, the actual error in MinGW-w64 builds needs to be investigated.

Also, `fast_finish` should be `false`

**Comment by frankmorgner** [comment]
Please note that current build status on the main home page is just pathetic. Since the coverity scan limit is constantly exceeded, CI doesn't build any of our code in `master` and the build icon only shows whether we can successfully run `./configure`. See https://github.com/OpenSC/OpenSC/issues/791#issuecomment-258037760

**Comment by viktorTarasov** [comment]
@frankmorgner 
As far as I see, the actual error do not related to OpenSC itself -- it's the problem of build system.

We'll wait a little bit to see if it'll be resolved.

**Comment by viktorTarasov** [comment]
@frankmorgner 
> ... just pathetic ... 

There are at least two reasons:
- _"We're continuing to experience severe build delays on our OS X infrastructure."_ (Travis-CI broadcast) . That's why this PR;
- It seems that there are multiple triggers of coverit-scan per build, for the same source version. It exhausts very rapidly the allowed limit. 

By the way,
could you be more exhaustive with your assertion _"fast_finish should be false"_ ?

**Comment by frankmorgner** [comment]
Opinions from me and other here: https://github.com/OpenSC/OpenSC/issues/791

**Comment by viktorTarasov** [comment]
@frankmorgner 
> See opinions here: #791

Sometimes so enigmatic...
What have I see there? Something more then the same observation?
Or the details about your _"fast_finish should be false"_ assertion?

**Comment by frankmorgner** [comment]
Quoting from #791:

> I'd prefer to see the output of compilation from as many compilers as possible

There are many reasons why a build may fail. In the recent past we have seen problems with download mirrors, the build infrastructure and, quite recently, seemingly arbitrary failures for no reason. I don't want any of these reasons to stop other build jobs.

Also, the warnings (and potentially errors) on Windows/macOS/Linux differ. I want to get all of them, even if a single build fails.

And most important, the review cycles for a PR span from at least one week (simple merge/review done by contributor) to more than several months (more complex merge that you want to have your eyes on). There is no reason to restrict ourself to quick builds.

**Comment by viktorTarasov** [comment]
You still will be able to see the output of compilation for as many compilers as possible,
the only difference is that the failed builds for the, sorry, _second-order-configurations_, which fails for the reasons that are external to the project, do not impact the general status of the build,

**Comment by viktorTarasov** [comment]
The problems with the cross-builds on the travis platform are still lasting.

**Pull request closed without merging**
