### PR TITLE
Better PKCS#11 compliance

### PR DESCRIPTION
**Pull request by tc-anssi**
This pull request removes redundant code introduced in with facaf59 and further improve PKCS#11 compliance.

### CODE REVIEW

**Comment by dengert** [comment]
The changes look good, but in addition to sc_pkcs15emu_add_rsa_prkey setting the access_flags,
there is also sc_pkcs15emu_add_ec_prkey that only sets one of the flags. sc_pkcs15emu_add_ec_prkey should set the same flags as  sc_pkcs15emu_add_rsa_prkey.

**Comment by tc-anssi** [comment]
Hi,

From what I just saw, this is already the case, `sc_pkcs15emu_add_ec_prkey` do the same as the RSA function. 
You might have looked at the pubkey EC function, which only sets `SC_PKCS15_PRKEY_ACESS_EXTRACTABLE` ?

**Comment by dengert** [comment]
On 1/16/2015 9:17 AM, Thomas Calderon wrote:
> Hi,
>
>  From what I just saw, this is already the case, |sc_pkcs15emu_add_ec_prkey| do the same as the RSA function.
> You might have looked at the pubkey EC function, which only sets |SC_PKCS15_PRKEY_ACESS_EXTRACTABLE| ?

Yes I did, sorry.

>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/352#issuecomment-70267722>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by viktorTarasov** [comment]
@JenkinsForOpenSC
retest this please

**Comment by viktorTarasov** [comment]
@JenkinsForOpenSC 
retest this please

**Comment by viktorTarasov** [comment]
retest this please

**Pull request merged**
