### PR TITLE
Define arm64 as a supported architecture in the Installer package

### LINKED ISSUE #2608: Wont install on Apple silicon without Rosetta 2
### Problem Description

0.22 says that it has added support for Apple silicon. When attempting to install the installer will require installing Rosetta 2 to continue installation.

### Steps to reproduce

1. Download installer
2. Mount DMG
3. Run installer

### PR DESCRIPTION
**Pull request by Eitot**
The Installer app assumes that the package requires Rosetta 2, unless arm64 is explicitly declared.

s. https://scriptingosx.com/2020/12/platform-support-in-macos-installer-packages-pkg/

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

Fixes #2608

### CODE REVIEW

**Comment by frankmorgner** [comment]
arm64 is only available when the installer is being built on arm64. arm64 was [added recently to the github runners](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/), but since it requires some quirks, I don't believe this is enabled by default. This PR should be changed so that `hostArchitectures` actually reflects whether or not we are building explicitly for arm (see `$BUILD_ARM` in `MacOSX/build-package.in`. If done so, this PR will fix #2608

**Comment by frankmorgner** [comment]
Just use a second file with all architectures included. Then modify the build script to use the correct distribution file, e.g. something like this:
```diff
diff --git a/MacOSX/build-package.in b/MacOSX/build-package.in
index 509fe0df..07d55167 100755
--- a/MacOSX/build-package.in
+++ b/MacOSX/build-package.in
@@ -58,6 +58,9 @@ export CFLAGS="$CFLAGS -isysroot $SDK_PATH"
 if test -n "${BUILD_ARM}"; then
        export CFLAGS="$CFLAGS -arch x86_64 -arch arm64"
        export LDFLAGS="$LDFLAGS -arch x86_64 -arch arm64"
+       DISTRIBUTION_XML=MacOSX/Distribution_universal.xml
+else
+       DISTRIBUTION_XML=MacOSX/Distribution.xml
 fi
 export OBJCFLAGS=$CFLAGS
 
@@ -220,7 +223,7 @@ pkgbuild --root ${BUILDPATH}/target_token $COMPONENT_TOKEN --identifier org.open
 pkgbuild --root ${BUILDPATH}/target_startup --component-plist MacOSX/target_startup.plist --identifier org.opensc-project.startup --version @PACKAGE_VERSION@ --install-location / OpenSC-startup.pkg
 
 # Build product
-productbuild --distribution MacOSX/Distribution.xml --package-path . --resources MacOSX/resources "${imagedir}/OpenSC @PACKAGE_VERSION@.pkg"
+productbuild --distribution $DISTRIBUTION_XML --package-path . --resources MacOSX/resources "${imagedir}/OpenSC @PACKAGE_VERSION@.pkg"
 
 # Sign installer
 if test -n "${INSTALLER_SIGN_IDENTITY}"; then
```

**Comment by frankmorgner** [comment]
Note, that I'd like to keep support for older xcode versions, because TokenD cannot be built with the newer ones.

**Comment by frankmorgner** [comment]
Thank you. You also need to add the new file to MacOSX/Makefile.am.

**Review by frankmorgner — APPROVED** [review]

**Comment by Jakuje** [comment]
I think it makes sense to include it in the releases, but I am not familiar with the code enough to merge it and before doing another RC with this, I would like to solve the issue with the osx build artifacts mentioned in https://github.com/OpenSC/OpenSC/issues/2426#issuecomment-1274558849

**Comment by Jakuje** [comment]
Thank you for your contribution!

**Pull request merged**
