### PR TITLE
Fix using environmental variables on WIN32.

### PR DESCRIPTION
**Pull request by kouril**
The comparison operator is wrong. The additional variable declaration doesn't make much sense to me.

### CODE REVIEW

**Comment by kouril** [comment]
Could someone here please take a look at the checks to see why the CI jobs are failing? The checks are not passing Linux builds, while the change I made is in a WIN32-defined part of the code, which isn't getting built there. Also, after I tried and re-opened the PR I'm getting two fails instead on a single one that I got before :-). I suspect an issue in the building mechanisms.

**Comment by popovec** [comment]
There is big difference on travis  for previous pull requests tests (for example #1734) --  travis is running Ubuntu 14.04.5 LTS, and  test run for this  pull request - Description:    Ubuntu 16.04.6 LTS


Seems there is problem, that some packages are not installed on travis, from failed OsEID simulation:

_The program 'socat' is currently not installed. To run 'socat' please ask your administrator to install the package 'socat'_

from failed simulation javacard:

_The program 'ant' is currently not installed. To run 'ant' please ask your administrator to install the package 'ant'_

You can add `ant` and `socat` package into `.travis.yml` ..

**Comment by kouril** [comment]
> You can add `ant` and `socat` package into `.travis.yml` ..

Thanks for the investigation. Not sure who your're referring to with "You" but I'd appreciate if someone more familiar with the building systems would take a look :-).

**Comment by frankmorgner** [comment]
thanks

**Pull request merged**
