### PR TITLE
WIP: TCOS: Fix compute_signature for RSA_RAW and 2048 bit keys

### PR DESCRIPTION
**Pull request by jmastr**
Mention which card(s) are used during testing. To get the name of your card,
run this command:
```
% opensc-tool -n
Using reader with a card: Identiv SCR3500 C Contact Reader
TCOS
```

##### Checklist

- [ ] Documentation is added or updated
- [x] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested
- [x] macOS CryptoTokenKit is tested

### CODE REVIEW

**Comment by jmastr** [comment]
```
% pkcs11-tool --login --test
Using slot 0 with a present token (0x0)
Logging in to "IDKey Card".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (IDKey1) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
  testing key 1 (2048 bits, label=IDKey2) with 1 signature mechanism
    RSA-PKCS: OK
couldn't find the corresponding pubkey
  testing key 2 (0 bits, label=IDKey3) with 1 signature mechanism -- can't be used to sign/verify, skipping: can't obtain modulus
couldn't find the corresponding pubkey
  testing key 3 (0 bits, label=IDKey4) with 1 signature mechanism -- can't be used to sign/verify, skipping: can't obtain modulus
couldn't find the corresponding pubkey
  testing key 4 (0 bits, label=IDKey5) with 1 signature mechanism -- can't be used to sign/verify, skipping: can't obtain modulus
couldn't find the corresponding pubkey
  testing key 5 (0 bits, label=IDKey6) with 1 signature mechanism -- can't be used to sign/verify, skipping: can't obtain modulus
Verify (currently only for RSA)
  testing key 0 (IDKey1)
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
  testing key 1 (IDKey2) with 1 mechanism
    RSA-PKCS: OK
  testing key 2 (IDKey3) with 1 mechanism -- can't find corresponding public key, skipping
  testing key 3 (IDKey4) with 1 mechanism -- can't find corresponding public key, skipping
  testing key 4 (IDKey5) with 1 mechanism -- can't find corresponding public key, skipping
  testing key 5 (IDKey6) with 1 mechanism -- can't find corresponding public key, skipping
Decryption (currently only for RSA)
  testing key 0 (IDKey1) 
    RSA-PKCS: OK
  testing key 1 (IDKey2) 
    RSA-PKCS: OK
  testing key 2 (IDKey3) 
couldn't find the corresponding pubkey for validation
    RSA-PKCS:   testing key 3 (IDKey4) 
couldn't find the corresponding pubkey for validation
    RSA-PKCS:   testing key 4 (IDKey5) 
couldn't find the corresponding pubkey for validation
    RSA-PKCS:   testing key 5 (IDKey6) 
couldn't find the corresponding pubkey for validation
    RSA-PKCS: No errors
```

**Comment by frankmorgner** [comment]
CTK is tested as well, right?

**Comment by jmastr** [comment]
> CTK is tested as well, right?

Yes. Works perfectly. I get the pairing notification and cert/PIN pop ups in Chrome.

**Comment by frankmorgner** [comment]
great, thanks

**Pull request merged**
