### PR TITLE
Use LoadLibrarEx with LOAD_WITH_ALTERED_SEARCH_PATH for absolute paths

### PR DESCRIPTION
**Pull request by qpernil**
If an absolute path is given set flags to find dependencies in the same directory, otherwise we can't load libraries that are in a directory that is not in the PATH.

Fixes https://github.com/OpenSC/OpenSC/issues/2291

### CODE REVIEW

**Comment by qpernil** [comment]
Using the pragma to link shlwapi might not be the way to go. I found that shlwapi.h was included in one other place, but couldn't find any mention of the library, so did it like this to make the PR small and self-contained.

**Comment by vjardin** [comment]
Please, could you update your patch in order to fix:
https://travis-ci.org/github/OpenSC/OpenSC/jobs/766455267#L1511
```
libscdl.c:30:0: error: ignoring #pragma comment  [-Werror=unknown-pragmas]
 #pragma comment(lib, "shlwapi")
```
?

**Comment by qpernil** [comment]
> Please, could you update your patch in order to fix:
> https://travis-ci.org/github/OpenSC/OpenSC/jobs/766455267#L1511
> 
> ```
> libscdl.c:30:0: error: ignoring #pragma comment  [-Werror=unknown-pragmas]
>  #pragma comment(lib, "shlwapi")
> ```
> 

OK, it's not being built by Visual Studio build tools I take it. I'll look into it.

**Comment by qpernil** [comment]
I think this builds OK now, the fail seems to be unrelated to my change (and probably temporary)

**Comment by qpernil** [comment]
Any comments on this, is it good to go ?

**Review by frankmorgner — APPROVED** [review]

**Comment by Jakuje** [comment]
one more comment/suggestion. I see that `shlwapi.lib` is added to dozen of build targets in the makefiles and mostly appended to the same list of other libs. Would it make sense to add it to some variable that is used in all of them to avoid the repetition of the same list in all the targets? It would make also the lines a bit shorter and changes easier to review.

This is not a must, but I think it should make the windows makefiles a bit more readable.

**Comment by frankmorgner** [comment]
Unfortunately, all Windows Makefiles are hand crafted right now. I'd leave this as is.

I've seen some cmake projects lately, which are doing a better job of supporting multiple platforms with different IDEs. Maybe this is something OpenSC could use, too. Also, there's a very need [package manager](https://conan.io/) available which integrates nicely...

**Comment by Jakuje** [comment]
Hmm. This looks like breaking the mingw build. I am not sure if it is because of some missing dependency or it needs to be somehow gated for mingw. Can you check?

https://github.com/OpenSC/OpenSC/runs/3534149314

**Comment by Jakuje** [comment]
This should be fixed with https://github.com/OpenSC/OpenSC/pull/2381/commits/520c88d6fdc0c1fe7cb88da9a475d3e3bac7ef77 from #2381 when merged.

**Pull request merged**
