### PR TITLE
Revert "pkcs11-tool: use CKF_USER_PIN_* flags to provide alerts to the user"

### PR DESCRIPTION
**Pull request by viktorTarasov**
Reverts OpenSC/OpenSC#795

The last proposal in PR discussion was to remove the 'if' logique and to dumbly print the active PIN flags. The owner of PR was agree and ready to rework PR.

### CODE REVIEW

**Comment by nunojpg** [comment]
@viktorTarasov, hi, I was about to do as you suggested, but it is a improvement (for me both were OK). Reverts should only happen if a bug is found and a solution is not ready.

That said, I'll open a new pull request with your suggested changes. I think you can close this.

**Comment by viktorTarasov** [comment]
@nunojpg 
> Reverts should only happen if a bug ...

So, without 'if' logique you cannot find the bug, isn't it?

In any case, without relation to your problem, with the only functionality of _pkcs11-tool_ in the mind,
I  think  that all PIN flags has to be reported as they are, without any 'if' logique. (reported together with login type, and other info).

**Comment by nunojpg** [comment]
@viktorTarasov I don't know about any bug/regression related to this. Before or after the commit.

Code that is determined to be not optimal shall be improved. Not reverted. If we start reverting all code that is not perfect I guess we'll end up with a Hello World.

In my head it is very clear: Without a regression nothing shall be reverted.

I think it is formally wrong, but I really don't care, I'll open the pull request as soon as this pull request is closed one way or the other, so I can know from where to rebase the changes.

**Comment by viktorTarasov** [comment]
@nunojpg 
Easy, take it easy!
Look on this PR rather as an invitation for participants to not reject the discussion in the PR closed too fast.

I will look onto the reaction, and if participants have no time to resolve this simple PR in convenient way, I will do it myself.

**Comment by dengert** [comment]
Not enough time is an issue, I would like to look at this when I
    can. 
    
    On 7/11/2016 11:24 AM, viktorTarasov
      wrote:
    
    
      @nunojpg 
        Easy, take it easy!
        Look on this PR rather as an invitation for participants to not
        reject the discussion in the PR closed too fast.
      I will look onto the reaction, and if participants have no time
        to resolve this simple PR in convenient way, I will do it
        myself.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nunojpg** [comment]
@viktorTarasov I am confused... How do you expect participants to solve this? It is your pull request... 

I already said I am available to provide a pull request as suggested by you. But how do you want to articulate it with this PR?

**Comment by viktorTarasov** [comment]
@nunojpg 
well, 
- I have to admit the _revert-PR_ is not quite adequate attempt to bring attention to the PR closed too fast. Take it as an invitation for discussion. Agree, that an _issue_ would be more appropriate for this case.
- I think that we are going to force/rebase the _master_ due to discussion in #823. That will be the occasion to accept a new version of #795.
- if you have (will have) a new version of #795, make it visible (PR, commit ID in your github repository, etc), we will cherry-pick it during the rebase.

**Comment by viktorTarasov** [comment]
master rebased, 
adopted version of #795 is in 1198197586cbfdd800d46301ff74799460944dde.

**Pull request closed without merging**
