### PR TITLE
TrueCrypt support for OpenPGP

### PR DESCRIPTION
**Pull request by hongquan**
Hello,

Here is the patch of OpenPGP to support the use of pkcs15's data object by TrueCrypt.

The method is to map data object to OpenPGP private DOs (0101 - 0104). However, currently, only DO 0101 can be used. Because other DOs (0102 - 0104) cannot be accessed at pkcs15 emulation initialization. Ref: http://sourceforge.net/mailarchive/message.php?msg_id=30646373

Another limitation is the inconsistence of filename between TrueCrypt own file list and token's. Please see these screenshot:
http://storage2.static.itmages.com/i/13/0327/h_1364371394_2877566_f6a08508dd.png
http://storage5.static.itmages.com/i/13/0327/h_1364371606_1091578_409c011341.png
There is no way to store the filename to OpenPGP card, it has to be hard-coded.
 
So, the note for user is: After importing keyfile to token, user should restart TrueCrypt to get the right filename.

### CODE REVIEW

**Comment by frankmorgner** [comment]
any reason why you re-opened this? It's not compiling, see the results of travis or appveyor

**Comment by hongquan** [comment]
Hi. I open this because some OpenPGP users want to use it with TrueCrypt and derivatives.

**Comment by frankmorgner** [comment]
What's your plan? Do you intend to fix the outstanding problems?

**Comment by hongquan** [comment]
Yes, I will fix the build error, and hope that this PR will be accepted.

**Comment by frankmorgner** [comment]
OK, please open a new PR when you've tested your changes (or if you need advice). Please do a clean rebase onto the current master.

**Pull request closed without merging**
