### PR TITLE
harmonize supported ECC curves with pkcs11-tool

### PR DESCRIPTION
**Pull request by philipWendland**
pkcs15-pubkey.c holds a struct containing supported ECC curves. The contents of
this struct are being harmonized with pkcs11-tool supported curves.

### CODE REVIEW

**Comment by philipWendland** [comment]
By the way, the 521 bit curve was recently added to the pkcs15-curves, I think it is not used by any card. 521 is not divisible by 8. There is code that does something like:
```
bytes = field_len / 8;
```
in: 
* `pkcs11/mechanism.c - sc_pkcs11_signature_size()`
* `libopensc/pkcs15-sec.c - sc_pkcs15_derive() and compute_signature()`
* I might not have found all of them

I think this will cause issues. Should the 521 bit curve be removed until this is fixed?

**Comment by dengert** [comment]
On 3/22/2015 11:43 AM, Philip Wendland wrote:
> By the way, the 521 bit curve was recently added to the pkcs15-curves, I think it is not used by any card. 521 is not divisible by 8. There is code that does something like:
>
> |bytes = field_len / 8;

Should that be:

  bytes = (field_len+7)/8;

https://tools.ietf.org/html/rfc6637

    "The adjusted underlying field size is the underlying
     field size that is rounded up to the nearest 8-bit boundary."

But that is only for the uncompressed point format.


> |
>
> in:
>
>   * |pkcs11/mechanism.c - sc_pkcs11_signature_size()|
>   * |libopensc/pkcs15-sec.c - sc_pkcs15_derive() and compute_signature()|
>   * I might not have found all of them
>
> I think this will cause issues. Should the 521 bit curve be removed until this is fixed?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/398#issuecomment-84651724>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by philipWendland** [comment]
Oh, the +7 is for rounding up if necessary. Now I see, thank you.

**Comment by dengert** [comment]
There may be a lot of places that need this...

On 3/22/2015 3:05 PM, Philip Wendland wrote:
> Oh, the +7 is for rounding up if necessary. Now I see, thank you.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/398#issuecomment-84689945>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by viktorTarasov** [comment]
applied, in 4b51b997482d30e62725176422a98689958d77fa

As for length of allocated memory for EC signature, it was correctly implemented in existing EC routines.
For the recent code it's fixed in 090aed2fc239e4a2eda2fac5b4f22a7b281da275.

**Pull request closed without merging**
