### PR TITLE
.github: Workaround broken Github image

### PR DESCRIPTION
**Pull request by Jakuje**
Fixes: #2456

Related: https://github.com/actions/virtual-environments/issues/4589

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by Jakuje** [comment]
For the record, this looks like it is not yet complete solution as it looks like the following step is failing silently
```
+ wine isetup-5.5.6.exe /SILENT /VERYSILENT /SP- /SUPPRESSMSGBOXES /NORESTART
```
as well as the fiollowing one, because the installation above probably failed:
```
+ wine 'C:/Program Files/Inno Setup 5/ISCC.exe' win32/OpenSC.iss
wine: cannot find 'C:/Program Files/Inno Setup 5/ISCC.exe
```
and then we are failing to upload artifacts
```
Warning: No files were found with the provided path: win32/Output/OpenSC*.exe. No artifacts will be uploaded.
```
and the `push-artifacts` task fails because there are no artifacts to pull from cache.

This happens for both 64b and 32b versions.

https://github.com/Jakuje/OpenSC/actions/runs/1517493522

**Comment by Jakuje** [comment]
Not sure what `/SILENT /VERYSILENT` does but it looks like it makes the wine installation hang for no apparent reason.

@dengert if you have some idea what might be going on there, any tips would be appreciated. Hopefully we will get some working image in week or two from Github, but there still might some other issue.

**Comment by Jakuje** [comment]
no idea ... the installation just fails. No warnings from wine are useful so I give up for today.

**Comment by Jakuje** [comment]
lol. Now with 3b18674 where I added exactly the same package list as before, technically dropping `libwine libwine:i386 wine64` (against suggestion from the Debian docs), it looks like it works fine again. Let me wait for the jobs to finish and squash that.

**Comment by Jakuje** [comment]
@dengert unless you will have some concerns about this, I will merge this version soon to get the green-tick again and to make the CI working in PRs again.

**Comment by dengert** [comment]
No concerns. I was not so much interested in `mingw` but in not having the green ticks!

I had said my xubuntu-20.04 system could not find the `wine32` package. But I was using the synaptic "quick" search, which could  not find it. The full search and  `apt show wine32` found it. 

I think Github or Ubuntu fixed the problem. I suspect it was in the repositories or their order or caching.

**Comment by Jakuje** [comment]
> No concerns. I was not so much interested in `mingw` but in not having the green ticks!
> 
> I had said my xubuntu-20.04 system could not find the `wine32` package. But I was using the synaptic "quick" search, which could not find it. The full search and `apt show wine32` found it.

I think you would need to add the 32 arch to find it.

> I think Github or Ubuntu fixed the problem. I suspect it was in the repositories or their order or caching.

Not yet. What we have here is a workaround that we will have to eventually remove, after they will fix it, but I do not suspect it will be earlier than in a week.

**Pull request merged**
