### PR TITLE
Remove legacy EstEID codepaths

### PR DESCRIPTION
**Pull request by metsma**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by martinpaljak** [comment]
I'm pretty sure that the whole mcrd driver could be removed in that case, I don't recall any other active users for it and I doubt new ones have emerged. If the rationale is "unused/maintained old card, lets remove". Yet this specific path (decryption of old documents) might be a reason to keep it around (so that things could be decrypted without manually having to build older versions)

**Comment by metsma** [comment]
> I'm pretty sure that the whole mcrd driver could be removed in that case, I don't recall any other active users for it and I doubt new ones have emerged. If the rationale is "unused/maintained old card, lets remove". Yet this specific path (decryption of old documents) might be a reason to keep it around (so that things could be decrypted without manually having to build older versions)

The only use case in this codepath was for EstEID old cards and this support has been already removed. This is followup cleanup commit.
I cannot comment the other driver support.

**Review by frankmorgner — APPROVED** [review]
thank you.

removal of mcrd can be planned as described here:
https://github.com/OpenSC/OpenSC/wiki/Removal-of-Old-Card-Drivers

**Review by Jakuje — APPROVED** [review]

**Comment by xhanulik** [comment]
As the EstEID support was removed, I updated https://github.com/OpenSC/OpenSC/wiki/Removal-of-Old-Card-Drivers and since there was not any recent user activity either, we can deactivate the driver. I will do it in separate PR.

**Review by xhanulik — APPROVED** [review]

**Pull request merged**
