### PR TITLE
Fix some more memory leaks reported by Coverity

### PR DESCRIPTION
**Pull request by frankmorgner**
Some of them have already been addressed similarily #452

### CODE REVIEW

**Comment by frankmorgner** [comment]
this are quite a lot of changes. if there are no objections, I'll merge in 7 days from now

**Comment by frankmorgner** [comment]
rebased to current master

**Comment by vletoux** [comment]
Code seems to be fine for me except the appVeyor error:
card-piv.c(34) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

(unistd.h was added by this PR)

**Comment by frankmorgner** [comment]
thanks, i missed this! I hope to find time to fix this later this day

**Comment by dengert** [comment]
card-piv.c appears to work fine  on Linux without the  \#define <unistd.h> 
Ok to move the other two \#defines

**Comment by frankmorgner** [comment]
I rebased to master, implemented the simplification in `card-openpgp.c` and fixed the include error on Windows.

@dengert not sure which defines you mean...

**Comment by vletoux** [comment]
seems fine for me

**Comment by dengert** [comment]
What I meant, was original change added   define <unistd.h> to card-piv.c and others.
I removed it, and card-piv.c worked. 
In the lastest version you  wrapped idefine <unistd.h>  in   ifndef _WIN32.

But why did you need to add define <unistd.h> in the first place?

**Comment by frankmorgner** [comment]
@dengert `unistd.h` declares `read()` which is used in `card-piv.c`

**Pull request merged**
