### PR TITLE
pkcs15-tool: new dump-summary command

### PR DESCRIPTION
**Pull request by nunojpg**
This command produces the following output format:

```
PKCS#15 Card [CARTAO DE CIDADAO]:
    Version        : 1
    Serial number  : 0000009483294
    Manufacturer ID: GEMALTO
    Flags          : Read-only, PRN generation, EID compliant

Card has 3 Authentication object(s).

Card has 2 Private key(s).

Card has 0 Public key(s).

Card has 5 Certificate(s).

Card has 5 Data object(s).
```

### CODE REVIEW

**Comment by frankmorgner** [comment]
I personally find it not very usefull...

Please add documentation to `doc/tools/pkcs15-tool.1.xml`

**Comment by nunojpg** [comment]
@frankmorgner What if it was a tree like summary? I want a way to quickly list the pkcs15 capabilities on the card.

**Comment by frankmorgner** [comment]
What about adding a command line switch `--list-info`, that generates:
```
PKCS#15 Card [CARTAO DE CIDADAO]:
    Version        : 1
    Serial number  : 0000009483294
    Manufacturer ID: GEMALTO
    Flags          : Read-only, PRN generation, EID compliant
```
The second part could be retrieved by `pkcs15-tool -D | grep 'Card has'`.

**Comment by viktorTarasov** [comment]
@nunojpg 
> What if it was a tree like summary?

You mean something like this?
```
PKCS#15 Card [CARTAO DE CIDADAO]:
    Version        : 1
    Serial number  : 0000009483294
    Manufacturer ID: GEMALTO
    Flags          : Read-only, PRN generation, EID compliant
    X.509 certificates (number):
        <shorten ID><shorten name>
        <shorten ID><shorten name>
    Private Keys(number):
        <key type><shorten ID><shorten name>
        <key type><shorten ID><shorten name>
PKCS#15 Card [CARTAO DE CIDADAO BIS]:
    ....
```

It could be useful.

**Comment by nunojpg** [comment]
I will implement both and then they can be evaluated by use and code impact. I'm closing this pull request until I update it.

**Comment by nunojpg** [comment]
Hi,

I've implemented:

```
./pkcs15-tool --list-info
PKCS#15 Card [CARTAO DE CIDADAO]:
	Version        : 1
	Serial number  : 000004093842343
	Manufacturer ID: GEMALTO
	Flags          : Read-only, PRN generation, EID compliant
```

and

```
./pkcs15-tool -D --tree  
PKCS#15 Card [CARTAO DE CIDADAO]:
	Version        : 1
	Serial number  : 000004093842343
	Manufacturer ID: GEMALTO
	Flags          : Read-only, PRN generation, EID compliant
Authentication object(s) [3]
  PIN | 01 | Ref:129 (0x81) | Tries left:3 | Auth PIN
  PIN | 02 | Ref:130 (0x82) | Tries left:3 | Sign PIN
  PIN | 03 | Ref:131 (0x83) | Tries left:3 | Address PIN
Private key(s) [2]
  RSA[1024] | 45 | Ref:2 (0x2) | Auth ID:01 | CITIZEN AUTHENTICATION KEY [0x4, sign]
  RSA[1024] | 46 | Ref:1 (0x1) | Auth ID:02 | CITIZEN SIGNATURE KEY [0x200, nonRepudiation]
Public key(s) [0]
Certificate(s) [5]
  Path:3f005f00ef09 | 45
  Path:3f005f00ef08 | 46
  Path:3f005f00ef0f | 51
  Path:3f005f00ef10 | 52
  Path:3f005f00ef11 | 50
Data object(s) [5]
  Path:3f005f00ef02 | Size: 15500 | Citizen Data        
  Path:3f005f00ef05 | Auth ID: 03 | Citizen Address Data
  Path:3f005f00ef07 | Size:  1000 | Citizen Notepad     
  Path:3f005f00ef06 | Size:  4000 | SOD                 
  Path:3f000003     | Size:     6 | TRACE
```

The tree format is highly dependent on the specific objects present on the card, and I tried to make it as generic as possible, but it must be checked with other cards to make sure the output continues to be reasonable. Please give it a try.

Thanks!

**Comment by nunojpg** [comment]
Superseded by #900

**Pull request closed without merging**
