### PR TITLE
Handle long PKCS#11 labels

### PR DESCRIPTION
**Pull request by frankmorgner**
##### Checklist

- [x] PKCS#11 module is tested

### CODE REVIEW

**Comment by muktupavels** [comment]
I quickly tested and this does not produce expected result with my card:
 ```
LATVIA ID         (User PIN)
```

It includes unnecessarily whitespaces.

**Comment by muktupavels** [comment]
Also in `pin_info->auth_type != SC_PKCS15_PIN_AUTH_TYPE_PIN` case token label will not be initialized.

**Comment by frankmorgner** [comment]
thanks for the review. I think the above issues should be fixed now.

**Comment by muktupavels** [comment]
Retested, token label looks good now for my card.

**Comment by muktupavels** [comment]
I just noticed unnecessarily truncation for slot description. I have description that has max length - 64:  
`SCM Microsystems Inc. SCR 3310 [CCID Interface] (21120703310203)`

After these changes it is now ellipsized:  
`SCM Microsystems Inc. SCR 3310 [CCID Interface] (211207033102...`

**Comment by dpward** [comment]
> I just noticed unnecessarily truncation for slot description. I have description that has max length - 64:
> `SCM Microsystems Inc. SCR 3310 [CCID Interface] (21120703310203)`
> 
> After these changes it is now ellipsized:
> `SCM Microsystems Inc. SCR 3310 [CCID Interface] (211207033102...`

The slot description gets [copied from](https://github.com/OpenSC/OpenSC/blob/f070c99b65850ba2f2d40192b59a70712a7902a9/src/pkcs11/slot.c#L56) the name given by the card reader driver. For PCSC, this can be [up to 128 bytes](https://github.com/OpenSC/OpenSC/blob/f070c99b65850ba2f2d40192b59a70712a7902a9/src/libopensc/reader-pcsc.c#L2363), and may contain text after the serial number. On my system it is:

`Broadcom Corp 5880 [Contacted SmartCard] (0123456789ABCD) 00 00`

So I would assume the slot name was already being truncated; what does `opensc-tool --list-readers` show?

**Comment by frankmorgner** [comment]
Indeed, I think the truncation wasn't visible before because it exactly matched the closing bracket. But actuall it got truncated by the 6 characters that indicated the channel id.

**Comment by muktupavels** [comment]
Sorry for noise, it is longer than 64:
```
alberts@z370m-d3h:~$ opensc-tool --list-readers
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              SCM Microsystems Inc. SCR 3310 [CCID Interface] (21120703310203) 00 00
```

**Pull request merged**
