### PR TITLE
Remove only -lglib-2.0 from GIO_LIBS2

### PR DESCRIPTION
**Pull request by xhanulik**
This is the alternative PR to #2689, fixing the problems described in #2615. The `pkg-config` sets `GIO2_LIBS` variable, and then only the unneeded `-lglib-2.0` is removed.

### CODE REVIEW

**Comment by xhanulik** [comment]
@saper could you try whether this would work also for FreeBSD?

**Comment by Jakuje** [comment]
Can you update the workflow files as mentioned in the following comment so we can receive a CI results on configure.ac changes? https://github.com/OpenSC/OpenSC/pull/2689#issuecomment-1413789336

**Review by Jakuje — APPROVED** [review]

**Comment by Jakuje** [comment]
Yes, this came from @mikhailnov in #2566 without much comments. We came to conclusion that some of them are real issues, some of them kind of expected, but wanted to clean up a bit. Thinking about it a bit more I have no strict preference between this and #2689 (while the #2689 being simpler and less code might be a plus though). Any other opinions?

For the particular Glib linking issue, I assume that this is just we not using all the stuff they would like us to use and therefore having unused libraries. I do not think this can be simply addressed in Glib upstream.

**Comment by Jakuje** [comment]
@frankmorgner any opinions or preferences for this and #2689 so we can merge one and move on? I would prefer this solution as it looks like working in all cases we know so far. But would like to hear opinions from others too as this is stalled for some time.

**Comment by frankmorgner** [comment]
OK, fine for me

**Review by frankmorgner — APPROVED** [review]

**Pull request merged**
