### PR TITLE
pkcs11: don't logout to preserve context of concurrent processes

### PR DESCRIPTION
**Pull request by frankmorgner**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Review by Jakuje — APPROVED** [review]
looks reasonable. It is though a question if we should make it a build time (like you propose) or runtime option (as Doug proposed in #2903).

**Comment by frankmorgner** [comment]
> looks reasonable. It is though a question if we should make it a build time (like you propose) or runtime option (as Doug proposed in #2903).

Indeed. As you can see, I even propose to not make it an option for `./configure`, but to still keep it in the source code. I suspect that making this optional (build time/ runtime) would not be used by anyone, but I'm open to other arguments.

**Comment by Jakuje** [comment]
That is a good point. It does not make sense to make it more complicated with configure/configuration options if this would be something that we can hardly support.

**Comment by Jakuje** [comment]
Any other concerns or are we good to merge this change for 0.24.0?

**Comment by dengert** [comment]
Looks good.

**Pull request merged**
