### PR TITLE
PIV implementation of dynamic response buffer using BER_TLV in response #1581

### LINKED ISSUE #1581: Segmentation fault in PIV's piv_general_io
### Problem Description

Fed with the following test data:
```
> 00 cb 3f ff 05 5c 03 5f c1 07 63
< 61 84 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 05 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
> 00 c0 00 00 61
< 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 6 1 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
```

This results in the following backtrace:
```
#0  0x000055555586b844 in sc_simpletlv_read_tag (buf=buf@entry=0x7fffffffd728, buflen=1633645655, tag_out=tag_out@entry=0x7fffffffd70b "", taglen=taglen@entry=0x7fffffffd738) at simpletlv.c:83
#1  0x00005555556db942 in piv_parse_ccc (card=0x5555558fa640, card=0x5555558fa640, rbuflen=<optimized out>, rbuf=<optimized out>) at card-piv.c:2747
#2  piv_process_ccc (card=0x5555558fa640) at card-piv.c:2787
#3  piv_match_card_continued (card=card@entry=0x5555558fa640) at card-piv.c:3272
#4  0x00005555556dc930 in piv_match_card (card=0x5555558fa640) at card-piv.c:3107
#5  piv_match_card (card=0x5555558fa640) at card-piv.c:3076
#6  0x000055555559f79c in sc_connect_card (reader=reader@entry=0x5555558fa4a0, card_out=card_out@entry=0x7fffffffddc0) at card.c:295
#7  0x000055555557c169 in util_connect_card_ex (ctx=0x5555558f9260, cardp=0x5555558f2220 <card>, reader_id=<optimized out>, do_wait=<optimized out>, do_lock=0, verbose=0) at util.c:154
#8  0x00005555555672e3 in main (argc=<optimized out>, argv=<optimized out>) at pkcs15-tool.c:2303
```
The problem is the automatic parsing of the data, which saves the **big** ASN.1 length in `bodylen`

https://github.com/OpenSC/OpenSC/blob/c3a9837b1064fdb173a9ea8ce3f7062a440674f3/src/libopensc/card-piv.c#L615-L623

and returns it as result of `piv_general_io` although `sc_asn1_read_tag` has previously errored with `SC_ERROR_ASN1_END_OF_CONTENTS`:

https://github.com/OpenSC/OpenSC/blob/c3a9837b1064fdb173a9ea8ce3f7062a440674f3/src/libopensc/card-piv.c#L637-L640

### Proposed Resolution

I don't see an obvious fix. The whole magic around caching and parsing data in `card-piv.c` is a big mess, that's repeatedly breaking OpenSC. If it doesn't see any serious rework, I'll disable PIV driver by default. It needs to become readable and maintainable, sacrificing simplicity for saving a couple of lines of code should be avoided. Given the fact that macOS and Windows include proprietary default drivers, the impact of disabling PIV in OpenSC is hopefully limited. @dengert, please have a look.

### Steps to reproduce

https://github.com/OpenSC/OpenSC/pull/1580

### PR DESCRIPTION
**Pull request by dengert**
Fixes #1581 caused by multiple reads of the tag during fuzzing tests.

The PIV card uses a number of ISO 7816-4 instructions where the payload shall be encoded in BER-TLV.
ISO 7816-4 recommends these be DER encoded, which they in the PIV case. These include the odd numbered GET DATA, GENERAL AUTHENTICATE and GENERATE ASYMMETRIC KEY PAIR. Thus when reading any of these payloads, the size of the data to read is defined by the BER_TLV tag plus the size of the tag. The only way to determine the size is to read the object.

Current PIV code does this in 2 steps. It uses GET DATA to read the first 8 bytes that will contain the
BER_TLV tag. Then it allocates a buffer then does a second GET DATA to read the tag and data.

In some recent fuzzing  tests see #1581 the first tag did not match the second tag causing problems.

This commit allocates a starting buffer, reads the first 256 bytes, parses the tag, checks its length,
reallocates the buffer (if needed) then continues to read the rest of the data using GET RESPONSE. 
The tag is only read once. This is done by using the apdu SC_APDU_FLAGS_NO_GET_RESP to get control back after the initial 256 bytes of data are read for T1 and for T0 after the first GET RESPONSE command completes.

Placing this code in apdu.c could be possible but very difficult. So this code is completely contained
in card-piv.c

 On branch piv-dynamic-resp

 Changes to be committed:
	modified:   src/libopensc/card-piv.c

##### Checklist

- [x] PKCS#11 module is tested

### CODE REVIEW

**Comment by mouse07410** [comment]
```
$ OPENSC_DEBUG=9 pkcs11-tool --test --login
P:40213; T:0x4670629312 14:29:04.640 [opensc-pkcs11] ctx.c:720:process_config_file: Used configuration file '/Library/OpenSC/etc/opensc.conf'
Using slot 0 with a present token (0x0)
Logging in to "Blumenthal, Uri (UR20980)".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
  SHA256: OK
  SHA384: OK
  SHA512: OK
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
error: PKCS11 function C_Sign failed: rv = CKR_GENERAL_ERROR (0x5)
Aborting.
    RSA-X-509: $ 
$ 
```

Log excerpt:
```
. . . . .
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] pkcs15-sec.c:677:sc_pkcs15_compute_signature: DEE flags:0x00000001 alg_info->flags:0x00000001 pad:0x00000000 sec:0x00000001
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card.c:477:sc_lock: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card.c:517:sc_lock: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] sec.c:105:sc_set_security_env: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card-piv.c:2360:piv_set_security_env: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card-piv.c:2365:piv_set_security_env: flags=00000014 op=2 alg=0 algf=00000001 algr=00000000 kr0=9a, krfl=1
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card-piv.c:2392:piv_set_security_env: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] sec.c:109:sc_set_security_env: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] sec.c:59:sc_compute_signature: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card-piv.c:2493:piv_compute_signature: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card-piv.c:2421:piv_validate_general_authentication: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card-piv.c:587:piv_general_io: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card.c:477:sc_lock: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card.c:517:sc_lock: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card.c:477:sc_lock: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] card.c:517:sc_lock: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:10, INS:87, P1:7, P2:9A, data(255) 0x7ffee5186430
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] reader-pcsc.c:285:pcsc_transmit: reader 'Yubico Yubikey 4 OTP+U2F+CCID'
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] reader-pcsc.c:286:pcsc_transmit:
Outgoing APDU (260 bytes):
10 87 07 9A FF 7C 82 01 06 82 00 81 82 01 00 00 ....ÿ|..........
01 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF .ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ
FF FF FF FF FF FF FF FF FF FF FF 00 30 21 30 09 ÿÿÿÿÿÿÿÿÿÿÿ.0!0.
06 05 2B 0E 03 02 1A 05 00 04 14 29 B0 E7 87 82 ..+........)°ç..
71 64 5F FF                                     qd_ÿ
P:40213; T:0x4670629312 14:29:07.562 [opensc-pkcs11] reader-pcsc.c:214:pcsc_internal_transmit: called
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] reader-pcsc.c:295:pcsc_transmit:
Incoming APDU (2 bytes):
90 00 ..
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:87, P1:7, P2:9A, data(11) 0x7ffee518652f
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] reader-pcsc.c:285:pcsc_transmit: reader 'Yubico Yubikey 4 OTP+U2F+CCID'
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] reader-pcsc.c:286:pcsc_transmit:
Outgoing APDU (17 bytes):
00 87 07 9A 0B B7 EE C7 DB 4A 74 73 A1 C0 0B C1 .....·îÇÛJts¡À.Á
00                                              .
P:40213; T:0x4670629312 14:29:07.563 [opensc-pkcs11] reader-pcsc.c:214:pcsc_internal_transmit: called
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] reader-pcsc.c:295:pcsc_transmit:
Incoming APDU (3 bytes):
7C 61 FF |aÿ
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card.c:527:sc_unlock: called
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card-piv.c:533:piv_apdu_realloc_resp: called
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card-piv.c:539:piv_apdu_realloc_resp: Unable to parse length: -1401 (Invalid ASN.1 object)
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card-piv.c:560:piv_apdu_realloc_resp: returning with: -1401 (Invalid ASN.1 object)
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card-piv.c:640:piv_general_io: Transmit failed: -1401 (Invalid ASN.1 object)
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card.c:527:sc_unlock: called
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card-piv.c:712:piv_general_io: returning with: -1401 (Invalid ASN.1 object)
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card-piv.c:2474:piv_validate_general_authentication: returning with: -1401 (Invalid ASN.1 object)
P:40213; T:0x4670629312 14:29:07.698 [opensc-pkcs11] card-piv.c:2551:piv_compute_signature: returning with: -1401 (Invalid ASN.1 object)
P:40213; T:0x4670629312 14:29:07.699 [opensc-pkcs11] sec.c:63:sc_compute_signature: returning with: -1401 (Invalid ASN.1 object)
. . . . .
```

Complete log: 
[opensc-debug-1723.log.txt](https://github.com/OpenSC/OpenSC/files/3369809/opensc-debug-1723.log.txt)

**Comment by dengert** [comment]
Thanks, I will look at it.

**Comment by dengert** [comment]
I can reproduce this on a Yubkey.

Problem is Yubkey only returned a single byte and "61 FF" as response to the compute signature operation that is chained. 
First part of chained operation starts 260 bytes :`10 87 07 9A FF 7C 82 01 06 82 00 81 82 01 00 00...`
response 2 bytes `90 00` (as expected.)
Second/last part of chained command 17 bytes: `00 87 07 9A 0B B7 EE C7 DB 4A 74 73 A1 C0 0B C1 00`
response  3 bytes `7C 61 FF` (Other cards would return up to 256 bytes of the response.)

The Yubkey does this with unmodified code, but the modified code was expecting the card to return as much of the response as it could which would include the full tag. '7C' is just the first byte of the tag so it could not be parsed.  

I am working on a fix that will postpone the parsing of the tag (and buffer reallocation) if this happens.

**Comment by mouse07410** [comment]
> I can reproduce this on a Yubkey

Haven't tested it on CAC (don't want to risk locking myself out), but it's possible that CAC would also "misbehave" here...

> I am working on a fix that will postpone the parsing of the tag (and buffer reallocation) if this happens.

Thank you!

**Comment by dengert** [comment]
You could use the current versions of OpenSC with debug output to see if it could happen. 
Look for the response where a signature is returned. Look for the first response that has the start of the signature. It should return 256 bytes + status and a get response would return the remainder. 

With a CAC/PIV  I would expect the first response would be 256 bytes.(as requested in Le) The Yubikey only returned 1 byte + status fora total of 3 in the first response. That sounds like a bug, but iso7816-4 allows it.   
 The Yubico appears to return some arbitrary amount of bytes in the first response. I see 211, 108 in addition to the 3. 

This PR is expecting the tag to be in the first response to contain the full tag, in this case '7C 82 01 04' other objects may have a larger tag.

**Comment by dengert** [comment]
@mouse07410 give this version a try. It addresses the Yubikey issues.

**Comment by mouse07410** [comment]
```
$ pkcs11-tool --test --login
Using slot 0 with a present token (0x0)
Logging in to "Mouse".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  seems to be OK
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
  SHA256: OK
  SHA384: OK
  SHA512: OK
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
    SHA384-RSA-PKCS: OK
    SHA512-RSA-PKCS: OK
  testing key 1 (2048 bits, label=SIGN key) with 1 signature mechanism
    RSA-X-509: OK
  testing key 2 (2048 bits, label=KEY MAN key) with 1 signature mechanism -- can't be used to sign/verify, skipping
  testing key 3 (2048 bits, label=CARD AUTH key) with 1 signature mechanism
    RSA-X-509: OK
Verify (currently only for RSA)
  testing key 0 (PIV AUTH key)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
    SHA384-RSA-PKCS: OK
    SHA512-RSA-PKCS: OK
  testing key 1 (SIGN key) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (KEY MAN key) with 1 mechanism -- can't be used to sign/verify, skipping
  testing key 3 (CARD AUTH key) with 1 mechanism
    RSA-X-509: OK
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (PIV AUTH key) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 1 (SIGN key) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 2 (KEY MAN key) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 3 (CARD AUTH key) 
    RSA-X-509: OK
    RSA-PKCS: OK
No errors
$ pkcs11-rsa-encr-demo2
This is not a CAC
Using KEY MAN key...
Generate a random data file (1000 bytes), Base64-encoded...
openssl rand -base64 -out /tmp/derive.63807.text 1000

Generated
  key: 0f5e9011b3f5c7936b001be3a712c15f3e4dbd9bb0633ffbd1065dfb9bd7945c
  iv:  448896bed4cc015ebfcc3801600c440b

Encrypt file /tmp/derive.63807.text with this key and IV...
openssl enc -aes-256-cfb -a -e -in /tmp/derive.63807.text -out /tmp/derive.63807.text.enc -K 0f5e9011b3f5c7936b001be3a712c15f3e4dbd9bb0633ffbd1065dfb9bd7945c -iv 448896bed4cc015ebfcc3801600c440b

Encrypting this random symmetric key to token RSA KEY MAN key...
echo 0f5e9011b3f5c7936b001be3a712c15f3e4dbd9bb0633ffbd1065dfb9bd7945c | xxd -r -p -c 200 | openssl pkeyutl -engine pkcs11 -keyform engine -encrypt -pubin -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20pubkey;type=public" -pkeyopt rsa_padding_mode:oaep -out /tmp/derive.63807.key.enc
engine "pkcs11" set.

Decrypting the symmetric key on the token...
openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:manufacturer=piv_II;object=KEY%20MAN%20key;type=private" -pkeyopt rsa_padding_mode:oaep -in /tmp/derive.63807.key.enc | xxd -p -c 200
engine "pkcs11" set.
Enter PKCS#11 token PIN for Mouse:

Decrypt file /tmp/derive.63807.text.enc with this key and IV...
openssl enc -aes-256-cfb -a -d -in /tmp/derive.63807.text.enc -out /tmp/derive.63807.text.dec -K 0f5e9011b3f5c7936b001be3a712c15f3e4dbd9bb0633ffbd1065dfb9bd7945c -iv 448896bed4cc015ebfcc3801600c440b

KEY1="0f5e9011b3f5c7936b001be3a712c15f3e4dbd9bb0633ffbd1065dfb9bd7945c"
KEY2="0f5e9011b3f5c7936b001be3a712c15f3e4dbd9bb0633ffbd1065dfb9bd7945c"
Original and decrypted keys  match
Original and decrypted files match
$ 
```

**Comment by mouse07410** [comment]
CAC works:
```
$ pkcs11-tool --slot 0x4 --test --login
Logging in to " . . . . . ".
Please enter User PIN: 
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_FUNCTION_NOT_SUPPORTED (0x54)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
  SHA256: OK
  SHA384: OK
  SHA512: OK
Signatures (currently only for RSA)
  testing key 0 (PIV AUTH key) 
  all 4 signature functions seem to work
  testing signature mechanisms:
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
    SHA384-RSA-PKCS: OK
    SHA512-RSA-PKCS: OK
  testing key 1 (2048 bits, label=SIGN key) with 1 signature mechanism
    RSA-X-509: OK
  testing key 2 (2048 bits, label=KEY MAN key) with 1 signature mechanism -- can't be used to sign/verify, skipping
Verify (currently only for RSA)
  testing key 0 (PIV AUTH key)
    RSA-X-509: OK
    RSA-PKCS: OK
    SHA1-RSA-PKCS: OK
    MD5-RSA-PKCS: OK
    RIPEMD160-RSA-PKCS: OK
    SHA256-RSA-PKCS: OK
    SHA384-RSA-PKCS: OK
    SHA512-RSA-PKCS: OK
  testing key 1 (SIGN key) with 1 mechanism
    RSA-X-509: OK
  testing key 2 (KEY MAN key) with 1 mechanism -- can't be used to sign/verify, skipping
Unwrap: not implemented
Decryption (currently only for RSA)
  testing key 0 (PIV AUTH key) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 1 (SIGN key) 
    RSA-X-509: OK
    RSA-PKCS: OK
  testing key 2 (KEY MAN key) 
    RSA-X-509: OK
    RSA-PKCS: OK
1 errors
$ 
```

**Comment by dengert** [comment]
In regards to your question in: https://github.com/OpenSC/OpenSC/issues/1710#issuecomment-512622263
Thanks for trying this. It pointed out that a card might not return as much data as expected and the tag may span multiple responses. 

I was hopping to get more comments form others too. 

I have worked on another version of this that put the reallocate in apdu.c and stored the `rbuflen` and `rbufused` in the `sc_apdu_t` This would allow other drivers to use use dynamic buffers where the size is contained in a leading TLV. This is defined in ISO7816-4 for a number of odd number commands. 

Anyone interested in a sc_apdu_t version?

**Comment by mouse07410** [comment]
> I have worked on another version of this that put the reallocate in `apdu.c` ...
> Anyone interested in a `sc_apdu_t` version?

The benefit of this other version is that it works with other drivers, not only PIV? It would be nice in general, but I've no way of testing it. And besides, I'd need to revert #1723...

**Pull request closed without merging**
