### PR TITLE
2nd try. DNIe UI moved into card-dnie.c. Handles:  Bad implementation of DNIe's UI #362

### PR DESCRIPTION
**Pull request by germanblanco**
This change removes unused code and removes user-interface module.

### CODE REVIEW

**Comment by germanblanco** [comment]
.. and thank you @frankmorgner for spotting the problem with Makefile.mak

**Comment by frankmorgner** [comment]
looks OK

**Comment by germanblanco** [comment]
I am assuming that the error reported by AppVeyor:
customactions.cpp(42) : fatal error C1083: Cannot open include file: 'wcautil.h': No such file or directory
Doesn't have to do with the changes, or?

**Comment by timofonic** [comment]
I'm just a lurker and frustrated user of DNIe. Nothing against your
efforts, you are doing a great one, but the support sucks.

What will happen with DNIe and the new DNIe version? Will it feature NFC?

I don't know so much about these technologies, but I'm tired of the Java
requirement and all the issues.Telefonica just cannibalized OpenSC and
didn't provide a proper implementation, it even has issues on Microsoft
Windows too.

I'm really surprised HTML5 didn't take this as a serious item.

I'm afraid the same will happen with it and the mess will be tried to be
solved with so little support.


What's the current status of NFC under Linux? Will OpenSC support it?

https://01.org/linux-nfc
http://open-nfc.org/wp/editions/linux-edition/
http://nfc-tools.org/index.php?title=Libnfc
https://www.opensc-project.org/opensc/ticket/218
https://github.com/soixantecircuits/ofxNFCReader/issues/3
https://frankmorgner.github.io/vsmartcard/remote-reader/README.html
https://github.com/OpenSC/OpenSC/issues/377

Kind regards.

**Comment by dengert** [comment]
In regard to NFS and OpenSC. PCSC supports a number of NFC readers, see:

https://pcsclite.alioth.debian.org/ccid/shouldwork.html

I have been using a Advanced Card Systems ACR122U as part of a GoToTags package.
On ubuntu, I had to blanklist some modules that grabed the device  by adding the file:
/etc/modprobe.d/blacklist-libnfc.conf:
blacklist pn533
blacklist nfc

PCSC can then use it as a CCID device.

Some cards may only allow access to selected files
and restrict the use of crypto or the PIN over NFC (PIV  specifications require restricted access)
The Yubico NEO has a PIV applet but does not meet the specs and allows everything over NFC, thus the issue:
https://github.com/OpenSC/OpenSC/issues/377
(I got the ACR122U to test this issue.)

Some cards may require Secure messaging over NFC to avoid the security risks of NFC.

You need to check your card specs. OpenSC needs little or no changes.

On 11/13/2015 3:06 PM, timofonic wrote:
> I'm just a lurker and frustrated user of DNIe. Nothing against your
> efforts, you are doing a great one, but the support sucks.
>
> What will happen with DNIe and the new DNIe version? Will it feature NFC?
>
> I don't know so much about these technologies, but I'm tired of the Java
> requirement and all the issues.Telefonica just cannibalized OpenSC and
> didn't provide a proper implementation, it even has issues on Microsoft
> Windows too.
>
> I'm really surprised HTML5 didn't take this as a serious item.
>
> I'm afraid the same will happen with it and the mess will be tried to be
> solved with so little support.
>
>
> What's the current status of NFC under Linux? Will OpenSC support it?
>
> https://01.org/linux-nfc
> http://open-nfc.org/wp/editions/linux-edition/
> http://nfc-tools.org/index.php?title=Libnfc
> https://www.opensc-project.org/opensc/ticket/218
> https://github.com/soixantecircuits/ofxNFCReader/issues/3
> https://frankmorgner.github.io/vsmartcard/remote-reader/README.html
> https://github.com/OpenSC/OpenSC/issues/377
>
> Kind regards.
>
> On Fri, Nov 13, 2015 at 6:40 PM, Germán Blanco <notifications@github.com>
> wrote:
>
>  > I am assuming that the error reported by AppVeyor:
>  > customactions.cpp(42) : fatal error C1083: Cannot open include file:
>  > 'wcautil.h': No such file or directory
>  > Doesn't have to do with the changes, or?
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/OpenSC/OpenSC/pull/605#issuecomment-156497502>.
>  >
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/605#issuecomment-156556990>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by CardContact** [comment]
Douglas is right. Generally the term NFC is little fuzzy: The original idea of NFC was to allow a close coupling between two device. Therefore industry "reinvented" ISO 14443, that was already in use for simple contactless chip cards (Mifare and alike). These cards/tags typically use ISO 14443 up to layer 3, but a proprietary protocol for data exchange.

The business idea was to place a chip at every billboard, so that a consumer could hold his mobile device at the chip to obtain more data for the advertised product. With much cheaper QR-Codes and a camera in the mobile phone that failed.

More sophisticated smart cards - and this is what OpenSC is all about - typically use either contact based communication as defined in ISO 7816-3 or contactless communication from ISO 14443-4. In either case they exchange APDUs, which are the famous CLA,INS,P1,P2,Lc,Data,Le sequences.

There are prominent examples for "NFC" like smart cards, like the German eID card or some PIV cards.

A general problem of contact-less smart cards is, that eavesdropping on the contactless interface is fairly simple. An attacker can easily obtain a PIN used for authentication, unless communication between the card and the terminal is protected (e.g. by secure messaging or using a challenge/response protocol). However, secure messaging requires the establishing of keys on both sides of the communication channel, which is what protocols like PACE or ChipAuthentication can provide for. Both schemes have in common that no pre-shared keys are required at the terminal.

In particular with ChipAuthentication there are some interesting new application possible, like what we do in the CoolPACS project (www.coolpacs.org).

**Comment by germanblanco** [comment]
If anybody has suggestions for uses of NFC together with DNIe 3.0, my friends at Fidesmo might also be interested. And if any changes are required in OpenSC, I would love to see the Issue for the Enhancement in the list.
A new Issue would also be the place (I think) to suggest support for DNIe 3.0. I was going to write it myself, but help is always welcome.
Many of the questions in the mail from @timofonic should be directed to the Spanish Administration. In case there is any doubt, I have no professional relationship with the Spanish Public Administration, and they might or might not read this thread at all.
In any case, this thread was about a pure programming-code-cleanup Pull Request, so taking profit of the momentum, could any committer please see if the change can be accepted?
And by the way, I think OpenSC is a great open source project, and the team working on it are very professional and helpful. The support for DNIe has room for improvement, but hopefully it will get better, and in any case the core team of OpenSC can do very little about it (none of them have a Spanish DNI to work on as far as I know). I do have a DNIe (3.0 thanks to the DGP) and work on this project once in a while, but as a hobby, so performance depends mostly on how busy I am with "real life".

**Comment by timofonic** [comment]
Well, I don't trust so much how things are done here in Spain. You know, "Spain is different" slogan from latest Franco regime is used very sarcastically ;)

I just want this technology to be usable directly under Linux without a custom configuration and help to make it popular and usable for my needs:

- Dealing with bureaucracy: I often forget dates and I consider bureaucracy very exhausting, I try to do all the paperwork digitally to avoid moving and do it at any time of day.
- Signing digital documents: 
* I'm terrible at dealing deadtree documents:  I often lost them or get messed handwriting at them. Fortunately I'm at least a lot better at using a computer to type, I'm a very fast and efficient touch typist if using a mechanical keyboard (Model M is my favourite).
* I'm actually studying electronics at a vocational school: I would love to be able to send homework digitally signed. Then my teachers would sign them back with the grade following the established grading methodology.

Are DNIe 3.0 available these days? I would get one and help at testing, despite I hate Java A LOT (please, how to eliminate this plague from Spanish Public Administration?).

Thanks a lot for your efforts, they are greatly appreciated! I just don't understand how someone in his spare time can do things a lot better than an entire government. You're really brave and skilled!

That's all. Sorry for the offtopic!

**Comment by frankmorgner** [comment]
Changing from contact-based to contact-less solves some problems, but it also brings some new ones. And I'm pretty sure that it won't solve the main issues DNIe 2.0 currently has (without even knowing what problems there might be).

**Comment by frankmorgner** [comment]
Has anyone else verified this PR?

**Comment by dengert** [comment]
No, don't have card. AppVeyor has a lot of failures!

On 11/14/2015 3:49 PM, Frank Morgner wrote:
> Has anyone else verified this PR?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/605#issuecomment-156748415>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
AppVeyor has changed its configuration regarding WiX... (not related to this PR)

**Comment by miguel-cv** [comment]
[OFFTOPIC] @timofonic 
In NFC topic, in http://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1120 you have some sample applications for android (with source) to read dnie certificates with a nfc mobile.

http://s10.postimg.org/52wqvwe21/dninfc2.jpg

Blacked parts are my name,dni number and CAN.

**Comment by germanblanco** [comment]
@miguel-cv, @rickyepoderi, could you please say if this works for you?

**Comment by rickyepoderi** [comment]
@germanblanco I'll try to test it as soon as possible but maybe you have to wait until weekend. Sorry.

@dengert I'll answer you in the other issue to maintain the conversation in the same thread.

**Comment by miguel-cv** [comment]
Tested, works for me. Signed a PDF document, the dialog appears to ask for confirmation.

**Comment by rickyepoderi** [comment]
I also tested this morning. It works as expected with and without the --enable-dnie-ui option. I can only test it in linux.

**Comment by frankmorgner** [comment]
thanks all

**Pull request merged**
