### PR TITLE
Fix issues with uninitialized object identifiiers with OpenPACE

### PR DESCRIPTION
**Pull request by frankmorgner**
fixes https://github.com/OpenSC/OpenSC/issues/2354

##### Checklist

- [x] Documentation is added or updated
- [x] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by Jakuje** [comment]
OSX build here fails with:
```
sm-eac.c:417:45: error: implicit declaration of function 'EAC_OBJ_nid2obj' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                data->cryptographic_mechanism_reference = EAC_OBJ_nid2obj(protocol);
                                                          ^
sm-eac.c:417:45: note: did you mean 'OBJ_nid2obj'?
/Users/runner/work/OpenSC/OpenSC/openssl_bin/Library/OpenSC/include/openssl/objects.h:59:14: note: 'OBJ_nid2obj' declared here
ASN1_OBJECT *OBJ_nid2obj(int n);
             ^
sm-eac.c:417:43: error: incompatible integer to pointer conversion assigning to 'ASN1_OBJECT *' (aka 'struct asn1_object_st *') from 'int' [-Werror,-Wint-conversion]
                data->cryptographic_mechanism_reference = EAC_OBJ_nid2obj(protocol);
                                                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```
Is it something to be addressed with inside of the openpace or in opensc build?

**Comment by frankmorgner** [comment]
thanks for the pointer. Using EAC_OBJ_nid2obj is intended as OpenPACE internally extends the object identifiers that may not be visible when the library is linked statically. that's why we ship a wrapper around this openssl function.

**Comment by frankmorgner** [comment]
> OSX build here fails with:
> 
> ```
> sm-eac.c:417:45: error: implicit declaration of function 'EAC_OBJ_nid2obj' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>                 data->cryptographic_mechanism_reference = EAC_OBJ_nid2obj(protocol);
>                                                           ^
> sm-eac.c:417:45: note: did you mean 'OBJ_nid2obj'?
> /Users/runner/work/OpenSC/OpenSC/openssl_bin/Library/OpenSC/include/openssl/objects.h:59:14: note: 'OBJ_nid2obj' declared here
> ASN1_OBJECT *OBJ_nid2obj(int n);
>              ^
> sm-eac.c:417:43: error: incompatible integer to pointer conversion assigning to 'ASN1_OBJECT *' (aka 'struct asn1_object_st *') from 'int' [-Werror,-Wint-conversion]
>                 data->cryptographic_mechanism_reference = EAC_OBJ_nid2obj(protocol);
>                                                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
> 2 errors generated.
> ```
> 
> Is it something to be addressed with inside of the openpace or in opensc build?

I've changed the code to check whether `EAC_OBJ_nid2obj` is available in that specific version of OpenPACE. Additionally, I've updated the OpenPACE version for macOS. The build is OK now :wink:

**Review by Jakuje — APPROVED** [review]

**Comment by frankmorgner** [comment]
cleaned up the commits and rebased onto master

**Pull request merged**
