### PR TITLE
pkcs15-init: Set algorithm after parsing spec

### PR DESCRIPTION
**Pull request by xhanulik**
Move the algorithm setting in `do_generate_skey()` after parsing the spec.

##### Checklist
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by Jakuje** [comment]
This is very similar pattern as in `do_store_secret_key()`, where this is handled correctly. I assume this was just mistype.

I actually did not try to generate symmetric key with pkcs15init on my myeid card yet. @fabled or @popovec can you check the change looks fine for you? Does OseID support key generation on card? Do you have it covered with tests Peter?

**Review by Jakuje — APPROVED** [review]

**Comment by popovec** [comment]
MyEID/OsEID card is not affected by this PR. There is no support for symmetric key generation on the OsEID card. It is possible to upload a symmetric key to this card. This conforms to the MyEID card specification as described in the MyEID Java Card 2.4.1 Reference Manual.

**Comment by Jakuje** [comment]
> MyEID/OsEID card is not affected by this PR. There is no support for symmetric key generation on the OsEID card. It is possible to upload a symmetric key to this card. This conforms to the MyEID card specification as described in the MyEID Java Card 2.4.1 Reference Manual.

Thanks for checking. So it looks like a unused code. I do not see symmetric key support in any other driver right now so this is likely dead code for opensc.

**Comment by fabled** [comment]
LGTM.

**Pull request merged**
