### PR TITLE
card-rtecp: Add Rutoken Lite

### PR DESCRIPTION
**Pull request by dfortinskiy**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by dfortinskiy** [comment]
> `decipher()` and `compute_signature()` are not implemented, so from a user's perspective there's not a lot to do with this card. Adding this card to OpenSC only makes sense if one of these would be implemented.

Rutoken Lite doesn't support any cryptographic operations (incl. `decipher()` and `compute_signature()`), so they are cut. But there are some people who use such cards for operations with data objects only with PIN protection. By happy occasion they also use OpenSC, so we have thought it could be nice to add such card.

If you really consider it should not be in upstream, than it's OK. 

> don't use `SC_CARD_TYPE_GENERIC_BASE`, instead use a card driver specific define. (`card-rtecp.c` already contains this problem for the other cards, I know).

OK.

**Comment by dfortinskiy** [comment]
> don't use `SC_CARD_TYPE_GENERIC_BASE`, instead use a card driver specific define. (`card-rtecp.c` already contains this problem for the other cards, I know).

In https://github.com/OpenSC/OpenSC/pull/1721.

**Comment by frankmorgner** [comment]
Again, I think it's a bit overkill to create a new card driver. Please check out https://github.com/OpenSC/OpenSC/pull/1728 if it works with your card.

**Comment by dfortinskiy** [comment]
> Again, I think it's a bit overkill to create a new card driver. 

Sure.
> Please check out #1728 if it works with your card.

This one is even better!

Close this MR?

**Pull request closed without merging**
