### PR TITLE
Fix the javacard CI and make it more robust against future failures

### LINKED ISSUE #2028: javacard simulation CI target broken
### Problem Description

Recently, all builds using javacard simulation fail to run PivApplet. I started investigating what is going on and it turns out (after unrolling the raw log in travis), that the build of PivApplet fails since some changes in upstream repository
```
BUILD FAILED
/home/travis/build/Jakuje/OpenSC/PivApplet/build.xml:66: Compile failed; see the compiler error output for details.
```
Investigating further, it looks like also the build of `yubico-piv-tool` fails later:
```
ykcs11.c:1838:5: error: â€˜forâ€™ loop initial declarations are only allowed in C99 mode
     for (CK_ULONG j = 0; j < ulCount; j++) {
     ^
make[2]: *** [ykcs11.lo] Error 1
make[2]: Leaving directory `/home/travis/build/Jakuje/OpenSC/yubico-piv-tool/ykcs11'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/Jakuje/OpenSC/yubico-piv-tool/ykcs11'
make: *** [install-recursive] Error 1
travis_time:end:2ae5cfef:start=1588869529247751602,finish=1588869598104316046,duration=68856564444,event=before_script
```
But both of these failures are ignored and we see only the failure of the jcardsim to start the applet.

The javacard simulation runs on oldes Ubuntu (14.04) -- the rest was already migrated to bionic (18.04). I did not update last time, because the jcardsim was not able to build with anything newer. There are some commits in https://github.com/arekinath/jcardsim which allow me to build it on my Fedora, but it still fails on Ubuntu for unknown reasons.

I put together few commits in the way to address this issue, but can not continue fiddling with that right now so if somebody would like to continue, feel free to do so:

https://github.com/Jakuje/OpenSC/commits/travis-kill

For others, this is a note that the javacard tests are broken now and its not your code that broke it :)

### PR DESCRIPTION
**Pull request by Jakuje**
Fixes #2028. 

This pull request updates the CI runner for javacard emulation to more current Ubuntu version (to have sensible compiler and openssl version to build yubico-piv-tool), but keeping the old Java version as jcardsim looks like having some issues with new Java 11. It also handles better the pcscd by stopping the service (which can exit any time) and starting pcscd manually.

##### Checklist
[X] CI only PR

### CODE REVIEW

**Comment by Jakuje** [comment]
The failing target is now the osx one. Could this be the issue?
```
+xcodebuild -target NotificationProxy -configuration Release -project NotificationProxy/NotificationProxy.xcodeproj install DSTROOT=/Users/travis/build/OpenSC/OpenSC/target/Library/OpenSC/ '' OTHER_CODE_SIGN_FLAGS=--timestamp CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO CODE_SIGN_STYLE=Manual

Build settings from command line:

    CODE_SIGN_INJECT_BASE_ENTITLEMENTS = NO

    CODE_SIGN_STYLE = Manual

    DSTROOT = /Users/travis/build/OpenSC/OpenSC/target/Library/OpenSC/

    OTHER_CODE_SIGN_FLAGS = --timestamp

xcodebuild: error: Unknown build action ''.
```
Seems like a change introduced in e71b8586 by @frankmorgner when it is build from PR and I do not have access to secrets to decode the keys?

**Comment by Jakuje** [comment]
Right, this variable comes from the repositotory settings:
```
$ export CODE_SIGN_IDENTITY=[secure]
```
I am not sure if excluding this variable will work for signing, it will be skipped or fail someplace later, but let me investigate.

**Comment by Jakuje** [comment]
@frankmorgner The current version kind of works for build, but fails to install (because of missing signing key. Is this something that can be worked around for development builds or really everything needs to be signed with something? Then we would have to disable the osx builds on PR or skip the install.

**Comment by frankmorgner** [comment]
Sigh, it was quite challenging to get this code signing automated in the first place. Let's merge your changes and I'll try to fix the code signing in a seperate PR.

**Pull request merged**
