### PR TITLE
allow single character strings with sc_hex_to_bin

### PR DESCRIPTION
**Pull request by frankmorgner**
fixes https://github.com/OpenSC/OpenSC/issues/1684
fixes https://github.com/OpenSC/OpenSC/issues/1669

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [x] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by szszszsz** [comment]
Hi!

Are there any build artifacts for this PR? I tried https://github.com/OpenSC/Nightly, but could not find them. I remember these were published on the AppVeyor some time ago, for each build.

**Comment by frankmorgner** [comment]
https://ci.appveyor.com/project/LudovicRousseau/opensc/build/job/ka2wdgpx3av0tjuv
https://ci.appveyor.com/project/LudovicRousseau/opensc/build/job/68flfgqylsc2uav2

**Comment by szszszsz** [comment]
There are no artefacts there, unless I am missing something:
https://ci.appveyor.com/project/LudovicRousseau/opensc/build/job/68flfgqylsc2uav2/artifacts

**Comment by frankmorgner** [comment]
Hmm, looks like the deploy phase isn't executed for PRs. I've updated the config accordingly so that a msi is pushed again.

**Comment by frankmorgner** [comment]
Should soon appear here https://ci.appveyor.com/project/LudovicRousseau/opensc/builds/24893884/job/y2b2lunieq7ep8q2/artifacts

**Pull request merged**
