### PR TITLE
Use explicit locking for OpenSC tools

### LINKED ISSUE #1043: opensc-explorer does not verify PIN on Windows 8.1
### Expected behaviour
PIN should be verified correctly while using opensc-explorer tool.

### Actual behaviour

Error message is shown: 
```
Unable to verify PIN code: Transmit failed
```
Issue is not occurring on Ubuntu 16.10 with OpenSC 0.16.

#### Preconditions:
Admin PIN set to `12345678`
OS: Windows 8.1 (also reported on Windows 10)
OpenSC build: latest development, No [0.16.0.1243](https://ci.appveyor.com/project/LudovicRousseau/opensc/build/0.16.0.1243)
Nitrokey Pro v0.8
```
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\opensc-tool.exe -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             Nitrokey Nitrokey Pro 0
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\opensc-tool.exe -a
Using reader with a card: Nitrokey Nitrokey Pro 0
3b:da:18:ff:81:b1:fe:75:1f:03:00:31:c5:73:c0:01:40:00:90:00:0c
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\opensc-tool.exe -n
Using reader with a card: Nitrokey Nitrokey Pro 0
CryptoStick v1.2 (OpenPGP v2.0)
```

#### Steps 
1. Run `opensc-explorer`
2. Run ` verify CHV3 3132333435363738`

### Logs

```
PS C:\Program Files\OpenSC Project\OpenSC\tools> ./opensc-explorer -v
OpenSC Explorer version 0.16.0
Using reader with a card: Nitrokey Nitrokey Pro 0
OpenSC [3F00]> verify CHV3 3132333435363738
Unable to verify PIN code: Transmit failed
```

[opensc-explorer_windows8.txt](https://github.com/OpenSC/OpenSC/files/978871/opensc-explorer_windows8.txt)
[opensc-explorer-issue-ubuntu16.10-working.txt](https://github.com/OpenSC/OpenSC/files/978888/opensc-explorer-issue-ubuntu16.10-working.txt)

CC: @jans23

### PR DESCRIPTION
**Pull request by frankmorgner**
fixes #1043 

##### Checklist

- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by mouse07410** [comment]
Would you mind saying what this PR is supposed to accomplish/fix? Is it related to any open issue?

**Comment by frankmorgner** [comment]
as stated above, this fixed #1043

**Comment by mouse07410** [comment]
This PR works on my machines.

**Comment by frankmorgner** [comment]
thanks

**Pull request merged**
