### PR TITLE
CPx: add registration for Windows/minidrivers

### PR DESCRIPTION
**Pull request by vjardin**
Let's OpenSC be able to support the IAS/ECC CPx cards.

Suggested-by: Doug Engert <deengert@gmail.com>

Fix: issue #2321

### CODE REVIEW

**Comment by Jakuje** [comment]
lgtm.

This issue was raised before that we usually update ATRs in the libopensc, but not in the minidriver, which causes these weird issues. I was suggesting we should have some automated check to verify that all the ATR mapping in card drivers are available also in the minidriver, but as I am not a Windows user, it is not high priority for me. I think either simple test in C or bash script that would be executed during `make check` should be fine.

**Comment by frankmorgner** [comment]
Difficult...

1. With ATR masking this could be quite tricky to detect whether a card driver is also registered via Minidriver
2. Most vendors provide a proprietary implementation for Windows, which may be preferred by users. Unfortunately, Windows just picks the first minidriver it sees without letting the user decide which implementation to use.

Making this configuration part of our installer, would be my preferred approach, but I don't currently have time for this...

@vjardin is there a proprietary driver for your card thay may be conflicting with OpenSC?

**Comment by vjardin** [comment]
I agree with @frankmorgner about the checks. I guess some comments into the OpenSC's minidriver code would be a good start.

Yes there is a proprietary driver but I do not understand the issues: anyone can decide not to install OpenSC but get the proprietary one. Of course if both are installed, it becomes an "undefined" state, but it is up to the users that decide to install or not these drivers.

**Review by Jakuje — APPROVED** [review]

**Comment by frankmorgner** [comment]
OK, then let's agree on adding CPx to OpenSC's minidriver configuration.

However, I agree with Doug that Microsoft isn't very verbose regarding the ATR mask. @vjardin did you verify that your comment is actually correct?

**Comment by vjardin** [comment]
Thanks @dengert : how should we proceed ? Should I cut/paste these lines as comments into the `minidriver.c` file ? I feel it is the best option in order to keep some awareness about it.

Or B-plan, what's about adding a section regarding Windows minidriver into the wiki (https://github.com/OpenSC/OpenSC/wiki/Adding-a-new-card-driver) ?

**Comment by dengert** [comment]
Add URL would work.

**Comment by frankmorgner** [comment]
done, thank you

**Comment by vjardin** [comment]
Thanks. Some users will like it ;)

**Pull request merged**
