### PR TITLE
Fixed issues reported by LGTM

### PR DESCRIPTION
**Pull request by frankmorgner**
https://lgtm.com/projects/g/OpenSC/OpenSC

##### Checklist
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by frankmorgner** [comment]
This pull request **fixes 33 alerts** when merging d9bc078eab48580271426a94c2ea758adf8a87c8 into bb6b78937f1b88f753117e8fd4971545123f9fac - [view on LGTM.com](https://lgtm.com/projects/g/OpenSC/OpenSC/rev/pr-ccea47d93752bfb203eaaca8b1fe2947fbb953ba)

**fixed alerts:**

* 25 for Local variable hides global variable
* 3 for Use of potentially dangerous function
* 2 for Missing header guard
* 2 for Comparison result is always the same
* 1 for Multiplication result converted to larger type

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dengert** [comment]
And using "c" or "p" are terrible  choices. "c" is used some 987 times as a variable name usually as a char.
"p" is used some 1527 times, usually as a pointer. 

based on running in libopensc try these yourself: 
```
grep "[^[:alnum:]_\]p[^[:alnum:]_\]" * | wc
grep "[^[:alnum:]_\]c[^[:alnum:]_\]" * | wc
grep "[^[:alnum:]_\]card[^[:alnum:]_\]" * | wc
grep "[^[:alnum:]_\]cert[^[:alnum:]_\]" * | wc

```

**Comment by frankmorgner** [comment]
I've changed the commits to preserve the original names.

**Comment by Jakuje** [comment]
Why there is a check for the Javascript, when there is 0 lines of code in Javascript in OpenSC? Othewise, I like the improvements.

**Pull request merged**
