### PR TITLE
ECDSA-SHA1: Apply SHA1 to input data before PSO compute signature.

### LINKED ISSUE #2181: ECDSA-SHA1 - unable to sign file/wrong signature
### Problem Description

I have a problem to generate/verify ECDSA signature (mechanism ECDSA-SHA1).
I want to sign the file with pkcs11-tool - to get the same result as with openssl:

### Steps to reproduce
On fresh initialized card:
`````
# OpenSSL generate EC key
rm -f tmp/test-key.pem
openssl ecparam -name prime256v1 -genkey -noout -out  tmp/test-key.pem
# extract EC pub key from key bundle
openssl ec -in tmp/test-key.pem -pubout >tmp/test-pub.pem
# generate random data
dd if=/dev/urandom count=1 bs=1000 of=tmp/testfile.txt
# generate signature/ verify signature (openssl)
rm -f tmp/ecdsa.sha1.signature
openssl dgst -sha1   -sign   tmp/test-key.pem -out        tmp/ecdsa.sha1.signature  tmp/testfile.txt
openssl dgst -sha1   -verify tmp/test-pub.pem -signature  tmp/ecdsa.sha1.signature  tmp/testfile.txt
# store key to card
pkcs15-init --store-private-key tmp/test-key.pem --auth-id=1 --pin xxx --label "256" --key-usage sign
# generate signature/ verify signature: (pkcs11-tool)
pkcs11-tool --pin xxx --sign --signature-format "openssl"  -m ECDSA-SHA1 --input-file tmp/testfile.txt --output-file tmp/ecdsa.sha1_pkcs11.signature
openssl dgst -sha1   -verify tmp/test-pub.pem -signature  tmp/ecdsa.sha1_pkcs11.signature  tmp/testfile.txt
`````

For big file (over key size): 

Using slot 0 with a present token (0x0)
Using signature algorithm ECDSA-SHA1
error: PKCS11 function C_SignUpdate failed: rv = CKR_DATA_LEN_RANGE (0x21)
Aborting.

If input file size is < key size:

Using slot 0 with a present token (0x0)
Using signature algorithm ECDSA-SHA1
Verification Failure

### Proposed Resolution
I have found that there is no sha1 applied on input data (probably because wrong register of pkcs11 mechanism).
Fix can be found in https://github.com/OpenSC/OpenSC/compare/master...popovec:fix_ECDSA_SHA but I would like someone to confirm this before I do PR.

### PR DESCRIPTION
**Pull request by popovec**
CKM_ECDSA and CKM_ECDSA_SHA1 cannot be registered in the same way.
We need to use sc_pkcs11_register_sign_and_hash_mechanism ()
for CKM_ECDSA_SHA1.

This fix  also enables more ECDSA-SHAxxx mechanisms in framework-pkcs15.c

Tested: MyEID 4.0.1 (secp256r1 with SHA1, SHA224, SHA256, SHA384, SHA512)

CI tests (Travis + OsEID) for ECDSA-SHAxxx mechanisms are also enabled.
Fixes #2181

##### Checklist
- [x] PKCS#11 module is tested

### CODE REVIEW

**Review by Jakuje — APPROVED** [review]
Looks good. Tested with patch from #2181 and the EC with SHA1 works with my Yubikey as well as with NIST Test PIV card 5.

**Comment by popovec** [comment]
This fix interferes with the functions  of the epass2003 driver. Please do  not merge until  a better solution is found - discusion in #2181.

**Comment by frankmorgner** [comment]
@popovec can we merge this along with https://github.com/OpenSC/OpenSC/pull/2190 or is there still an other problem?

**Comment by popovec** [comment]
> @popovec can we merge this along with #2190 or is there still an other problem? 

#2190 is fine for me, #2190 already contain this PR (as commit 5e5300816c8d49e1334b16062582da83cf149393). 

Thanks.

**Comment by frankmorgner** [comment]
thanks for the feedback! closed with https://github.com/OpenSC/OpenSC/pull/2190

**Pull request closed without merging**
