### PR TITLE
macOS: Use a better Installer and Uninstaller

### PR DESCRIPTION
**Pull request by frankmorgner**
An apple script converted to an App calls the local
/usr/local/bin/opensc-uninstall

### CODE REVIEW

**Comment by frankmorgner** [comment]
Maybe someone else could add some nice icons...

**Comment by metsma** [comment]
You can compile the app build time to avoid apple binaries in source.
osacompile -o MyScript.app MyScript.scpt

**Comment by frankmorgner** [comment]
thanks

**Comment by frankmorgner** [comment]
- fixed compiling the app from source via `build-package`
- fixed `make dist`

- added simplified user interactions during installation

**Pull request merged**
