### PR TITLE
Move to macOS Utilities folder

### PR DESCRIPTION
**Pull request by metsma**
Signed-off-by: Raul Metsma <raul@metsma.ee>

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by Jakuje** [comment]
@frankmorgner can you check this one if it is fine to merge?

**Comment by frankmorgner** [comment]
Isn't this folder reserved for the builtin system utilities?

**Comment by metsma** [comment]
Adobe and friends add also items there and since macOS 10.15 it is separated into 2 folders.
/Applications/Utilities for third party and /System/Applications/Utilities for system readonly folder

**Comment by frankmorgner** [comment]
nice to know :+1: Then we should only install it to Utilities on 10.15 and later, right?

**Comment by metsma** [comment]
You can install previous versions also. Adobe has done so always.
Screenshot 2020-06-23 09 18 20

**Pull request merged**
