### PR TITLE
Mac package

### PR DESCRIPTION
**Pull request by frankmorgner**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by Jakuje** [comment]
lgtm assuming the results will be as in `travis-ci/pr` (without the secure environment variables).

The failure in `travis-ci/push` looks like either picking some wrong environment or failing for other reason?

I see also failures not only in PR, but also in current master:
```
+SIGN_PARAMS='CODE_SIGN_IDENTITY=[secure]'

+OTHER_CODE_SIGN_FLAGS=--timestamp CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO CODE_SIGN_STYLE=Manual

./MacOSX/build-package: line 29: OTHER_CODE_SIGN_FLAGS=--timestamp: command not found
```
Is this PR fixing also these?

https://travis-ci.org/github/OpenSC/OpenSC/jobs/691212703#L5792

**Comment by frankmorgner** [comment]
Yes, this should fix all the build problems. However, the codesign error indicates that the code signing certificate needs to be renewed, sigh.

**Comment by frankmorgner** [comment]
Code signing works as expected. Now it's again the javacard simulation, that fails 🙄

**Comment by Jakuje** [comment]
But CI in master failed and is finally green again. I assume it is just flaky.

**Pull request merged**
