### PR TITLE
Prep openssl 1.1 v2 

### PR DESCRIPTION
**Pull request by dengert**
This is a replacement for #654  but based on v0.16.0-rc. The bulk of the commits have been sguashed into 1 large commit. The first (small one) could be committed today, the second could wait till OpenSSL-1.1.0 is released. 

I believe I have addressed all the comments in #654 

I am looking for additional comments, ans there are a lot of changes.

### CODE REVIEW

**Comment by viktorTarasov** [comment]
> 8f28dcd 	Handle C and C++ "inline" and "restrict" keywords for various compilers

I still do not understand, what is the benefit from using _restrict_ and _inline_ modifiers in software to manage smart cards.

I propose to eliminate all occurrences of these modifiers, including _simclist_.
"Simclist -- advanced techniques for improving performance of lists handling". What for? To handle few short lists: slots, sessions, readers, objects ?

**Comment by dengert** [comment]
As I said in https://github.com/OpenSC/OpenSC/commit/8f28dcd7b71754675e2ecbe6bc5a5548d2ef2849 
: "(Another option is to just remove all inline and restrict keywords from OpenSC code.)"

There is not much to be gained in performance.
I would still keep simclist just without the inline and restrict keywords and without the tests to set them.

0.16.0 should at least address the issue. Either by doing a better job of handling the keywords, or
not use the keywords at all.

If we chose to eliminate the keywords, we may in the future run it to the issue if new code is added
that uses them. That is why I added https://github.com/OpenSC/OpenSC/commit/8f28dcd7b71754675e2ecbe6bc5a5548d2ef2849

**Comment by viktorTarasov** [comment]
@dengert sorry, have not seen.

8f28dcd applied to _0.16.0_.

**Comment by dengert** [comment]
Now that OpenSSL-1.1.0-pre5 is released, I am going to close this PR, and open a new PR with these mods and additional mode that are required by OpenSSL-1.1.0-pre5

**Comment by dengert** [comment]
Replaced by #861. OpenSSL-1.1.0 has been released.

**Pull request closed without merging**
