### PR TITLE
Fix issues #335 and #336, missing commits

### PR DESCRIPTION
**Pull request by tc-anssi**
Hi,

Regarding the two issues mentioned in the title, it seems two commits were missing from my previous pull requests.
The first missing commit enables the PKCS#11 compliance improvements otherwise `access_flags` is not read.
The second commit is related to `access_flags` for IAS-ECC cards.

Sorry I missed that!

Cheers.

### CODE REVIEW

**Comment by viktorTarasov** [comment]
Agree with  <i>Improve PKCS#11 compliance</i>  (917653a).

Do not agree with <i>IAS-ECC: improve PKCS#11 compliance</i> ( 0d58595),
look my comment to #336.

**Comment by tc-anssi** [comment]
Hi Viktor,

I re-read your comment on #336 and I have to disagree with your interpretation of CKA_ALWAYS_SENSITIVE and CKA_NEVER_EXTRACTABLE.

Let's take for instance the C_CreateObject() function, the standard states (>=v2.20):
> If C_CreateObject is used to create a key object, the key object will have its
> CKA_LOCAL attribute set to CK_FALSE. If that key object is a secret or private key
> then the new key will have the CKA_ALWAYS_SENSITIVE attribute set to
> CK_FALSE, and the CKA_NEVER_EXTRACTABLE attribute set to CK_FALSE.

Therefore, the value of those two attributes depends on the type of operation that was used to "instantiate" the object.

Now, the two attributes can safely be set to CK_TRUE when the key is generated on-board since OpenSC does not allow wrapping operations. This is what I did with (0d58595).

**Comment by viktorTarasov** [comment]
> I re-read your comment on #336 and I have to disagree with your interpretation of
> CKA_ALWAYS_SENSITIVE and CKA_NEVER_EXTRACTABLE.


You have a reason.
Thank you.

**Comment by viktorTarasov** [comment]
Applied in 4915eaa56b4e81346e1696b2cb38a0f2df14db5b and bbedd4ef00bf457fdf11be7899c64579248885e1,
thank you.

**Comment by dengert** [comment]
On 1/5/2015 6:17 AM, Thomas Calderon wrote:
> Hi Viktor,
>
> I re-read your comment on #336 <https://github.com/OpenSC/OpenSC/issues/336> and I have to disagree with your interpretation of CKA_ALWAYS_SENSITIVE and CKA_NEVER_EXTRACTABLE.
>
> Let's take for instance the C_CreateObject() function, the standard states (>=v2.20):
>
>     If C_CreateObject is used to create a key object, the key object will have its
>     CKA_LOCAL attribute set to CK_FALSE. If that key object is a secret or private key
>     then the new key will have the CKA_ALWAYS_SENSITIVE attribute set to
>     CK_FALSE, and the CKA_NEVER_EXTRACTABLE attribute set to CK_FALSE.
>
> Therefore, the value of those two attributes depends on the type of operation that was used to "instantiate" the object.
>
> Now, the two attributes can safely be set to CK_TRUE when the key is generated on-boardsince OpenSC does not allow wrapping operations.

I agree with the conclusion, if the token enforces not reading a key that was generated on the card, but disagree with the logic:
"since OpenSC does not allow wrapping operations.". The attribute has to do with the token not with the middle-ware
currently accessing the token. If the IAS/ECC card do wrapped extraction, even if OpenSC does not support wrapping,
then the CKA_NEVER_EXTRACTABLE should be false.


If the OpenSC code has to determine what the attribute should be, other then reading it from the token,
then it maybe guessing at what the card issuer actually did, for example escrowing a key,
or generating the key off the card, and writing it to the card using some card vendor commands
that may not be documented. So some of these attributes may depend on the policies of the
card issuer.

So what can the IAS/ECC token do?
What can a card issuer set?
What attributes of access flags can be read from the token?



This is what I did with (0d58595
> <https://github.com/OpenSC/OpenSC/commit/0d585952541e6667c08ad4ae6accc1f5e17766fb>).
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/348#issuecomment-68700801>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by viktorTarasov** [comment]
Thomas cited the PKCS11 standard:
 >    If C_CreateObject is used to create a key object, the key object will have its
>     CKA_LOCAL attribute set to CK_FALSE. If that key object is a secret or private key
>     then the new key will have the CKA_ALWAYS_SENSITIVE attribute set to
>     CK_FALSE, and the CKA_NEVER_EXTRACTABLE attribute set to CK_FALSE.

My updated IMHO:
these three attributes are related to the hole key history;
in this logic they are set to FALSE when object is created with C_CreateObject 
(once upon a time the key material was outside the card).

Other two attributes
CKA_EXTRACTABLE and CKA_SENSITIVE are related to the current object state or token capacity.
For IAS/ECC card private key cannot be revealed off card; so these attributes are set to FALSE and TRUE.

**Pull request closed without merging**
