### PR TITLE
Update Security policy to match current practices

### PR DESCRIPTION
**Pull request by Jakuje**
I do not know how exactly the workflow looks for non-owner, but this is taken from the pkcs11-provider security policy, where you get a choice to report security issue after clicking to "New Issue".

##### Checklist

- [X] Documentation is added or updated

### CODE REVIEW

**Comment by tomato42** [comment]
I see in the Security tab that there's an option to file a private security bug, wouldn't it be better to recommend use of those?

**Comment by Jakuje** [comment]
> I see in the Security tab that there's an option to file a private security bug, wouldn't it be better to recommend use of those?

Do you have a screenshot how it looks from your side? For me the Security tab has all the configuration and no button to report security vulnerability.

**Comment by frankmorgner** [comment]
grafik

**Comment by Jakuje** [comment]
Thanks. I was not expecting the button will be there for not logged in users. Updated.

**Review by tomato42 — APPROVED** [review]

**Pull request merged**
