### PR TITLE
Minor code quality improvements to fix  in relation to #412

### PR DESCRIPTION
**Pull request by vletoux**
Hi,

As requested here my contribution to fix a few code analysis warnings.
Indeed, it is difficult to test it but the modifications are minor and they may be checked using a code review.

regards,
Vincent LE TOUX

### CODE REVIEW

**Comment by vletoux** [comment]
The Travis compilation failed like yesterday (without a compilation error). I'll wait a few hours and do a commit to force a recompilation as suggested by Frank.

**Comment by frankmorgner** [comment]
looks good, thank you.

**Comment by frankmorgner** [comment]
I'm waiting for a second opinion, especially on the conflict resolution for the minidriver (which I can't test).

**Comment by dengert** [comment]
See @viktorTarasov  comments on #426

**Comment by viktorTarasov** [comment]
MD changes shortly tested (certutil, generate key, import cert, authentication in IE) on Vista 32 bit.

Applied in 8ea328ff7fb311e582f312fe4f145c1af0d52390,
thank you.

**Pull request closed without merging**
