### PR TITLE
Run 32b builds on Fedora

### PR DESCRIPTION
**Pull request by Jakuje**
The Ubuntu images are pretty much broken every other week in regards to the installation of 32b arch packages because this is not supported by the ppa's that are pushed to the GA images.

As this was underway, I did run normal build on Fedora too and fixed some test issues that I encountered.

Based on the suggestion in https://github.com/OpenSC/OpenSC/pull/2661#issuecomment-1404208313

### CODE REVIEW

**Comment by dengert** [comment]
I too have been looking at setup-linux.sh 
The build-ix86 fails. But the build-mingw and build-mingw32 so I reordered a few thing in:

https://github.com/OpenSC/OpenSC/pull/2053/commits/812cfcfd58feb6010dd95920d6b5d664b120dc4c

See https://github.com/OpenSC/OpenSC/pull/2053 which is still waiting for test-cac and  appveyor

The other surprising this is I don't see where the buil-ix86 is actually used.

Also note some jobs use

**Comment by Jakuje** [comment]
> I too have been looking at setup-linux.sh
> The build-ix86 fails. But the build-mingw and build-mingw32 so I reordered a few thing in:

> https://github.com/OpenSC/OpenSC/commit/812cfcfd58feb6010dd95920d6b5d664b120dc4c

> See https://github.com/OpenSC/OpenSC/pull/2053 which is still waiting for test-cac and appveyor

Thanks. This looks also good. Hopefully it will keep working for some time. I can pull also this commit and skip the removal of the build-ix86.

> The other surprising this is I don't see where the buil-ix86 is actually used.

Its just used to try to build for 32b arch. It does not have any other use similarly as many other targets.

**Comment by frankmorgner** [comment]
can `build-ix86` then be removed from `.github/workflows/linux.yml`?

**Comment by Jakuje** [comment]
> can `build-ix86` then be removed from `.github/workflows/linux.yml`?

that was my initial attempt, but @dengert in the meantime fixed the build again (I included his commit) so I just kept the fedora targets as they are hopefully simple enough to be stable.

**Comment by Jakuje** [comment]
I see the recent builds work ok again (for example on master) even without these changes as GH probably reverted the problematic changes, but all of these changes should make gradual improvement, even though we are not sure if they are addressing the specific issue (but we can expect similar issues happening from time to time again).

**Comment by dengert** [comment]
One additional  question.  In .github/workflows/linux.yml  

- all the jobs that run on "ubuntu-20.04" use the actions/*@v2
- all the jobs that run on  " ubuntu-22.04" use the actions/*@v3
- most of the jobs that use "ubuntu-latest" use the actions/*@v3 (looks like the newest ones)
- But jobs build-no-shared, build-ix86, build-mingw,  build-mingw32 all use "ubuntu-latest"  with actions/*@v2 (these appear to be older)
- "ubuntu-latest" is  "22.04.1" today

Should  build-no-shared, build-ix86, build-mingw,  build-mingw32 be using  actions/*@v3 ?

**Comment by Jakuje** [comment]
> Should build-no-shared, build-ix86, build-mingw, build-mingw32 be using actions/*@V3 ?

Probably yes, but I did not want to mix more changes in this PR. It should be no problem to update to V3 everywhere, I believe.

**Review by frankmorgner — APPROVED** [review]

**Pull request merged**
