### PR TITLE
Run Windows CI on Github Actions

### PR DESCRIPTION
**Pull request by metsma**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by metsma** [comment]
I moved Appveyor build 1 to 1 github.
@frankmorgner Can you please add signpath.
I left only 2019 and 2022 VC

**Review by frankmorgner — COMMENTED** [review]
Thank you very much for taking your time and making this work!

This PR removes AppVeyor entirely. (I am not against this step, I just want to highlight this explicitly.)

As the metadata for instructing some CI runner to do things changes from platform to platform, we have chosen in the other workflow files for Github Actions to put most of the commands into scripts in the `.github` folder. Would it be possible to do the same with the Windows commands, e.g. as powershell scripts? This approach would be more flexible if we need to switch away from Github some day.

You have also simplified [OpenSC.wxs.in](https://github.com/OpenSC/OpenSC/pull/3251/files#diff-a143744d1ceaef543502b75259cf9f9e7d91e91d558039a167a8c29d61ee0213). Did you test if local builds on a 64 bit platform still support building the 32 bit installer?

You are very generous of including new build dependencies (lukka/run-vcpkg@v7, ilammy/msvc-dev-cmd@v1, msys2/setup-msys2@v2, proudust/gh-describe@v2) for things that previously have been done with small sniplets. I am a bit sceptical of this approach as it adds an attack vector to the build infrastructure. (Also, having dedicated build scripts for the runner as suggested above, those dependencies might not be needed anymore.) Do other @OpenSC/maintainers have an opinion about this?

**Comment by metsma** [comment]
> Thank you very much for taking your time and making this work!
> 
> This PR removes AppVeyor entirely. (I am not against this step, I just want to highlight this explicitly.)

I left this for now

> As the metadata for instructing some CI runner to do things changes from platform to platform, we have chosen in the other workflow files for Github Actions to put most of the commands into scripts in the `.github` folder. Would it be possible to do the same with the Windows commands, e.g. as powershell scripts? This approach would be more flexible if we need to switch away from Github some day.

I really don't want invest to much time for this because most the complexity can be solved with meson build system.

> You have also simplified [OpenSC.wxs.in](https://github.com/OpenSC/OpenSC/pull/3251/files#diff-a143744d1ceaef543502b75259cf9f9e7d91e91d558039a167a8c29d61ee0213). Did you test if local builds on a 64 bit platform still support building the 32 bit installer?

I reverted this to make follow up PR for switching to WIX 5. The change did not affect the 32 build only cleanup wix code.

> You are very generous of including new build dependencies (lukka/run-vcpkg@v7, ilammy/msvc-dev-cmd@v1, msys2/setup-msys2@v2, proudust/gh-describe@v2) for things that previously have been done with small sniplets. I am a bit sceptical of this approach as it adds an attack vector to the build infrastructure. (Also, having dedicated build scripts for the runner as suggested above, those dependencies might not be needed anymore.) Do other @OpenSC/maintainers have an opinion about this?

Like I said most of the helpers are for autotools bootstraping.
Only one is lukka/run-vcpkg@v7 that is for building OpenSSL with vcpkg and it uses caching for github actions.

**Review by frankmorgner — CHANGES_REQUESTED** [review]
AppVeyor is reporting the following problem:
```
C:\projects\opensc\win32\OpenSC.wxs(30) : error CNDL0265 : The Platform attribute has an invalid value X64.  Possible values are x86, x64, or ia64.
```
Could you try changing this to `x64`, which may be compatible between different versions of wxs

**Comment by metsma** [comment]
> AppVeyor is reporting the following problem:
> 
> ```
> C:\projects\opensc\win32\OpenSC.wxs(30) : error CNDL0265 : The Platform attribute has an invalid value X64.  Possible values are x86, x64, or ia64.
> ```
> 
> Could you try changing this to `x64`, which may be compatible between different versions of wxs

Resolved

**Pull request merged**
