### PR TITLE
Fixes build error in opensc-notify (issue #2068).

### PR DESCRIPTION
**Pull request by misterzed88**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by Jakuje** [comment]
Can you check/share your `config.log` before this change, where is the `-lpthread` mentioned and generated Makefile (in src/tools/) in your case?

For me (on Fedora), `-lpthread` comes from pkgconfig's `GIO2_CFLAGS`, which are already in the notify CFLAGS.

**Comment by misterzed88** [comment]
On 7/1/20 3:07 PM, Jakub Jelen wrote:
> Can you check/share your |config.log| before this change, where is the 
> |-lpthread| mentioned and generated Makefile (in src/tools/) in your case?
> 
> For me (on Fedora), |-lpthread| comes from pkgconfig's |GIO2_CFLAGS|, 
> which are already in the notify CFLAGS.

My GIO2_CFLAGS from configure is empty:
GIO2_CFLAGS=''

Which is no surprise since my system does not have GIO installed. Quote 
from config.log:
configure:20258: $PKG_CONFIG --exists --print-errors "gio-2.0"
Package gio-2.0 was not found in the pkg-config search path.

I am running the following distro (lsb-release -da), installed with 
Qubes OS:
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch

So this explains why the CI build works while my build breaks. (It is 
really nice to go to the bottom of a problem to fully understand what's 
happening.)

Since gio-2.0 lib availibility is optional in the OpenSC build, notify 
should not rely on it to provide the pthread lib option (which would be 
an indirect dependency, anyway). So the correct solution should still be 
to add the direct dependency as proposed in the PR.

Or what do you think?

Best regards,
Zoltan

**Comment by Jakuje** [comment]
Right. This is a good solution for now.

On the other hand, the opensc-notify is app designated only to show notification in gui and if there is no GUI library (GIO on Linux) available, it basically does not do anything. I would argue that id there was `--disable-notify` configure switch or the GUI dependencies were not found, the `opensc-notify` tool should not build at all, but not sure if it would be more or less confusing than the current situation. What do you think @frankmorgner ?

**Comment by frankmorgner** [comment]
... interesting I've just checked the generated Makefile. It looks like AM_CFLAGS (which contains -lpthread) is not used once we specify `opensc_notify_CFLAGS`. This doesn't show up in CI, because opensc-notify is linked to libgio, which also requires pthread.

Note that in your case, where libgio is not found, opensc-notify gets built with your change, but it should never emit any notification...

**Comment by frankmorgner** [comment]
Oh... and yes, disabling opensc-notify in this case, would be good from a user's perspective

**Pull request merged**
