### PR TITLE
improvements to opensc-explorer & new tool openpgp-tool

### PR DESCRIPTION
**Pull request by marschap**
Please consider pulling these commits into opensc/staging.

### CODE REVIEW

**Comment by arrowd** [comment]
Sorry for bumping this old PR, but where do all the magic numbers of this table

```
	{ "Account",  "OPENGPG_ACCOUNT", "3F00:005E",      NULL       },
	{ "URL",      "OPENPGP_URL",     "3F00:5F50",      NULL       },
	{ "Name",     "OPENPGP_NAME",    "3F00:0065:005B", NULL       },
	{ "Language", "OPENPGP_LANG",    "3F00:0065:5F2D", prettify_language },
	{ "Gender",   "OPENPGP_GENDER",  "3F00:0065:5F35", prettify_gender   },
```

come from? Is this some standard or an internal implementation detail if OpenSC?

**Comment by arrowd** [comment]
Yep, already found it: https://gnupg.org/ftp/specs/openpgp-card-1.1.pdf

Thank you for the reply!

**Comment by dengert** [comment]
Look at newer version https://gnupg.org/ftp/specs/OpenPGP-smart-card-application-3.4.pdf
You can also use opensc-explorer  to look at the file structures.

**Comment by arrowd** [comment]
Since I got your attention and you mentioned `opensc-explorer`, can you help me with this:

```
OpenSC [3F00]> put 005e
3F00_005E: No such file or directory
```

According to the standard,

> Login data, max. 254 bytes (binary, proprietary)
This DO can be used to store any information used for the
Log-In process in a client/server authentication (e.g. user
name of a network).

I was hoping to put some data into this EF. It shows up in the `ls` output:

```
OpenSC [3F00]> ls
FileID  Type  Size
[00FA]    DF   142
 004F    wEF    16
 005E    wEF     0
...
```

**Comment by dengert** [comment]
I am not very good with opensc-explorer. 
 You may have to login i.e. verify command See: "Access conditions for Data Objects" 

"If the card is delivered without personalisation and/or PW letter, then a default content is
assumed (UTF-8): PW1 = “123456” (6 bytes, 313233343536); PW3 = “12345678” (8
bytes, 3132333435363738). After a card reset, these values are restored also."

**Comment by arrowd** [comment]
It worked with

```
OpenSC [3F00]> update_binary 005e 0 "asd"
Total of 3 bytes written to 005E at offset 0.
```

Thanks for your time, anyways!

**Pull request merged**
