### PR TITLE
SECURITY.md: Introduce security reporting process

### PR DESCRIPTION
**Pull request by Jakuje**
As part of CII Best Practices evaluation, there is a step for making sure we have documentation how to report security vulnerabilities. Github proposes the `SECURITY.md` to do that. I tried to fill their template, but I would like to hear if it reflects previously used processes, if there is something to change or improve in this direction.

https://bestpractices.coreinfrastructure.org/en/projects/3908/

### CODE REVIEW

**Comment by Jakuje** [comment]
I would like also others members to review the questionnaire (everyone with commit access here should be able to update it), whether they see some space for improvement, if I missed something or there is something to add. After having the security process,I believe we will have the checklist complete and we can add the badge.

**Comment by dengert** [comment]
"It is SUGGESTED that the test suite cover most (or ideally all) the code branches, input fields, and function"

very large code base and poor testing history makes this hard to achieve yet.

Could also say project does not have all smart cards for testing. And not able to tell if cards are still being used.

**Comment by Jakuje** [comment]
> "It is SUGGESTED that the test suite cover most (or ideally all) the code branches, input fields, and function"
> 
> very large code base and poor testing history makes this hard to achieve yet.
> 
> Could also say project does not have all smart cards for testing. And not able to tell if cards are still being used.

Thanks for suggestion. I added that part.

**Comment by frankmorgner** [comment]
thank you!

**Pull request merged**
