### PR TITLE
[pkcs11-tool] CKO display serial number

### PR DESCRIPTION
**Pull request by AlexandreGonzalo**
I am using the pkcs11-tool to list the certificates stored in my PKCS#11 token.
I have this patch which displays the certificate serial number and maybe that's something which could be merged to master.

Certificate Object; type = X.509 cert
  subject:    DN: C=FR, ST=PACA, L=Valbonne, O=Trustonic, CN=*.trustonic.com
  serial:     54E67E7F3DB8F07D11D473717C71E057FD7D22C9
  ID:         01

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by frankmorgner** [comment]
can we do this without being dependant on OpenSSL?

**Comment by Jakuje** [comment]
can you rebase the changes on current master to remove the needless commits (adding support for SHA3, merge commits)?

**Comment by AlexandreGonzalo** [comment]
> I am using the pkcs11-tool to list the certificates stored in my PKCS#11 token. I have this patch which displays the certificate serial number and maybe that's something which could be merged to master.
> 
> Certificate Object; type = X.509 cert subject: DN: C=FR, ST=PACA, L=Valbonne, O=Trustonic, CN=*.trustonic.com serial: 54E67E7F3DB8F07D11D473717C71E057FD7D22C9 ID: 01



> can you rebase the changes on current master to remove the needless commits (adding support for SHA3, merge commits)?

I created this new PR
https://github.com/OpenSC/OpenSC/pull/2641

**Comment by AlexandreGonzalo** [comment]
> 



> can we do this without being dependant on OpenSSL?

I did the same as getSUBJECT() above and it is an easy win.
I don't think that it is worth to try to avoid OpenSSL.

**Pull request closed without merging**
