### PR TITLE
travis.yml - install socat and ant packages.

### LINKED ISSUE #1745: The GitHub CI automated checks are broken
The CI jobs are failing probably due to missing configuration/setup. See the last two PR's.

### PR DESCRIPTION
**Pull request by popovec**
Fixes #1745

### CODE REVIEW

**Comment by popovec** [comment]
This is not opensc bug, can someone fix this? 

https://api.travis-ci.org/v3/job/559891315/log.txt

Compiling 95 source files to /home/travis/build/OpenSC/OpenSC/jcardsim/target/classes
COMPILATION ERROR : 
error: Source option 5 is no longer supported. Use 6 or later.
error: Target option 1.5 is no longer supported. Use 1.6 or later.

**Comment by popovec** [comment]
`dist: trusty` in .travis.yml can help fix this issue. Is this acceptable ?

**Comment by frankmorgner** [comment]
Yes, please add `dist: trusty` in the matrix where the simulation is done.

**Comment by popovec** [comment]
Fixed, travis CI is now working - all on Ubuntu 16.04.6 LTS, except javacard simulation - it is still running on Ubuntu 14.04.5 LTS

**Comment by frankmorgner** [comment]
thanks

**Pull request merged**
