### PR TITLE
OpenSSL 1.1.1 is deprecated

### PR DESCRIPTION
**Pull request by metsma**
##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [x] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by frankmorgner** [comment]
I think it would be good to schedule this when after the upcoming version was released.

I agree with the suggested change, although I'd like to note that extended support for 1.1.1 is [still available](https://www.openssl.org/policies/releasestrat.html)

**Comment by metsma** [comment]
> I think it would be good to schedule this when after the upcoming version was released.
> 

I agree

> I agree with the suggested change, although I'd like to note that extended support for 1.1.1 is [still available](https://www.openssl.org/policies/releasestrat.html)

Thats why I did not touch configure script. It is still possible build with 1.1.1. But default build should produce "suppored" binary

**Comment by frankmorgner** [comment]
Agreed. [Our AppVeyor configuration ](https://github.com/OpenSC/OpenSC/blob/master/.appveyor.yml)should be changed to use the [pre installed 3.0 version ](https://www.appveyor.com/docs/windows-images-software/)as well then.

**Comment by metsma** [comment]
Huh haven't used AppVeyor recently. Is there reason that OpenSC does not use GitHub Actions windows environments?

**Comment by frankmorgner** [comment]
1. We're using AppVeyor for historical reasons
2. My long term plan is to integrate [Signpath](https://github.com/OpenSC/OpenSC/pull/2799), which currently doesn't support GHA

**Comment by Jakuje** [comment]
@metsma can you please rebase so we can re-triger the CI and make sure everything works before merging? Release is out so I would like to give this some more testing.

**Comment by metsma** [comment]
Done

**Comment by Jakuje** [comment]
Looking at the https://www.openssl.org/source/ I am wondering if we should keep the 3.0 or jump to 3.2 directly, which is latest stable.

**Review by Jakuje — APPROVED** [review]

**Comment by frankmorgner** [comment]
I think it is better to stick to the LTS version.

**Pull request merged**
