### PR TITLE
After a fork do not release resources shared with parent

### PR DESCRIPTION
**Pull request by frankmorgner**
This PR implements the second option proposed in https://github.com/OpenSC/OpenSC/pull/493#issuecomment-121917436 . I hope my approach is a bit cleaner and more complete than what is proposed in #493. Everything works as expected with a CardOS card and `pkcs11-tool --test-fork --login --test`

### CODE REVIEW

**Comment by frankmorgner** [comment]
@nmav what do you think?

**Comment by nmav** [comment]
I haven't checked yet. I just returned from holidays. I'll try to find out some time and check it.

**Comment by nmav** [comment]
That patch looks simpler and cleaner than 493. As of memory leaks these remain, but as I said in 493 they should be treated as a separate issue.

**Comment by frankmorgner** [comment]
@nmav thanks for the feedback.

Could you open a separate issue with the missing memory leaks? thank you!

**Comment by nmav** [comment]
On second view, this patch doesn't handle the case where after a fork, C_Finalize() is called (without C_Initialize()). If that happens the same error will occur. I'll open an issue for that.

**Pull request merged**
