### PR TITLE
Fixing some memory leaks in DNIe.

### PR DESCRIPTION
**Pull request by germanblanco**
Please consider this change.
As far as I can test, it produces a clean output with Valgrind as far as DNIe is concerned.
Additional testing by other people will be very much appreciated.

### CODE REVIEW

**Comment by frankmorgner** [comment]
`dnie_transmit_apdu` should not modify the original APDU. This way, a caller is not forced to clean up buffers that are created in the underlying functions. Maybe the implementation of the envelope command from `dnie_wrap_apdu` could be merged into `sc_transmit_apdu` as alternative to chaining...

**Comment by germanblanco** [comment]
Thank you for the review and your comments, @frankmorgner 
I agree with what you say, that would be the way to do it. I would like to take that step as soon as possible.
However, this pull request fixes other memory leaks in the code, and it fixes all memory leaks. If it is ok with you, I would suggest to put this in and leave the code working without memory leaks in an ugly way. Then we can work on moving dnie_wrap_apdu into sc_transmit_apdu. The "free" that we is there now will have to be removed, but that will be a small detail.

**Comment by frankmorgner** [comment]
When do you think, will you look at `dnie_transmit_apdu`? If we start fixing things, we should fix them at the right place. Otherwise we will create confusion and inconsistency.

**Comment by germanblanco** [comment]
I should be able to do that before the end of the year. It will also require some regression test with other cards in order to check that nothing is broken.
Are there any goal dates for the next release already?
If you prefer, I could remove the "free" of apdu->data from this Pull Request and keep the rest.

**Comment by frankmorgner** [comment]
Yes, I'd prefer that. When editing this commit, please also look at the merge conflict, thanks.

**Comment by frankmorgner** [comment]
I added #610 as a reminder

**Pull request closed without merging**
