### PR TITLE
pkcs11-tool: Add extractable option to key import

### PR DESCRIPTION
**Pull request by metsma**
Signed-off-by: Raul Metsma <raul@metsma.ee>

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [X] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by frankmorgner** [comment]
private key objects may also have this attribute, right?

**Comment by frankmorgner** [comment]
@metsma would it make sense to add this attribute to private key objects as well?

**Comment by martinpaljak** [comment]
Yes

**Comment by metsma** [comment]
Added

**Comment by frankmorgner** [comment]
thanks

**Pull request merged**
