### PR TITLE
Add new appveyor image combinations

### PR DESCRIPTION
**Pull request by metsma**
* Use OpenSSL 3.0 in new images
* Use Wix 3.14 in new images
* Update ZLib to 1.3.1

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by metsma** [comment]
If we want minimise the build matrix in Appveyor, we should move least to Visual Studio 2019 image.
Then we have up to date OpenSSL 3.0.
And default build artifacts should come also from this image.

**Comment by frankmorgner** [comment]
I think it is good to test all the different combinations. Having an Github action with Windows now enables developers to quickly see problems on Windows without waiting for every job to complete in AppVeyor.

**Review by frankmorgner — APPROVED** [review]

**Comment by metsma** [comment]
> I think it is good to test all the different combinations. Having an Github action with Windows now enables developers to quickly see problems on Windows without waiting for every job to complete in AppVeyor.

I was thinking more the Appveyor build matrix.
What is the plan next release?
Do we still produce final product from appveyor?
I am worried that Appveyor 2017 image uses deprecated OpenSSL 1.1.1

**Comment by frankmorgner** [comment]
For the release, we can take the newer image, no problem. The signpath hook works for all AppVeyor builds, we only need to select the correct one for release signing in their web front end when requesting the release package

**Pull request merged**
