### PR TITLE
Add missing manual pages and clean up noticed issues

### LINKED ISSUE #2013: Missing manual page for pkcs11-register
### Problem Description

I think all other tools have manual page, but this one is missing.

### Proposed Resolution

create a manual page describing this new tool in 0.20.0, latest before the next release

### Logs
```
$ man pkcs11-register
No manual entry for pkcs11-register
$ pkcs11-register -h
pkcs11-register 0.20.0

Usage: pkcs11-register [OPTIONS]...

Install a PKCS#11 module to known applications.

  -h, --help              Print help and exit
  -V, --version           Print version and exit
  -m, --module=FILENAME   Specify the module to load  (default=`OpenSC's
                            PKCS#11 module')
      --skip-chrome       Don't install module to Chrome  (default=off)
      --skip-firefox      Don't install module to Firefox  (default=off)
      --skip-thunderbird  Don't install module to Thunderbird  (default=off)
      --skip-seamonkey    Don't install module to SeaMonkey  (default=off)

Report bugs to https://github.com/OpenSC/OpenSC/issues

Written by Frank Morgner <frankmorgner@gmail.com>
```

### PR DESCRIPTION
**Pull request by Jakuje**
Partially fixes #2013 and introduces a new check, making sure every new tool has a manual page.

##### Checklist

- [X] Documentation is added or updated

### CODE REVIEW

**Comment by Jakuje** [comment]
> thanks

Please, do not merge (at least the test) yet as it is failing CI. I am not sure if there is some automated way to create the XML from the tools help. I was writing it so far manually, but got lost on the subcommands as I was not sure how to handle these. It would be nice if you could follow up on this. We can probably merge the rest though.

**Comment by frankmorgner** [comment]
- the appveyor problems is unrelated
- the travis problem with cac simulation looks like a concurrency problem, likely unrelated

**Comment by frankmorgner** [comment]
I've restarted the builds

**Comment by Jakuje** [comment]
The CAC build is failing with the new test:
```
FAIL: test-manpage.sh
=====================
goid-tool: missing switch --new-pin
goid-tool: missing switch --new-bio
goid-tool: missing switch --info
goid-tool: missing switch --certificate
goid-tool: missing switch -c
goid-tool: missing switch --key
goid-tool: missing switch -k
goid-tool: missing switch --print-cardid
goid-tool: missing switch --write-cardid
goid-tool: missing switch --print-paccessid
goid-tool: missing switch --write-paccessid
goid-tool: missing switch --read-dg
goid-tool: missing switch --out-file
goid-tool: missing switch --read-dg
goid-tool: missing switch --write-dg
goid-tool: missing switch --in-file
goid-tool: missing switch --write-dg
goid-tool: missing switch --delete-dg
goid-tool: missing switch --create-dg
goid-tool: missing switch --new-size
goid-tool: missing switch --new-read-ac
goid-tool: missing switch --new-read-ac-chatbit
goid-tool: missing switch --new-write-ac
goid-tool: missing switch --new-write-ac-chatbit
Not all the switches in help are documented in manual pages
FAIL test-manpage.sh (exit status: 1)
```
Later on, the CAC test is failing, because opensc was not installed (because test above failed)

**Pull request merged**
