### PR TITLE
Add badges for more cards covered in CI

### PR DESCRIPTION
**Pull request by Jakuje**
I plugged SC-HSM and ePass tokens to my old machine and the CI on gitlab now runs on them. This PR adds them to readme.

Machine is slow so it will take some time to finish (and valgrind will likely fail). The new machine with to test more cards is on the way.

Any ideas what more should be covered in the p11tests appreciated.

##### Checklist
- [X] Documentation is added or updated

### CODE REVIEW

**Review by frankmorgner — APPROVED** [review]

**Review by frankmorgner — APPROVED** [review]

**Comment by Jakuje** [comment]
I did not add a links to the readme, but it should be these two. I will certainly add more full names to the release testing page:
 * https://www.ftsafe.com/store/product/epass2003-pki-token/
 * https://www.cardomatic.de/en/p/smartcard-hsm-4k-usb-token

not sure if we want to link these (or others) from the main page directly.

Before merging, I will probably disable the valgrind jobs.

**Comment by frankmorgner** [comment]
Did you take a look at the reported memory leak?

I would only add the names of the card so that users get a feeling of what was tested. Smart card shops could be listed here https://github.com/OpenSC/Wiki/blob/31d5516dbc01897d573573f437cad501fc29d673/Frequently-Asked-Questions.textile#where-can-i-buy-smart-cards-

**Comment by dengert** [comment]
Amozon.com in US and amazon.co.uk  and maybe other EU countries sells some smart cards too.

**Comment by Jakuje** [comment]
I think this one is ready now too. The ePass is still failing (there is outstanding PR), the SC-HSM should pass now.

**Pull request merged**
