### PR TITLE
minidriver for JPKI

### PR DESCRIPTION
**Pull request by hamano**
Still I got error message "Cannot get User PIN object".
Just a moment please.

### CODE REVIEW

**Comment by hamano** [comment]
I'll test tomorrow!

**Comment by hamano** [comment]
I just succeed to read certificate by certutil -scinfo and certmgr.msc, but failed SSL Client authentication by IE11 and Edge.
Could you give me some advice? @frankmorgner @dengert

**Comment by frankmorgner** [comment]
Certutil is performing private key operations, are they all working? Have a good look on the console output!

Can you confirm with a proprietary minidriver that this should work?

Am 9. Februar 2017 14:22:08 MEZ schrieb HAMANO Tsukasa <notifications@github.com>:
>I just succeed to read certificate by certutil -scinfo and certmgr.msc,
>but failed SSL Client authentication by IE11 and Edge.
>Could you give me some advice? @frankmorgner @dengert
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenSC/OpenSC/pull/964#issuecomment-278638718

-- 
Frank Morgner

**Comment by dengert** [comment]
Use the opensc-debug.log on Windows. 

Use mindriver logging. Read minidriver.c lines 240-270 that include:
```
250 #ifdef CARDMOD_LOW_LEVEL_DEBUG
261     lldebugfp = fopen("C:\\tmp\\md.log","a+");
```
Windows will cache certificates in the cert store, along with info to tell user what card is needed. It needs  unique serial numbers.  You may need to clear out the cert store if you change what serial number is returned. 

The dummy serial number of all zeros may be a big problem.
`1176  * Set 'cardid' from the 'serialNumber' attribute of the 'tokenInfo'`

If the GET DATA APDU (FF CA 00 00) to get UID from card does not work, you may need to use some info from a certificate to derive a serial number. But having the certificates pin protected may not make that possible. (opensc-debug.log would show if the UID could be read.) Also see #810 about FF CA 00 00.

PKCS#11 may work with two PINS each in a different slot.  minidriver may have a problem with the two PINS.

**Comment by frankmorgner** [comment]
Does your card work in minidriver now?

**Comment by frankmorgner** [comment]
@hamano have you enabled the windows service "certificate propagation"?

**Comment by hamano** [comment]
@frankmorgner @dengert 
Hi, Edge is working, but IE11 does not work.
(I'll add screen shot later)
Do you think the issue around driver side?

This is [md.log](https://gist.github.com/hamano/bf42b413d1badbbcf09cab83e423d473) when inserting card.

~~~
pszDirectoryName = mscp, pszFileName = msroots, dwFlags = 0, pcbData=0, *ppbData=0
check_reader_status
pCardData->hSCardCtx:0x00000004 hScard:0x00000000
check_reader_status r=5 flags 0x00000005
MD virtual file system: found 'mscp' directory
CardReadFile(): file 'msroots' not found in 'mscp'
~~~
file 'msroot' was added correctly, but the 'msroots' are not found.

~~~
now read certificate 'Digital Signature Certificate'
certificate '1' read error -1211
cannot find public key
~~~
Digital Signature Certificate is protected by PIN so it is expected behavior.

Any other strange points?
Thank you.

**Comment by hamano** [comment]
> @hamano have you enabled the windows service "certificate propagation"?

Yes, running "certificate propagation"

**Comment by hamano** [comment]
"confirm certificate windows" was popuped, but PIN prompt does not popuped.
I've monitored TLS message in front of WEB server, then I confirmed that IE11 does not sent Certificate message.
It looks like [KB2988411](https://support.microsoft.com/en-us/help/2988411/client-certificate-request-fails-when-tls-1.2-and-1.1-secure-protocols-are-enabled-in-internet-explorer-11), but I definitely updated to latest windows 10.

**Comment by dengert** [comment]
Does the chrome browser work? I believe it can use the minidriver. This would then imply the problem is in IE.

I see in md.log a certificate. Using sed, xxd and openssl x509  it looks like:
```
Certificate:
    Data:
        Version: 3 (0x2)
       Serial Number: 6354692 (0x60f704)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=JP, O=JPKI, OU=JPKI for user authentication, OU=Japan Agency for Local Authority Information Systems
        Validity
            Not Before: Mar  1 16:33:40 2016 GMT
            Not After : Feb 28 14:59:59 2021 GMT
        Subject: C=JP, CN=......
```
I assume that is your user certificate.  But these lines:
```
now read certificate 'Digital Signature Certificate'
certificate '1' read error -1211
cannot find public key
```
implies minidriver is trying to read the certificate from the card to get the public key.
If this fails can you use the certificate from above to get the public key?

**Comment by hamano** [comment]
@dengert Edge and Chrome are working but IE11 doesn't work.

> implies minidriver is trying to read the certificate from the card to get the public key.
> If this fails can you use the certificate from above to get the public key?

We don't use the 'Digital Signature Certificate' for TLS authentication.
It seems sucseed to read 'User Authentication Certificate' and publickey.
see [pkcs15-tool -D](https://gist.github.com/hamano/f7677926a9d57efdc021930e96b3bddb#file-pkcs15-tool-d)

~~~
% pkcs15-tool -r 1 | openssl x509 -issuer -noout
issuer=C = JP, O = JPKI, OU = JPKI for user authentication, OU = Japan Agency for Local Authority Information Systems

% pkcs15-tool -r 2
Certificate read failed: Security status not satisfied

% pkcs15-tool -r 2 -a 2 --verify-pin | openssl x509 -issuer -noout
Please enter PIN [Digital Signature PIN]: 
issuer=C = JP, O = JPKI, OU = JPKI for digital signature, OU = Japan Agency for Local Authority Information Systems
~~~

Thank you.

**Comment by frankmorgner** [comment]
@hamano I'm not sure what the missing bit is, but if you wish we can merge this PR so that at least some applications are working. You could add a wiki article on the known limitations for your card.

**Comment by hamano** [comment]
Thank you for your concern.
Yes, please merge this PR. I'll open another PR around IE11 issue.

I've tested TLS authentication with following platforms:
- Windows 10 Edge
- Windows 10 Google Chrome 56
- Windows 10 Firefox 51
- OS X El Capitan Safari 10
- Ubuntu 16.04 LTS Google Chrome 56
- Ubuntu 16.04 LTS Firefox 51
- Debian 9 Google Chrome 56
- Debian 9 Firefox 51
- Debian 9 Firefox ESR 45

**Pull request merged**
