### PR TITLE
opensc-notify: Fix wrong popup menu popup position

### PR DESCRIPTION
**Pull request by llogar**
If monitor resolution scaling is used, opensc-notify.exe popup menu pops up at the wrong position.

### CODE REVIEW

**Review by frankmorgner — COMMENTED** [review]
Looks good.

If we rely on `EnumDisplaySettings` to be successful, then `info.rcMonitor.right - info.rcMonitor.left` should not be `0`. Do you think it makes sense to test for this anyway in order to prevent a possible devision by zero?

**Comment by llogar** [comment]
I also share the opinion the division by zero shouldn't occur, but I guess one more check doesn't hurt...

**Review by frankmorgner — APPROVED** [review]
thank you

**Comment by Jakuje** [comment]
Thank you for the contribution and reviews! I do not have a way to test it, but I think it is good to go for 0.24.0 unless there would be some concerns against.

**Pull request merged**
