### PR TITLE
Travis OSX integrations

### PR DESCRIPTION
**Pull request by martinpaljak**
So that all changes and pull requests would be build on Travis as well.

### CODE REVIEW

**Comment by martinpaljak** [comment]
As OSX only has clang and no mingw the build machinery should be adjusted slightly. For completeness the Tokend should also be built (maybe OSX "single build file" be split into two steps, building OpenSC + tokend + building the full .dmg?)

**Comment by frankmorgner** [comment]
Could you instead use matrix include to build a speciffic configuration of osx to omit gcc/mingw on osx. Also, you should disable documentation on osx as the requirements are not met.

**Comment by martinpaljak** [comment]
I need to look deeper into the build matrix setup of travis, no experience with that yet. If anyone feels like it, go ahead.

**Comment by frankmorgner** [comment]
unforunately I had the same problem. Its try and error. However, you can always force an update on your branch which also updates this PR. Make sure to test your configuration with http://lint.travis-ci.org/

**Comment by frankmorgner** [comment]
on github you could also search for `filename:.travis.yml ...` for similar solutions.

**Comment by frankmorgner** [comment]
I'll try in #420

**Pull request closed without merging**
