### PR TITLE
Fix some memory leaks

### PR DESCRIPTION
**Pull request by frankmorgner**
I worked through most of the resource leaks reported by Coverity Scan which were mainly due to (non-existing) cleanup in error cases. This is done in one commit per file.

Please test carefully. Thank you!

### CODE REVIEW

**Comment by philipWendland** [comment]
After a successful RSA signing operation with OpenSSL and engine_pkcs11 I get:

```
0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x1)
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x1) 1
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:98:sc_pkcs11_close_session: real C_CloseSession(0xf876c0)
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs15-pin.c:695:sc_pkcs15_pincache_clear: called
0x7fa701373700 23:09:54.390 [opensc-pkcs11] framework-pkcs15.c:1388:pkcs15_release_token: pkcs15_release_token() not implemented
0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x2)
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x2) 0
0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x3)
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x3) 0
0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x4)
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x4) 0
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs15.c:1263:sc_pkcs15_unbind: called
0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs15-pin.c:695:sc_pkcs15_pincache_clear: called
0x7fa701373700 23:09:54.390 [opensc-pkcs11] misc.c:61:sc_to_cryptoki_error_common: libopensc return value: 0 (Success)
0x7fa701373700 23:09:54.390 [opensc-pkcs11] card.c:294:sc_disconnect_card: called
0x7fa701373700 23:09:54.390 [opensc-pkcs11] card-isoApplet.c:142:isoApplet_finish: called
0x7fa701373700 23:09:54.390 [opensc-pkcs11] card-isoApplet.c:148:isoApplet_finish: returning with: 0 (Success)
0x7fa701373700 23:09:54.390 [opensc-pkcs11] reader-pcsc.c:506:pcsc_disconnect: called
0x7fa701373700 23:09:54.467 [opensc-pkcs11] card.c:315:sc_disconnect_card: returning with: 0 (Success)
*** Error in `openssl': free(): invalid pointer: 0x00007fa6ffebcbc0 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x7198e)[0x7fa70075c98e]
/usr/lib/libc.so.6(+0x76dee)[0x7fa700761dee]
/usr/lib/libc.so.6(+0x775cb)[0x7fa7007625cb]
/usr/local/lib/opensc-pkcs11.so(+0xedd0)[0x7fa6ffc99dd0]
/usr/local/lib/opensc-pkcs11.so(+0x9340)[0x7fa6ffc94340]
/usr/local/lib/libp11.so.2(PKCS11_CTX_unload+0x2b)[0x7fa6ffec6694]
/usr/local/lib/engines/engine_pkcs11.so(+0x2450)[0x7fa7000cd450]
/usr/lib/libcrypto.so.1.0.0(engine_unlocked_finish+0x29)[0x7fa700bb9a39]
/usr/lib/libcrypto.so.1.0.0(+0x12c53d)[0x7fa700bba53d]
/usr/lib/libcrypto.so.1.0.0(lh_doall+0x41)[0x7fa700bca3c1]
/usr/lib/libcrypto.so.1.0.0(engine_table_cleanup+0x33)[0x7fa700bba813]
/usr/lib/libcrypto.so.1.0.0(+0x12ac26)[0x7fa700bb8c26]
/usr/lib/libcrypto.so.1.0.0(sk_pop_free+0x31)[0x7fa700bc9921]
/usr/lib/libcrypto.so.1.0.0(ENGINE_cleanup+0x1c)[0x7fa700bb8f2c]
openssl[0x41a133]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fa70070b800]
openssl[0x41a399]
```
(Will investigate more tomorrow)

**Comment by dengert** [comment]
There are some memory leaks, in engine and/or p11. There were two sets of competing patches from a few years ago
that tried to address them.

On 4/30/2015 4:18 PM, Philip Wendland wrote:
> After a successful RSA signing operation with OpenSSL and engine_pkcs11 I get:
>
> |0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x1)
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x1) 1
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:98:sc_pkcs11_close_session: real C_CloseSession(0xf876c0)
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs15-pin.c:695:sc_pkcs15_pincache_clear: called
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] framework-pkcs15.c:1388:pkcs15_release_token: pkcs15_release_token() not implemented
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x2)
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x2) 0
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x3)
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x3) 0
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] slot.c:419:slot_token_removed: slot_token_removed(0x4)
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs11-session.c:126:sc_pkcs11_close_all_sessions: real C_CloseAllSessions(0x4) 0
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs15.c:1263:sc_pkcs15_unbind: called
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] pkcs15-pin.c:695:sc_pkcs15_pincache_clear: called
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] misc.c:61:sc_to_cryptoki_error_common: libopensc return value: 0 (Success)
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] card.c:294:sc_disconnect_card: called
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] card-isoApplet.c:142:isoApplet_finish: called
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] card-isoApplet.c:148:isoApplet_finish: returning with: 0 (Success)
> 0x7fa701373700 23:09:54.390 [opensc-pkcs11] reader-pcsc.c:506:pcsc_disconnect: called
> 0x7fa701373700 23:09:54.467 [opensc-pkcs11] card.c:315:sc_disconnect_card: returning with: 0 (Success)
> *** Error in `openssl': free(): invalid pointer: 0x00007fa6ffebcbc0 ***
> ======= Backtrace: =========
> /usr/lib/libc.so.6(+0x7198e)[0x7fa70075c98e]
> /usr/lib/libc.so.6(+0x76dee)[0x7fa700761dee]
> /usr/lib/libc.so.6(+0x775cb)[0x7fa7007625cb]
> /usr/local/lib/opensc-pkcs11.so(+0xedd0)[0x7fa6ffc99dd0]
> /usr/local/lib/opensc-pkcs11.so(+0x9340)[0x7fa6ffc94340]
> /usr/local/lib/libp11.so.2(PKCS11_CTX_unload+0x2b)[0x7fa6ffec6694]
> /usr/local/lib/engines/engine_pkcs11.so(+0x2450)[0x7fa7000cd450]
> /usr/lib/libcrypto.so.1.0.0(engine_unlocked_finish+0x29)[0x7fa700bb9a39]
> /usr/lib/libcrypto.so.1.0.0(+0x12c53d)[0x7fa700bba53d]
> /usr/lib/libcrypto.so.1.0.0(lh_doall+0x41)[0x7fa700bca3c1]
> /usr/lib/libcrypto.so.1.0.0(engine_table_cleanup+0x33)[0x7fa700bba813]
> /usr/lib/libcrypto.so.1.0.0(+0x12ac26)[0x7fa700bb8c26]
> /usr/lib/libcrypto.so.1.0.0(sk_pop_free+0x31)[0x7fa700bc9921]
> /usr/lib/libcrypto.so.1.0.0(ENGINE_cleanup+0x1c)[0x7fa700bb8f2c]
> openssl[0x41a133]
> /usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7fa70070b800]
> openssl[0x41a399]
> |
>
> (Will investigate more tomorrow)
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/452#issuecomment-97971490>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by philipWendland** [comment]
@frankmorgner 
I could trace this back to 0bdc365ef2dddcf8baf45ce7f10964b22fd32960. Looks like a double free to me (looking at the debug output, not the code changes). Do you see how this could happen?

@dengert 
> There are some memory leaks, in engine and/or p11. There were two sets of competing patches from a few years ago that tried to address them.

Do you think this is related? (I was using the current master branch of engine_pkcs11.so).

**Comment by dengert** [comment]
On 5/1/2015 4:34 AM, Philip Wendland wrote:
> @frankmorgner <https://github.com/frankmorgner>
> I could trace this back to 0bdc365 <https://github.com/OpenSC/OpenSC/commit/0bdc365ef2dddcf8baf45ce7f10964b22fd32960>. Looks like a double free to me (looking at the debug output, not the code
> changes). Do you see how this could happen?

Calling the EVP_MD_CTX_create and EVP_MD_CTX_destroy are what we should be doing, because EVP_MD_CTX_destroy calls  EVP_MD_CTX_cleanup
that does a few more things.

The few more things may be the source of the double free, if we are missing some other OpenSSL structure too.

Do you have the trace?

>
> @dengert <https://github.com/dengert>
>
>     There are some memory leaks, in engine and/or p11. There were two sets of competing patches from a few years ago that tried to address them.
>
> Do you think this is related? (I was using the current master branch of engine_pkcs11.so).

The change to use the EVP_MD_CTX_destroy should have reduced the memory leaks.


>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/452#issuecomment-98085419>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
@philipWendland I just pushed a commit that is related. Could you try again?

**Comment by frankmorgner** [comment]
@dengert do you know where to find those old patches?

**Comment by philipWendland** [comment]
@frankmorgner 
Was about to point you to the same thing. With the old version:
```
card_removed (reader=0x6c8580) at slot.c:173
173			for (i=0; i < card->nmechanisms; ++i) {
(gdb) n
174				if (card->mechanisms[i]->free_mech_data) {
(gdb) 
177				free(card->mechanisms[i]);
(gdb) 
*** Error in `/usr/bin/openssl': free(): invalid pointer: 0x00007ffff6b12bc0 ***
```
With your new commit it is fixed!

**Comment by dengert** [comment]
On 5/1/2015 6:14 AM, Frank Morgner wrote:
> @dengert <https://github.com/dengert> do you know where to find those old patches?

Has 3 sets of fixes, but may need to be revised:
https://github.com/OpenSC/engine_pkcs11/pulls

Helps to show relationships:
https://github.com/OpenSC/engine_pkcs11/network


https://github.com/OpenSC/libp11/pulls
https://github.com/OpenSC/libp11/network


@commonism had the most memory leak changes.

I had stated to look at them, and it was adding a lot of code and I was in the middle of adding the ECDSA  and ECDH support and waiting for OpenSSL to address how to
work with ECC without using the local OpenSSL EC header files. Now those have been done, its time to look at memory leaks again.


>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/452#issuecomment-98103018>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
If there are no more tests or reviews going on, then this can be merged. I think all remarks have been considered so far.

**Comment by viktorTarasov** [comment]
I would prefer to pick these commits individually :
* hesitating to touch specific part that I cannot test
* do not think that the only return in a function has to be after 'err' label

**Comment by frankmorgner** [comment]
Please choose the method you prefer most. (I hope you don't want me to send dozens of individual PRs.) I just have the impression that we don't get more review (or progress) than what we've got at the moment.

Referring to the 'goto err' method: I think a single exit point for a function was also in the secure coding guidelines you once referenced. Anyway, it surely solves the problem of only having one location where cleanup should be done. And this is what is currently missing in big parts of the code and what this PR tries to solve. If you've got a better solution please let me know.

**Comment by viktorTarasov** [comment]
@frankmorgner : once more you take me for someone else. 

a: accepted, i: ignored, r: rewritten
Other people can also pick and push some of the ignored commits. 

 a e87b484 fixed invalid free
 a 775866e framework-pkcs15: fixed memory leak when encoding pubkey
 a 328f629 fix resource leaks in while registering PKCS#11 mechanisms
 a f76b69a pkcs11-tool: fixed resource leak
 a 0bdc365 openssl: fixed resource leak
 a 541f217 pkcs15-infocamere: fixed resource leak
 a 9ad919a sc-hsm-tool: fixed resource leak
 a fdb944a pkcs15-tool: fixed resource leak
 a aba7014 pkcs15-init: fixed resource leak
 a 9d26754 pkcs15-crypt: fixed resource leak
 i 2bde25c piv-tool: fixed resource leak
 a f0ddbf4 openpgp-tool: fixed resource leak
 a 2025728 pintest: fixed resource leak
 a 28b18b7 sm-cwa14890: fixed resource leak
 a 63d1376 profile: fixed resource leak
 a 1afd8b6 pkcs15-setcos: fixed resource leak
 a 8c9fbc5 pkcs15-rtecp: fixed resource leak
 i 8eb40b5 pkcs15-oberthur: fixed resource leak
 r 0194953 pkcs15-oberthur-awp: fixed resource leak
 r 983b3c1 pkcs15-myeid: fixed resource leak
 i da4b71b pkcs15-lib: fixed resource leak
 r d76c675 pkcs15-iasecc: fixed resource leak
 a 0c3c347 pkcs15-gpk: fixed resource leak
 i 5adeec9 pkcs15-epass2003: fixed resource leak
 a cdca459 pkcs15-cflex: fixed resource leak
 a 4a30105 pkcs15-authentic: fixed resource leak
 a a367fd1 sm-common: fixed resource leak
 a 5e0678d pkcs15-syn: fixed resource leak
 a 4a7ec77 pkcs15-pubkey: fixed resource leak
 r 46175da pkcs15-data: fixed resource leak
 a 26ae2c4 pkcs15-cache: fixed resource leak
 a 0c30c9b pkcs15: fixed resource leak
 a f7ed8e4 pkcs15-algo: fixed resource leak
 i 303f38e iasecc-sdo: fixed resource leak
 i cb6695b cwa-dnie: fixed resource leak
 i f6e5f99 cwa14890: fixed resource leak
 i 0ed90f3 card-tcos: fixed resource leak
 r 4b83fc6 card-myeid: fixed resource leak
 r a51740b card-iasecc: fixed resource leak
 a f5a0b45 card-authentic: fixed resource leak
 a 78aadef fixed indenting
 a e5c992d added LOG_TEST_GOTO_ERR and SC_TEST_GOTO_ERR

**Comment by frankmorgner** [comment]
Thanks for looking into it!

I updated the PR to only include the previously ignored commits.

**Comment by frankmorgner** [comment]
@viktorTarasov I again reviewed the remaining patches and they indeed look fine. Do you see any reason why not to accept them?

**Comment by frankmorgner** [comment]
merged with master and rebased

**Comment by frankmorgner** [comment]
If no objections, I'll merge the remaining patches (all of them were previously "ignored").

**Pull request merged**
