### PR TITLE
configure: disable "autostart-items" by default

### PR DESCRIPTION
**Pull request by henning-schild**
Related-to: https://github.com/OpenSC/OpenSC/issues/2060
Signed-off-by: Henning Schild <henning@hennsch.de>

##### Checklist

- [x] Documentation is added or updated
- [x] New files have a LGPL 2.1 license statement
- [x] PKCS#11 module is tested
- [x] Windows minidriver is tested
- [x] macOS tokend is tested

### CODE REVIEW

**Comment by frankmorgner** [comment]
A real solution would be to recognize symlinks instead...

**Review by frankmorgner — CHANGES_REQUESTED** [review]
A real solution would be to recognize symlinks instead...

**Comment by henning-schild** [comment]
Sure, and hard-links, bind-mounts, all other pkcs#11 plugins in the world, that opensc can not possibly know about ... browsers that users do not want to have configured for opensc.

The tool needs more work before it can be considered safe for unconditional regular automatic use. And making that the default means distros will likely inherit it ... once they go >=0.20 (which many of the big ones have not yet done)

**Comment by frankmorgner** [comment]
Feel free to rework and make a new PR

**Pull request closed without merging**
