### PR TITLE
Build cleanups

### PR DESCRIPTION
**Pull request by alonbl**
Some build fixups.

1. update .gitignore for recent automake test suites
2. remove generated sources out of tree.

### CODE REVIEW

**Comment by frankmorgner** [comment]
I'm keeping files.html and tools.html in the source tree on purpose, to be able to link the man pages in the [wiki](https://github.com/OpenSC/OpenSC/wiki)

**Comment by alonbl** [comment]
This is not the correct way to handle generated files, probably better is
to have them as release as well, or have ci to automatically build and
publish them to some other repository.

**Comment by frankmorgner** [comment]
feel free to propose an alternative approach

**Comment by alonbl** [comment]
On Mon, Sep 10, 2018 at 10:48 AM Frank Morgner <notifications@github.com> wrote:
> feel free to propose an alternative approach

I have.

I hope you agree that best practice is to avoid having generated files
within source repository.

I suggest to have a CI trigger on master commit to build package or
even only docs, clone docs repo commit the new docs and push.
Have wiki to refer to docs repo with 1:1 branches as source.

I do not see any advantage of having this docs are a full blown repo,
I use webdav in my setups, however, I do understand that github does
not provide webdav service (although sourceforge does).

**Comment by frankmorgner** [comment]
Keeping built files has advantages and disadvantages; removing them has advantages and disadvantages...

Your approach was the idea behind https://github.com/OpenSC/opensc.github.io. As alternative, Github also allows [a dedicated branch or the `docs` folder](https://blog.github.com/2016-08-22-publish-your-project-documentation-with-github-pages/) to publish static documentation.

The problem is, that nobody has yet taken the time to implement one of the approaches. Feel free to add the required changes to `appveyor.yml` or `.travic.yml` for updating the docs... Just check on the scripts I've used to upload the nightly builds.

**Comment by alonbl** [comment]
ok, closing this as I have no time to invest, sorry for the noise.

**Pull request closed without merging**
