### PR TITLE
Fix OpenPGP driver to work correctly with YubiKey NEO

### PR DESCRIPTION
**Pull request by frankmorgner**
I tried to sum up the discussion from #507 in this PR.

I don't have a NEO. @dengert, @rqou @mouse07410 could you check with your NEOs whether:

1. the NEO defaults to the PIV application
2. You can force the PGP application via opensc.conf as discussed in #507
3. the PGP application works as expected

 Thank you!

### CODE REVIEW

**Comment by mouse07410** [comment]
Frank,

I’ve done some testing of this PR, and found it working fine on my YubiKey NEO (PIV 0.1.3, OpenPGP 1.0.10). I haven’t tested OpenSC.tokend, as it is giving me problems in general.

$ yubico-piv-tool -a status
CHUID: 3019d4e739da739ced39ce……..
Slot 9a:
Algorithm: RSA2048
Subject DN: CN=uri
Issuer DN: C=US, ST=MA, O=The Burrow, OU=Gatherers, CN=Forest RSA CA 3
Fingerprint: e403cd9afb75328b16289b59e082f673736386f4a57…..
Not Before: Sep  1 03:06:27 2015 GMT
Not After: Sep  1 03:06:27 2018 GMT
…
$ piv-tool -n
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
PIV-II card
$ OPENSC_CONF=/Library/OpenSC/etc/neo-openpgp-opensc.conf openpgp-tool --pretty -U
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
Account:   uri
Name:      Blumenthal Uri
Language:  en
Gender:    male
$ gpg2 --card-status
Application ID ...: D276000…..
Version ..........: 2.0
Manufacturer .....: Yubico
Serial number ....: xxxxxxxx
Name of cardholder: Uri Blumenthal
Language prefs ...: en
Sex ..............: male
URL of public key : [not set]
Login data .......: uri
Signature PIN ....: forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 127 127 127
PIN retry counter : 10 10 10
Signature counter : 11
Signature key ....: 0EB9 0C09 F70A 8D69 4338  AD9B A068 AD0D 7D7B DC2C
      created ....: 2015-09-01 02:23:54
Encryption key....: 5241 5DEF 8A73 6E73 E660  EE60 E18F 852E E8FC B143
      created ....: 2015-02-12 09:59:21
Authentication key: C888 C3CD D0E6 F8A7 ADA3  99FF F193 66B0 FA43 FF7D
      created ....: 2015-02-12 10:00:04
General key info..: pub  2048R/0xA068AD0D7D7BDC2C 2015-09-01 Mobile Mouse 4 (Yubi) <mouse07410@hotmail.com<mailto:mouse07410@hotmail.com>>
sec   2048R/0x684AC1FCEAA16B87  created: 2015-02-12  expires: 2018-02-11
ssb>  2048R/0xE18F852EE8FCB143  created: 2015-02-12  expires: 2018-02-11
                      card-no: 0006 03643907
ssb>  2048R/0xF19366B0FA43FF7D  created: 2015-02-12  expires: 2018-02-11
                      card-no: 0006 03643907
ssb>  2048R/0xA068AD0D7D7BDC2C  created: 2015-09-01  expires: 2018-08-31
                      card-no: 0006 03643907



On Sep 12, 2015, at 13:34 , Frank Morgner <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried to sum up the discussion from #507<https://github.com/OpenSC/OpenSC/pull/507> in this PR.

I don't have a NEO. @dengert<https://github.com/dengert>, @rqou<https://github.com/rqou> @mouse07410<https://github.com/mouse07410> could you check with your NEOs whether:

  1.  the NEO defaults to the PIV application
  2.  You can force the PGP application via opensc.conf as discussed in #507<https://github.com/OpenSC/OpenSC/pull/507>
  3.  the PGP application works as expected

Thank you!

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/OpenSC/OpenSC/pull/551

Commit Summary

  *   Fix OpenPGP driver to work correctly with YubiKey NEO
  *   openpgp: match application, not ATR

File Changes

  *   M src/libopensc/card-openpgp.c<https://github.com/OpenSC/OpenSC/pull/551/files#diff-0> (54)
  *   M src/libopensc/ctx.c<https://github.com/OpenSC/OpenSC/pull/551/files#diff-1> (2)

Patch Links:

  *   https://github.com/OpenSC/OpenSC/pull/551.patch
  *   https://github.com/OpenSC/OpenSC/pull/551.diff

—
Reply to this email directly or view it on GitHub<https://github.com/OpenSC/OpenSC/pull/551>.

--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by frankmorgner** [comment]
Great, thanks! I'll wait for some more comments, though.

**Comment by dengert** [comment]
Working on it...

On 9/13/2015 1:59 AM, Frank Morgner wrote:
> Great, thanks! I'll wait for some more comments, though.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/551#issuecomment-139847987>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
The NEO using the PIV applet continues to work as expected with these mods.

**Comment by dengert** [comment]
While trying the NEO on a NFC reader, ATR is:
$ opensc-tool -a
Using reader with a card: ACS ACR122U PICC Interface 00 00
3b:8c:80:01:59:75:62:69:6b:65:79:4e:45:4f:72:33:58

While plugging NEO in as USB ATR is:
$ opensc-tool -a
Using reader with a card: Yubico Yubikey NEO OTP+CCID 00 00
3b:fc:13:00:00:81:31:fe:15:59:75:62:69:6b:65:79:4e:45:4f:72:33:e1

This may not be an issue, but these mods do add USB ATR but not NFC ATR to card-openpgp.c.

The NEO PIV supports verify and crypto over NFC, a violation of NIST specifications for PIV. Not clear if OpenPGP will work over NFC, or if there are security issues.

**Comment by frankmorgner** [comment]
well, transmit of an unprotected PIN via NFC  is always a problem, for PIV and for PGP

**Comment by frankmorgner** [comment]
Feel free, to add the contact-less ATR in a PR.

**Comment by dengert** [comment]
I don't think the ATR is needed if the OpenPGP code because it now test for AIDs. The patch added the NEO ATR for some reason.
Someone with multiple OpenPGP cards could test if the ATRs are still needed, as older cards may not
have an AID on the card.

Microsoft does not use ATRs for their drivers such as the PIV. I think they look for AIDs.
For non windows drivers, I think the registry still needs ATRs and/or ATR masks to use the OpenSC minidriver.
There may be a way to get around this, but I have not looked for it.

On 9/13/2015 6:35 PM, Frank Morgner wrote:
> Feel free, to add the contact-less ATR in a PR.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/551#issuecomment-139928505>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
The ATR in the PGP driver is used as shortcut and to set the name of the card.

**Comment by dengert** [comment]
It does more then set the name, pgp_match_card returns 1, without even checking if there is as AID.



  290 pgp_match_card(sc_card_t *card)
  291 {
  292         int i;
  293
  294         i = _sc_match_atr(card, pgp_atrs, &card->type);
  295         if (i >= 0) {
  296                 card->name = pgp_atrs[i].name;
  297                 return 1;

Following does not get executed...

  298         } else {
  299                 sc_path_t       partial_aid;
  300                 unsigned char aid[16];
  301
  302                 /* select application "OpenPGP" */


Only checking the ATR was the original problem. The real fix in this patch was the reordering of the drivers in ctx.c
so the openpgp did not grab the card before other drivers (i.e. piv) could see if the card had a AID for a different application.
The patch does will allow for new cards to have the openpgp applet without having to add the ATR.
The NEO should be treated as one of these new cards, and not have its ATR added to the code.

You can leave the patch as is, the point I am trying to make is this patch still uses the ATR for the NEO.


On 9/14/2015 2:18 AM, Frank Morgner wrote:
> The ATR in the PGP driver is used as shortcut and to set the name of the card.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/551#issuecomment-139982334>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
Also see #391, as it should work with out adding the ATR, and the NEO should be treated the same way, anf the NEO ATR not added either.

**Comment by frankmorgner** [comment]
the pgp application does get selected in the pgp's init function anyway, that's why the neo doesn't need it anymore in the match function.

**Comment by dengert** [comment]
You are not getting my point. I am not saying the OpenPGP does not work, I am saying the openpgp driver interferes with
some other application being selected when the card does not have an OpenPGP application.

If we were to add some other driver that could use the NEO and added it in ctx.c
after the openpgp driver, the new driver would never get selected, even if the NEO did not have the openpgp applet.

card.c line 260 to 292  call ops->match_card(card) and r = ops->init(card) loking at all drivers.
But only  if match_card(card) != 1 and init(card) returns SC_ERROR_INVALID_CARD will another card driver be tested.
If init(card) fails the card is disconnected.

Looking at  card-openpgp.c line 350, pgp_init calls iso_ops->select_file and line 352 returns r, which
I do not believe is SC_ERROR_INVALID_CARD. The code in pgp_match_card that tries to the select the AID
if it fails, will have pgp_match_card return 0, so other drivers can look at the card.

So the best place to do the AID check is in the match_card which should be doing only what is needed to verify this driver
is the driver that should be using this card. The init function could fail for a number of reasons.

It also looks like the code on pgp_match_card is much more robust, setting the card->type from the AID.
and not requiring the ATR.

I would like to see some developers with OpenPGP cards to remove these lines, and let pgp_match_card query the AID:

  294         i = _sc_match_atr(card, pgp_atrs, &card->type);
  295         if (i >= 0) {
  296                 card->name = pgp_atrs[i].name;
  297                 return 1;
  298         } else

If card name is important, and ATRs are still needed, the above code could still do the _match_card, and even if it works,
do the AID matching.

OpenSC should look closet at ISO7816-4 section 9 "Application independent Card Services" to select an application.
Only for non compliant cards, with single applications should the ATR be used.

On 9/14/2015 10:48 AM, Frank Morgner wrote:
> the pgp application does get selected in the pgp's init function anyway, that's why the neo doesn't need it anymore in the match function.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/551#issuecomment-140121898>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
AFAIK, all neo's are produced with the PGP applet on board. AFAIK, the neo's ATR is unique and does not interfere with other cards. In consequence, it's reasonable to assume that a card with this ATR supports PGP. (Whether that's ISO compliant or not is on a different page. Most vendors don't even seem to be very committed to the ISO standard...) So, what the pgp driver does is not elegant, but it's OK.

Imagine the problem you described with a PGP driver that only recognizes the AID (a) and with a PGP driver that only recognizes the ATR (b). What would happen to the neo?

1. neo gets inserted
2. `sc_connect_card` iterates through card drivers `match_card`
3. `sc_connect_card` breaks when *the first* driver returns 1 for `match_card`
4. card is returned initialized with exactly this driver.

You may have noticed that it doesn't matter whether `match_card` returns 1 because of an ATR or because of an AID. The real problem here, is that only the first matching driver gets valued. All the others are ignored. This kind of "interference" with an other card driver as you say is *intrinsic* to OpenSC's card handling, it is *not* a bad design decision within the PGP driver.

Solving this intrinsic problem is what we need to do as future work. And this is also what I tried to point out in #538. In PKCS\#11, for example, one solution could be to *not ignore the rest of the card drivers* during the matching, but to instead create slots for all card drivers that are usable, while internally mapping each slot to the correct card/card driver.

**Comment by dengert** [comment]
I am not talking two PGP drivers. I am talking about the card-openpgp.c driver that does not do a very good job, and some future driver
for some other applet not getting called because of the code in card-openpgp.c.

Calling the match_card of the piv driver before the match in the the openpgp to avoid the issues in card-openpgp was my main concern, and you fixed that part.
A user can also select the application by using opensc.conf.

#538 could work if the card can support two applications possibly being used at the same time.

I am not getting anywhere with this discussion. The problem will show up again.


On 9/14/2015 3:08 PM, Frank Morgner wrote:
> AFAIK, all neo's are produced with the PGP applet on board. AFAIK, the neo's ATR is unique and does not interfere with other cards. In consequence, it's reasonable to assume that a card with this ATR
> supports PGP. (Whether that's ISO compliant or not is on a different page. Most vendors don't even seem to be very committed to the ISO standard...) So, what the pgp driver does is not elegant, but
> it's OK.
>
> Imagine the problem you described with a PGP driver that only recognizes the AID (a) and with a PGP driver that only recognizes the ATR (b). What would happen to the neo?
>
>  1. neo gets inserted
>  2. |sc_connect_card| iterates through card drivers |match_card|
>  3. |sc_connect_card| breaks when /the first/ driver returns 1 for |match_card|
>  4. card is returned initialized with exactly this driver.
>
> You may have noticed that it doesn't matter whether |match_card| returns 1 because of an ATR or because of an AID. The real problem here, is that only the first matching driver gets valued. All the
> others are ignored. This kind of "interference" with an other card driver as you say is /intrinsic/ to OpenSC's card handling, it is /not/ a bad design decision within the PGP driver.
>
> Solving this intrinsic problem is what we need to do as future work. And this is also what I tried to point out in #538 <https://github.com/OpenSC/OpenSC/issues/538>. In PKCS#11, for example, one
> solution could be to /not ignore the rest of the card drivers/ during the matching, but to instead create slots for all card drivers that are usable, while internally mapping each slot to the correct
> card/card driver.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/pull/551#issuecomment-140191922>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
I rebased to resolve the conflicts, if there are no objections I'll merge the PR.

**Comment by philipWendland** [comment]
I did not follow this discussion with full concentration, but a simple
comment:

AFAIK the first neos had default ISD keys, or at least the possibility
to install/delete applets. So it could be possible that there are neos
out there with no PGP applet.

**Comment by mouse07410** [comment]
Only development (and early release) NEOs had the ability to manage (install/delete) applets. Current/production versions do not allow the user that capability.

For practical purposes, I think we can safely ignore those early devices, and assume that all the relevant applets are present/installed. Plus, there is no reason (that I see) to delete an applet (rather than just letting it be there, unused) - it's not like it would occupy memory needed for something else. So in the worst case, a user who does not need a PGP applet, would have to install it. I could live with it, if it were me. :-)

Sent from my iPad

On Sep 16, 2015, at 05:49, Philip Wendland <notifications@github.com<mailto:notifications@github.com>> wrote:

I did not follow this discussion with full concentration, but a simple
comment:

AFAIK the first neos had default ISD keys, or at least the possibility
to install/delete applets. So it could be possible that there are neos
out there with no PGP applet.

**Pull request merged**
