### PR TITLE
essentially revert 1bb2547

### LINKED ISSUE #2199: opensc 0.21.0 break my openvpn config using a Aladdin Knowledge Systems Token JC PKI
As soon as I install opensc 0.21.0, the detection of this PKI token by openvp is broken. 

Bus 005 Device 003: ID 0529:0620 Aladdin Knowledge Systems Token JC

### Steps to reproduce
It seems the PKI key is no more detected and the code keeps asking for inserting the token and the window to enter Pin code never displayed. Downgrading to opensc 0.20.0, the problem vanishes.

Note that for this PKI, there is a specific library to use libeToken.so but pkcs11-tool works when instructed to use this module.

It is probably a bad interaction via libpkcs11-helper but I have no clue yet.

Could you provide some direction to help debugging the problem.

### PR DESCRIPTION
**Pull request by frankmorgner**
fixes #2199

returns not allowed PKCS#11 codes to applications, however

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by dengert** [comment]
Looks good.  
@EricV can you also test this?

Tested with OpenSC configured to only recognize myeid cards with a Yubikey and empty reader:  
```
 export PKCS11SPY=/opt/ossl-1.1/lib/opensc-pkcs11.so 
 export PKCS11SPY_OUTPUT=/tmp/spy.txt
 export OPENSC_DRIVER=myeid
./pkcs11-tool --module /opt/ossl-1.1/lib/pkcs11-spy.so  -L
Available slots:
Slot 0 (0x0): Yubico YubiKey OTP+FIDO+CCID 00 00
  (token not recognized)
Slot 1 (0x4): SCM Microsystems Inc. SCR 355 [CCID Interface] 01 00
  (empty)
```

With Yubikey and a myeid card. pkcs11-spy loads p11-kit which then loads modules for opensc-pkcs11, softhsm and ykcs11.

```
export PKCS11SPY=/usr/lib/x86_64-linux-gnu/p11-kit-proxy.so
export PKCS11SPY_OUTPUT=/tmp/spy.txt
export OPENSC_DRIVER=myeid
./pkcs11-tool --module /opt/ossl-1.1/lib/pkcs11-spy.so  -L
export PKCS11SPY=/opt/ossl-1.1/lib/opensc-pkcs11.so 

Slot 0 (0x10): Yubico YubiKey OTP+FIDO+CCID 00 00
  (token not recognized)    ((OpenSC configure to only recognize myeid))
Slot 1 (0x11): SCM Microsystems Inc. SCR 355 [CCID Interface] 01 00
  token label        : MyEID (Basic PIN)
  token manufacturer : Aventra Ltd.
  token model        : PKCS#15
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 40.0
  serial num         : 506325162e50244c
  pin min/max        : 4/8
Slot 2 (0x12): SCM Microsystems Inc. SCR 355 [CCID Interface] 01 00
  token label        : MyEID (Sign PIN)
  token manufacturer : Aventra Ltd.
  token model        : PKCS#15
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 40.0
  serial num         : 506325162e50244c
  pin min/max        : 4/8
Slot 3 (0x13): SoftHSM slot ID 0x3b974305
  token label        : mytoken
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.5
  firmware version   : 2.5
  serial num         : 75b0ec1e3b974305
  pin min/max        : 4/255
Slot 4 (0x14): SoftHSM slot ID 0x1
  token state:   uninitialized


((the ykcs11 module then finds the Yubikey)) 
Slot 5 (0x15): Yubico YubiKey OTP+FIDO+CCID 00 00
  token label        : YubiKey PIV #13412288
  token manufacturer : Yubico (www.yubico.com)
  token model        : YubiKey YK5
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 1.0
  firmware version   : 5.26
  serial num         : 13412288
  pin min/max        : 6/48
```


@EricV can you also test this?

**Comment by EricV** [comment]
Confirmed working for me also.

**Comment by frankmorgner** [comment]
thanks for testing!

**Comment by dengert** [comment]
@frankmorgner  are you considering  having a 0.21.1 release to fix this bug?

The bug will show up when using p11-kit  and token is not supported by OpenSC. 
So this will lead to people reporting this problem to their smart card vendor or linux distro, and not to OpenSC. 
Our reputation is on the line, if we can not operate under p11-kit.

**Comment by EricV** [comment]
I support this request, we have hundreds of Linux PC that are yet not affected but that will be if the next debian version incorporates the 0.21.0. And currently freeze for this next debian version is really close (mid february)

If you want to make it secure you can just take this commit and realease 0.21.0 + this commit as 0.21.1.

Otherwyse I tested git upstream yesterday and it also works. Just to let you know.

**Pull request merged**
