### PR TITLE
Aladdin work in progress

### PR DESCRIPTION
**Pull request by ieugen**
Details in #461

### CODE REVIEW

**Comment by frankmorgner** [comment]
Before actually implementing stuff, you should read the docs. https://www.digisign.ro//uploads/Fisa-tehnica-eToken.pdf says something about
```
Modele (in functie de memorie)    32K, 64K (Siemens CardOS), 72K (Java)
```
Though I don't speak Romanian, this sounds like you should be able to reuse the CardOS driver, which is already part of OpenSC. You could try adding your ATR to the CardOS driver...

**Comment by ieugen** [comment]
Thanks.
It means that it might be CardOS or Java. How can I make sure? The output (in #461 ) mentions 72k Java. And what are my options in that case?  

p.s. I've installed more packages and I can build OpenSC right now :D

**Comment by frankmorgner** [comment]
sorry, your documents are not very detailed. you're on your own...

**Comment by frankmorgner** [comment]
please re-open if you have some more progress

**Pull request closed without merging**
