### PR TITLE
GIDS: don't split PSO:DEC into multiple commands

### PR DESCRIPTION
**Pull request by frankmorgner**
@zlovik, please check whether this fixes your problem with #765.

##### Checklist
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by zlovik** [comment]
Unfortunate, after apply [this](https://github.com/OpenSC/OpenSC/pull/1604.patch) patch, I have an error CKR_ARGUMENTS_BAD (0x7). 
For more information see: [gids_patch1604.log](https://github.com/OpenSC/OpenSC/files/2850342/gids_patch1604.log)

**Comment by frankmorgner** [comment]
Please try the additional patch and let me know if this works with your EF.ATR.

**Comment by frankmorgner** [comment]
Your card doesn't contain an EF.ATR, which would be the place on the card to announce extended length capabilities, see the [GIDS specification](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn642100(v=vs.85)#generic-identity-device-specification-version-20). Without that, OpenSC assumes that the card can only send 256 bytes of data, which is one byte less than what your type of key requires (the padding content indicator doesn't fit anymore). @zlovik, how did you initialize your card or where did you get it from.
```
Outgoing APDU (15 bytes):
00 A4 04 00 09 A0 00 00 03 97 42 54 46 59 00 ..........BTFY.
P:14297; T:0x4578170304 12:40:14.890 [opensc-pkcs11] reader-pcsc.c:213:pcsc_internal_transmit: called
P:14297; T:0x4578170304 12:40:14.912 [opensc-pkcs11] reader-pcsc.c:294:pcsc_transmit: 
Incoming APDU (22 bytes):
61 12 4F 0B A0 00 00 03 97 42 54 46 59 02 01 73 a.O......BTFY..s
03 40 01 C0 90 00                               .@....
P:14297; T:0x4578170304 12:40:14.912 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:14297; T:0x4578170304 12:40:14.912 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:14297; T:0x4578170304 12:40:14.913 [opensc-pkcs11] card.c:465:sc_unlock: called
P:14297; T:0x4578170304 12:40:14.913 [opensc-pkcs11] reader-pcsc.c:673:pcsc_unlock: called
P:14297; T:0x4578170304 12:40:14.913 [opensc-pkcs11] card-gids.c:299:gids_select_aid: returning with: 0 (Success)
P:14297; T:0x4578170304 12:40:14.914 [opensc-pkcs11] card-gids.c:582:gids_match_card: found AID
P:14297; T:0x4578170304 12:40:14.914 [opensc-pkcs11] card.c:297:sc_connect_card: matched: GIDS Smart Card
P:14297; T:0x4578170304 12:40:14.914 [opensc-pkcs11] card-gids.c:632:gids_init: called
P:14297; T:0x4578170304 12:40:14.914 [opensc-pkcs11] ef-atr.c:147:sc_parse_ef_atr: called
P:14297; T:0x4578170304 12:40:14.914 [opensc-pkcs11] card.c:754:sc_select_file: called; type=2, path=3f002f01
P:14297; T:0x4578170304 12:40:14.914 [opensc-pkcs11] card-gids.c:956:gids_select_file: called
P:14297; T:0x4578170304 12:40:14.915 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:14297; T:0x4578170304 12:40:14.915 [opensc-pkcs11] card.c:415:sc_lock: called
P:14297; T:0x4578170304 12:40:14.915 [opensc-pkcs11] reader-pcsc.c:623:pcsc_lock: called
P:14297; T:0x4578170304 12:40:14.915 [opensc-pkcs11] card-gids.c:2093:gids_card_reader_lock_obtained: called
P:14297; T:0x4578170304 12:40:14.915 [opensc-pkcs11] card-gids.c:2101:gids_card_reader_lock_obtained: returning with: 0 (Success)
P:14297; T:0x4578170304 12:40:14.915 [opensc-pkcs11] card.c:455:sc_lock: returning with: 0 (Success)
P:14297; T:0x4578170304 12:40:14.916 [opensc-pkcs11] apdu.c:513:sc_transmit: called
P:14297; T:0x4578170304 12:40:14.916 [opensc-pkcs11] apdu.c:363:sc_single_transmit: called
P:14297; T:0x4578170304 12:40:14.916 [opensc-pkcs11] apdu.c:370:sc_single_transmit: CLA:0, INS:A4, P1:8, P2:0, data(2) 0x7ffee3b392f2
P:14297; T:0x4578170304 12:40:14.916 [opensc-pkcs11] reader-pcsc.c:284:pcsc_transmit: reader 'ACS ACR 38U-CCID'
P:14297; T:0x4578170304 12:40:14.916 [opensc-pkcs11] reader-pcsc.c:285:pcsc_transmit: 
Outgoing APDU (8 bytes):
00 A4 08 00 02 2F 01 00 ...../..
P:14297; T:0x4578170304 12:40:14.916 [opensc-pkcs11] reader-pcsc.c:213:pcsc_internal_transmit: called
P:14297; T:0x4578170304 12:40:14.928 [opensc-pkcs11] reader-pcsc.c:294:pcsc_transmit: 
Incoming APDU (2 bytes):
6A 86 j.
P:14297; T:0x4578170304 12:40:14.928 [opensc-pkcs11] apdu.c:382:sc_single_transmit: returning with: 0 (Success)
P:14297; T:0x4578170304 12:40:14.928 [opensc-pkcs11] apdu.c:535:sc_transmit: returning with: 0 (Success)
P:14297; T:0x4578170304 12:40:14.928 [opensc-pkcs11] card.c:465:sc_unlock: called
P:14297; T:0x4578170304 12:40:14.928 [opensc-pkcs11] reader-pcsc.c:673:pcsc_unlock: called
P:14297; T:0x4578170304 12:40:14.929 [opensc-pkcs11] iso7816.c:128:iso7816_check_sw: Incorrect parameters P1-P2
P:14297; T:0x4578170304 12:40:14.929 [opensc-pkcs11] iso7816.c:578:iso7816_select_file: returning with: -1205 (Incorrect parameters in APDU)
P:14297; T:0x4578170304 12:40:14.929 [opensc-pkcs11] card.c:776:sc_select_file: 'SELECT' error: -1205 (Incorrect parameters in APDU)
P:14297; T:0x4578170304 12:40:14.929 [opensc-pkcs11] ef-atr.c:151:sc_parse_ef_atr: Cannot select EF(ATR) file: -1205 (Incorrect parameters in APDU)
```
@vletoux is the above trace the right way to read EF.ATR from GIDS or is there some special handling for `3F00` required?

**Comment by vletoux** [comment]
This GIDS applet (https://github.com/vletoux/GidsApplet) defines the 3F00 file at initilization:
https://github.com/vletoux/GidsApplet/blob/master/src/com/mysmartlogon/gidsApplet/GidsApplet.java#L130-L150
For EF.ATR, it is here:
https://github.com/vletoux/GidsApplet/blob/master/src/com/mysmartlogon/gidsApplet/GidsApplet.java#L306-L334
It defines for the capability byte at the value 0x80 
https://github.com/vletoux/GidsApplet/blob/master/src/com/mysmartlogon/gidsApplet/GidsApplet.java#L317
image
which means it supports chained APDU

I checked the code: it supports chained APDU for PSO:DEC in code

**Comment by frankmorgner** [comment]
In the above trace OpenSC uses INS=A4 for selecting the file, but your applet only handles INS=CB for returning EF.ATR. The GIDS specification is not exactly clear on whether EF.ATR/EF.DIR may be selected via SELECT APDU or not...

I don't have experience with other cards, but it looks like the easiest solution would be to add a special case to OpenSC's `gids_select_file`/`gids_read_binary`.

**Comment by zlovik** [comment]
Information about my GidsApplet.cap
`MD5 (GidsApplet.cap) = 852619a9fb79aa0a01a9b1347b093db7`
Unfortunately it's all information what I know about CAP file.

For installing applets use [globalplatform](https://javacard.pro/globalplatform/)
Setup step:
`java -jar gp.jar  -uninstall GidsApplet.cap -install GidsApplet.cap -default`

Initialization & personalization step:
`gids-tool -X --admin-key 000000000000000000000000000000000000000000000000 --pin 1234 --serial-number 30303030303030303030303030303030`

**Comment by frankmorgner** [comment]
The GIDS specification speaks of EF.ATR/EF.DIR as files in MF (which is also defined this way in ISO 7816-4). Additionally, there is the following passage on GET DATA:
>A GET DATA or PUT DATA command performs an implicit selection of the EF that is indicated by P1-P2 except when P1-P2 equals 2F-00 or 2F-01. This allows a GIDS application to retrieve the contents of EF.ATR and EF.DIR that are in the MF without losing the current selected application or its security status.

So it's fair to say that the GIDS applet should be extended to allow *explicit* selection and READ BINARY of EF.ATR/EF.DIR.

If done so, this PR should allow correct parsing of the card's transceive sizes.

**Comment by frankmorgner** [comment]
One more update: I've realized that some parts of EF.ATR are pre-defined by the spec, which means that the extended length capabilities can be hard coded. And the card service data shows that READ BINARY for EF.ATR is disabled... So it would be nice to add allow using GET DATA or even READ RECORD with sc_parse_ef_atr, however, that would require parsing comact TLV parsing of the card's ATR, which isn't currently implemented.

I've updated the PR to force the extended length capability, which should make the decipherment work.

**Comment by vletoux** [comment]
The cap used is the 1.1 version of the gids applet : 
https://github.com/vletoux/GidsApplet/releases/tag/1.1

**Comment by vletoux** [comment]
Frank, you force SC_CARD_CAP_APDU_EXT. But not all cards support extended APDU.
The applet works with chained APDU - I think you are introducing a breaking change.

You can see here the unit test when decrypting with a 2048 bits RSA key:
https://github.com/vletoux/GidsApplet/blob/master/src/com/mysmartlogon/gidsAppletTests/MinidriverTest.java#L82-L84

**Comment by frankmorgner** [comment]
Hmm, extended capabilities are hard coded in the GIDS spec, which makes me think that all implementations should support it.

Anyway, OpenSC should do chaining already without this PR:
https://github.com/OpenSC/OpenSC/blob/c2cc83754e84c74cd17c6a6b175a13bee2b95fc4/src/libopensc/card-gids.c#L2092
https://github.com/OpenSC/OpenSC/blob/c2cc83754e84c74cd17c6a6b175a13bee2b95fc4/src/libopensc/iso7816.c#L964-L999
https://github.com/OpenSC/OpenSC/blob/c2cc83754e84c74cd17c6a6b175a13bee2b95fc4/src/libopensc/iso7816.c#L34-L44

But according to the logs this doesn't happen...

**Comment by vletoux** [comment]
A third party virtual reader ? VMWare shared smart card is known for that.

**Comment by vletoux** [comment]
Also I recommend to upgrade the GIDS applet that @zlovik is using:
1.1 is known to break a key when having more than 1 certificate. 1.2 fixes that problem.
https://github.com/vletoux/GidsApplet/commit/f7c5d627f4a2dc2570c2f1ebe7984d2a863f3016

**Comment by frankmorgner** [comment]
No, it's OpenSC that throws an internal error, which should not happen if chaining was activated:
```
P:8445; T:0x4599911872 10:55:35.455 [opensc-pkcs11] sec.c:43:sc_decipher: called
P:8445; T:0x4599911872 10:55:35.455 [opensc-pkcs11] iso7816.c:976:iso7816_decipher: called
P:8445; T:0x4599911872 10:55:35.456 [opensc-pkcs11] iso7816.c:979:iso7816_decipher: ISO7816 decipher: in-len 256, out-len 512
P:8445; T:0x4599911872 10:55:35.456 [opensc-pkcs11] apdu.c:546:sc_transmit_apdu: called
P:8445; T:0x4599911872 10:55:35.456 [opensc-pkcs11] apdu.c:261:sc_check_apdu: failed length check for short APDU
P:8445; T:0x4599911872 10:55:35.456 [opensc-pkcs11] apdu.c:331:sc_check_apdu: Invalid Case 4 short APDU:
cse=04 cla=00 ins=2a p1=80 p2=86 lc=257 le=256
resp=0x7ffee4c19b10 resplen=512 data=0x7fa73e6090f0 datalen=257
P:8445; T:0x4599911872 10:55:35.456 [opensc-pkcs11] iso7816.c:1003:iso7816_decipher: APDU transmit failed: -1300 (Invalid arguments)
P:8445; T:0x4599911872 10:55:35.456 [opensc-pkcs11] sec.c:47:sc_decipher: returning with: -1300 (Invalid arguments)
```

**Comment by zlovik** [comment]
@vletoux thank you for recommendation.
@frankmorgner after apply last changes, I have a next problem with PSO:DEC
[gids_pso_err21.log](https://github.com/OpenSC/OpenSC/files/2864069/gids_pso_err21.log)

**Comment by frankmorgner** [comment]
In your log, finally all the decryption data is sent. However, the card still throws an error. It looks like the only place this error can happen, is this here:
https://github.com/vletoux/GidsApplet/blob/b7a20f7ada66190cd14600fc22426e3202e704d5/src/com/mysmartlogon/gidsApplet/GidsApplet.java#L707-L712
It looks like your input doesn't match the RSA keysize... Please check if this error also occurs with `pkcs11-tool --test --login` (which should pick the correct sizes).

I think this remote debugging leads nowhere. Current pointers are:
- OpenSC doesn't set the chaining bit if the possible length to send is too short, which shouldn't be the case in decipherment in iso7816.c
- By specification, GIDS applet should be capable of Extended length, which gets enabled with this PR. If not all GIDS cards support extended length, then this PR needs to be adapted to check EF.ATR via GET DATA.

**Comment by zlovik** [comment]
The testing of GIDS has been failed also. On this case, seems, the function PSO:COMP_SIGN returned 1206 (Wrong length). 
```
$pkcs11-tool --test --login --pin 1234
Using slot 1 with a present token (0x4)
C_SeedRandom() and C_GenerateRandom():
  seeding (C_SeedRandom) not supported
  ERR: C_GenerateRandom failed: CKR_FUNCTION_NOT_SUPPORTED (0x54)
Digests:
  all 4 digest functions seem to work
  MD5: OK
  SHA-1: OK
  RIPEMD160: OK
Signatures (currently only for RSA)
  testing key 0 (Private Key 00) 
error: PKCS11 function C_SignFinal failed: rv = CKR_DATA_LEN_RANGE (0x21)
Aborting.
```
I did the test twice. On the first case with 1024 key length and secondly 2048.
[gids_test_rsa1024.log](https://github.com/OpenSC/OpenSC/files/2868906/gids_test_rsa1024.log)
[gids_test_rsa2048.log](https://github.com/OpenSC/OpenSC/files/2868907/gids_test_rsa2048.log)

P.S. By the way, I see one interesting moment with "Padding indicator" byte in the PSO:DEC. By the formatting APDU, OpenSC set this byte in 0x00.
[https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/iso7816.c#L985-L997](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/iso7816.c#L985-L997)
But in the [vletoux test case](https://github.com/vletoux/GidsApplet/blob/master/src/com/mysmartlogon/gidsAppletTests/MinidriverTest.java#L83), this byte is missing. 
Can this leads to the error with PSO:DEC?

**Comment by vletoux** [comment]
I'm sorry but now is a bad time for me to load / debug the GIDS applet

**Comment by frankmorgner** [comment]
Closing this issue due to inactivity. Please re-open the ticket if more input is available.

**Pull request closed without merging**
