### PR TITLE
Remove too verbose output (close #1698)

### LINKED ISSUE #1698: Abuse of SC_FUNC_CALLED?
Since fbb4d1f84326b31d3b00f8a317389bd0d818f644, when calling pkcs-tool --verbose I get a arguably too verbose message:

P:6716; T:0x140409995595648 14:11:34.265 [pkcs15-tool] pkcs15-itacns.c:866:sc_pkcs15emu_itacns_init_ex: called

I wonder if this commit is just exposing the abuse of SC_FUNC_CALLED(card->ctx, 1) at pkcs15-itacns, and if this calls should be replaced with LOG_FUNC_CALLED(ctx);

If so I can submit a pull request.

### PR DESCRIPTION
**Pull request by nunojpg**

### CODE REVIEW

**Comment by frankmorgner** [comment]
I think SC_LOG_DEBUG_NORMAL (a.k.a. *helps developers*) would be more appropriate...

**Comment by Jakuje** [comment]
> I think SC_LOG_DEBUG_NORMAL (a.k.a. _helps developers_) would be more appropriate...

Might be. But all 95% other `SC_FUNC_CALLED` are called with `SC_LOG_DEBUG_VERBOSE`.

**Comment by frankmorgner** [comment]
> Might be. But all 95% other `SC_FUNC_CALLED` are called with `SC_LOG_DEBUG_VERBOSE`.

1/3 of the code uses `SC_FUNC_CALLED(card->ctx, SC_LOG_DEBUG_VERBOSE);` while 2/3 uses `LOG_FUNC_CALLED(ctx);`, wheras the latter translates to `SC_LOG_DEBUG_NORMAL`...

**Comment by nunojpg** [comment]
@frankmorgner I changed to SC_LOG_DEBUG_NORMAL

**Pull request merged**
