### PR TITLE
Upgrade OpenSSL to 1.1.1

### PR DESCRIPTION
**Pull request by metsma**
Version 1.0.2 is deprecated

Signed-off-by: Raul Metsma <raul@metsma.ee>

##### Checklist

- [ ] Documentation is added or updated
- [ ] New files have a LGPL 2.1 license statement
- [X] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Comment by metsma** [comment]
> I agree with the change in general, but we need to change the AppVeyor configuration as well.

Not sure how to fix openpace build, I am not familiar that project
https://ci.appveyor.com/project/LudovicRousseau/opensc/builds/31117727/job/xp7mvm0vav0mcrq6#L874

**Comment by frankmorgner** [comment]
This compiles OpenPACE with OpenSSL 1.1.1:
https://github.com/frankmorgner/OpenSC/commit/fd1fe6b7beab6fa8f9f09c392d45588f2997d063
https://github.com/OpenSC/OpenSC/commit/9d727e3ec4b42aa941e211838e70e42a0a9d3b7f
and you need this to configure the correct OpenSSL directory:
https://github.com/frankmorgner/OpenSC/commit/5120a23c87beaf3169600b3a3e06dc5374275a91

**Comment by metsma** [comment]
VS14 is good now, VS12 still broken

**Comment by frankmorgner** [comment]
OpenSSL binaries are not backward compatible due to changes in VS. I am working on integrating newer VSs (https://github.com/frankmorgner/OpenSC/tree/openssl)

**Comment by frankmorgner** [comment]
I've fixed the Windows builds in https://github.com/OpenSC/OpenSC/pull/1973

**Comment by frankmorgner** [comment]
merged with #1973

**Pull request closed without merging**
