### PR TITLE
Support uncompressed certificates on IDPrime 940

### LINKED ISSUE #2956: No certificates recognized on a Gemalto IDPrime 940
### Problem Description
I have a company-issued Gemalto IDPrime 940 (allegedly) with a user certificate on it used for logging into our infrastructure. I've been given the task of investigating integration with Linux without the use of proprietary modules to interface with the card, and am currently experimenting with OpenSC 0.24.0-rc2.

The card is properly recognized as an IDPrime 940 by OpenSC, and I can successfully authenticate with it using my PIN. However, none of the tools available (pkcs11-tool, pkcs15-tool, opensc-tool, etc) display any certificates on the card. 

There should be a single RSA2048 certificate issued to me with the appropriate attributes for smartcard login on the card, and I've verified that that is the case on a Windows machine running Net iD Access (the proprietary module currently in use).

### Steps to reproduce

1. Insert a Gemalto IDPrime 940 card with at least one certificate on the token
2. Run `pkcs11-tool --login -O`
3. Observe no listed certificates

### Logs
https://gist.github.com/Nihlus/cdc6cea6d051a732952a0f4e2e6c3075

I believe I've redacted any sensitive data in the logs; however, I'd very much appreciate a heads-up if I haven't.

### PR DESCRIPTION
**Pull request by Nihlus**
This PR intends to fix handling of uncompressed certificates in Gemalto IDPrime cards. I'm currently testing this on a 940 (applet version 4), but other card variants may be affected.

Specifically, the PR fixes a bug with the data caching when reading binary data from the card, as well as ensuring that the on-card file sizes are known regardless of the compression state of the file.

Fixes #2956.

##### Checklist

- [ ] Documentation is added or updated
- [ ] PKCS#11 module is tested
- [ ] Windows minidriver is tested
- [ ] macOS tokend is tested

### CODE REVIEW

**Review by Jakuje — APPROVED** [review]
Tested with all bunch cards I have lying around and all looks good! Thank you for your contribution!

**Comment by Nihlus** [comment]
Excellent! Now to start messing with the IDEMIA 9 cards...

**Review by frankmorgner — APPROVED** [review]
Please let us know when you think this PR is finalized

**Comment by Jakuje** [comment]
From my side, I think we are good, but I would like @xhanulik to check the modified code for the certificate compression.

**Comment by Nihlus** [comment]
I'm also happy with it, provided nothing else comes up.

**Review by xhanulik — APPROVED** [review]
Looks good.

**Comment by Jakuje** [comment]
Thank you!

**Comment by Jakuje** [comment]
@Nihlus can you send me the ATRs your card have? I would like to collect them in one place so we can detect issues in overlapping ATR masks such as #3106 in the future.

**Comment by Nihlus** [comment]
@Jakuje Unfortunately, I no longer have access to the cards I used while implementing support. I've changed workplaces and of course had to turn in my smartcard :(

I could try to get one of my previous colleagues in the loop on this issue to see if they're up for it.

**Comment by Jakuje** [comment]
> @Jakuje Unfortunately, I no longer have access to the cards I used while implementing support. I've changed workplaces and of course had to turn in my smartcard :(
> 
> I could try to get one of my previous colleagues in the loop on this issue to see if they're up for it.

Thank you! If you have someone that would be willing to provide this information, it would be helpful.

Lets continue discussion in #3154 -- I was not sure if tagging you there would work to send out the notification.

**Comment by viljo** [comment]
@Jakuje sorry guys have been keeping myself busy, expecially now when @Nihlus has left his work to me :) Here is the string reqested from @Nihlus card:
3b:7f:96:00:00:80:31:80:65:b0:85:03:00:ef:12:02:f0:82:90:00

**Pull request merged**
